// Pack A — Society Columnist, Retired Surgeon, Greenhouse Curator.
// Owned by the paper/payments & material-provenance writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_A: Record<Extract<ArchetypeId, 'columnist' | 'surgeon' | 'curator'>, AuthoredDialogueRoute[]> = {
  columnist: [
    r('columnist-ink', 'social', 'ink-fiber', 'You keep taking notes. What have you written down tonight?',
      'Names, who arrived with whom, the little disasters. Nothing you’d hang a man for.', 'thoughtful',
      s(
        c('Which note made you smudge the page like that?', 'A row in the gallery. My pen skidded and I got ink all over my hand.', 'suspicious'),
        c('Aren’t these just gossip notes?', 'Gossip pays my rent. But no, that isn’t tonight’s useful part.', 'angry'),
        c('Enough. Whose name did you tear out of that book?', 'Now you’re asking properly. And now we’re done with my notebook.', 'neutral'),
      ),
      s(
        c('What happened to the corner you tore off?', 'It was soaked with ink, so I ripped it away and tucked the scrap in my cuff to bin later.', 'worried'),
        c('Could someone else have used your pen?', 'Half the room borrows pens. Mine just leaks. That proves nothing.', 'suspicious'),
        c('Just tell me who was arguing.', 'No. Go find their names yourself — the page is mine.', 'angry'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the ink on her hand to the ink on the torn gallery page.',
        bargain: c('Help me quietly and I keep your source out of it?', 'Kind, for a hired man. The ink’s mine, yes — but a leaky pen isn’t a crime.', 'thoughtful'),
        challenge: c('The ink on your hand matches the torn page. Explain.', 'So compare them. A pen that leaks makes a mess, not a monster.', 'angry'),
      }),
    r('columnist-perfume', 'room', 'floral-perfume', 'Your perfume is awfully strong tonight. Why?',
      'The atomizer overfilled before dinner and sprayed everywhere. Gardenia beats damp wool, believe me.', 'neutral',
      s(
        c('Where were you when it sprayed?', 'At the drawing-room mirror. The bulb jammed and soaked my glove instead of my wrist.', 'thoughtful'),
        c('Is that scent in fashion this year?', 'Fashionable enough that three women will claim it tonight.', 'neutral'),
        c('You drowned yourself in scent to cover something. What?', 'Nonsense. My perfume doesn’t need cross-examining.', 'neutral'),
      ),
      s(
        c('What did you do with the soaked glove?', 'Carried it around a while. It left gardenia in every room I passed.', 'worried'),
        c('Could the conservatory flowers explain it?', 'Only to someone who can’t tell real gardenia from a bottle.', 'angry'),
        c('The perfume tells me nothing.', 'Then stop sniffing around it.', 'suspicious'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Show how the bulb soaked her glove but not her wrist.',
        bargain: c('No column, no fuss — who else touched that atomizer?', 'You do listen. Someone used it after me; that’s why the scent sits heavier on the glove than on me.', 'thoughtful'),
        challenge: c('The scent’s on the glove, not your skin. Explain that?', 'So a bulb sprayed cloth harder than wrist. That’s a spill, not a plot.', 'angry'),
      }),
    r('columnist-shorthand', 'timeline', 'torn-note', 'What was so important you wrote through dinner?',
      'A conversation worth keeping. I got it down in shorthand before either of them could take it back.', 'thoughtful',
      s(
        c('What made that note different from the rest?', 'I jotted a name, a room, and a time in the margin.', 'suspicious'),
        c('Will you just tell me the gossip?', 'No. Gossip given away for free isn’t worth having.', 'angry'),
        c('Give me the page, or I’ll assume the worst.', 'I meant to. We’re done with that page.', 'neutral'),
      ),
      s(
        c('Where’s that torn margin now?', 'I tore it off when one name got too dangerous to carry. It fell out of my folio somewhere.', 'worried'),
        c('Can anyone else read your shorthand?', 'A good reporter could. Most people here struggle with the menu.', 'neutral'),
        c('I’ll just ask the two who argued.', 'Do. They lie better than my notes.', 'suspicious'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Line up the “12:10” on her scrap with the time of the gallery row.',
        bargain: c('Trust me with the time and I’ll shield the rest?', 'All right. It reads 12:10, a lone C, and part of a room. A meeting, not an accusation.', 'thoughtful'),
        challenge: c('Your scrap already reads twelve-ten and a C. Whose?', 'You read torn paper boldly. A time and half a letter accuse no one.', 'angry'),
      }),
    r('columnist-society', 'intel', undefined, 'Who’s trying hardest to look like they’re enjoying this?',
      'Nearly everyone. The better question is who keeps checking the doors between smiles.', 'suspicious',
      s(
        c('Who keeps watching the doors?', 'It changes, but the nervous looks started after a row near the hall.', 'thoughtful'),
        c('Is nervousness always meaningful to you?', 'Only when it spoils otherwise good posture.', 'neutral'),
        c('Stop playing columnist and name who’s afraid.', 'Gladly. That’s the end of this one.', 'neutral'),
      ),
      s(
        c('What can I actually check about that row?', 'Two voices, a slammed door, and someone who reached the corridor just as it ended.', 'thoughtful'),
        c('Are you protecting the names?', 'I’m protecting my standards. Half-heard scraps aren’t fit to print yet.', 'suspicious'),
        c('That’s enough society news.', 'Then we’ve finished the social page.', 'neutral'),
      ),
      {
        bargain: c('Off the record — who frightened whom tonight?', 'Off the record, then. A quiet man went pale when the hall door slammed.', 'thoughtful'),
        challenge: c('Names now, or I start questioning your discretion.', 'Threaten my discretion and you’ll get nothing printable.', 'angry'),
      }),
    r('columnist-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply of medicine?',
      'I cut my thumb on a broken glass and borrowed something to clean it. It stung like a bad review.', 'worried',
      s(
        c('What did you borrow to clean it?', 'A little bottle from another guest’s kit. Clear stuff, very sharp.', 'thoughtful'),
        c('Is one small cut worth all this?', 'I write by hand. A ruined thumb is a professional disaster.', 'neutral'),
        c('That smell’s far too strong for one cut. Explain.', 'Believe what you like. The bottle wasn’t mine to keep. We’re done.', 'neutral'),
      ),
      s(
        c('Whose kit did the bottle come from?', 'Someone pressed it on me in the powder room and watched me dab it on.', 'worried'),
        c('Could that smell come from cleaning something else?', 'Half the house reeks of the sickroom tonight. Mine just closed a cut.', 'suspicious'),
        c('The smell tells me nothing.', 'Then stop breathing in my bad luck.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the guest who handed her the bottle to confirm it.',
        bargain: c('Name who lent it and I keep your clumsiness quiet?', 'Generous. Ask them — they watched me clean the cut, and the smell explains itself.', 'thoughtful'),
        challenge: c('Someone watched you use that bottle. Shall we ask them?', 'Ask. A borrowed bottle and a witness prove I bleed, not that I’m dangerous.', 'angry'),
      }),
    r('columnist-earth', 'timeline', 'fine-earth', 'How did pale grit get on your hem?',
      'I followed a promising row into the conservatory and knelt where a pot had been knocked over.', 'suspicious',
      s(
        c('Why did you kneel in the spilled grit?', 'There was a folded note under the bench. You pick those up gracefully or not at all.', 'thoughtful'),
        c('Do you always ruin a gown for gossip?', 'For the right gossip, I’d ruin a lot more.', 'neutral'),
        c('You didn’t kneel for a note. What were you really after?', 'My knees are my own business. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did that grit go after you stood up?', 'From my hem to my hand to the bench I steadied myself on. It gets everywhere.', 'worried'),
        c('Could the grit just be from the garden?', 'Too pale and too fine for garden soil. Someone tracked it in.', 'thoughtful'),
        c('The grit leads nowhere.', 'Then stop following my hemline.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the pale grit from the knocked-over pot to her hem, hand, and the bench.',
        bargain: c('Walk me through where the grit went and I stay discreet?', 'Kind of you. Pot to hem, hem to hand, hand to bench. That’s the whole trip.', 'thoughtful'),
        challenge: c('That grit puts you at the spilled pot. Well?', 'So it does. Kneeling by a spill makes me nosy, not dangerous.', 'angry'),
      }),
    r('columnist-wool', 'social', 'black-wool', 'Whose coat left black threads on your shoulders?',
      'A man draped his coat over me against the draught in the gallery. It shed all over me.', 'neutral',
      s(
        c('Which man lent you the coat?', 'One too dull to name and too warm to refuse. The wool caught on my clasp straight away.', 'thoughtful'),
        c('Do you make a habit of borrowing men’s coats?', 'Only when the house is cold and the company’s colder.', 'neutral'),
        c('That thread’s coarser than any dinner jacket. Explain.', 'Explain it yourself. The coat went back to its owner.', 'neutral'),
      ),
      s(
        c('Where exactly did the wool snag?', 'On my shoulder clasp, the moment he settled it round me.', 'worried'),
        c('Could the thread be from your own wrap?', 'My wrap is silk. That coarse black strand is his, not mine.', 'suspicious'),
        c('The thread proves nothing.', 'Then stop picking at it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the coarse strand can’t be her silk wrap — only the borrowed coat.',
        bargain: c('Point me to the coat and I keep the man’s name quiet?', 'Decent of you. My wrap’s silk; that strand is coarse wool, so it came off his coat, not me.', 'thoughtful'),
        challenge: c('You claim a borrowed coat — prove the thread isn’t yours?', 'Compare them. Silk against wool. Even you can tell those apart.', 'angry'),
      }),
    r('columnist-polish', 'room', 'metal-polish', 'Why is there a waxy metal smear on your fingers?',
      'I picked up a silver cigarette case to read the engraving. Someone had just polished it.', 'neutral',
      s(
        c('Whose case were you reading?', 'One with initials worth a paragraph, if they’re who I think.', 'suspicious'),
        c('Do you handle everything that isn’t yours?', 'Only the shiny, secretive things. They make the best columns.', 'neutral'),
        c('You handled more than a cigarette case. What else?', 'A lady doesn’t list her own fingerprints. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did the polish end up?', 'On my fingers and the clasp — right where a thumb opens it.', 'worried'),
        c('Could that smear be from your own compact?', 'My compact holds powder, not polish. That’s someone’s freshly shined silver.', 'thoughtful'),
        c('The smear is meaningless.', 'Then let go of my hand.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she smudged the engraving, and watch her correct you.',
        bargain: c('Help me quietly and the initials stay out of print?', 'You bargain well. I only touched the lid — whoever polished the base is your man.', 'thoughtful'),
        challenge: c('You wiped that case clean of more than polish. Well?', 'I read an engraving. Curiosity smudges silver; it isn’t a confession.', 'angry'),
      }),
    r('columnist-powder', 'social', 'face-powder', 'Why is there ivory powder on your sleeve?',
      'The powder room was a scrum of women all patting at once. A cloud like that doesn’t pick favourites.', 'neutral',
      s(
        c('Who were you crowded next to?', 'Two women sharing one mirror and, it seems, one compact’s worth of dust.', 'thoughtful'),
        c('Isn’t that just your own powder?', 'Mine stays on my face, not thrown across a sleeve like confetti.', 'neutral'),
        c('That powder was pressed on, not dusted. Explain.', 'My makeup isn’t evidence. We’re finished.', 'neutral'),
      ),
      s(
        c('Where did the stray powder settle?', 'My sleeve and cuff, where another woman brushed me reaching for the glass.', 'worried'),
        c('Couldn’t every woman here wear that shade?', 'Several claim to. Only one wears it as heavily as this.', 'suspicious'),
        c('The powder tells me nothing.', 'Then stop dusting me for it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the shade on her sleeve to the compact that shed it.',
        bargain: c('Point me to the compact and I keep your vanity private?', 'Kind. The shade on my sleeve is heavier than mine — match it to her compact.', 'thoughtful'),
        challenge: c('That powder’s on your sleeve. Care to explain?', 'Compare the shades. Mine’s lighter. Someone else’s cloud landed on me.', 'angry'),
      }),
    r('columnist-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with machine oil?',
      'My lighter jammed at the worst moment. A drop of oil and some bad language sorted it out.', 'suspicious',
      s(
        c('When did the lighter jam?', 'Just as the hall clock struck. I remember because I swore along with the chimes.', 'thoughtful'),
        c('Why not just ask someone for a light?', 'And owe them a favour? I’d rather oil a hinge than a debt.', 'neutral'),
        c('That’s far more oil than one lighter needs. Explain.', 'My vices are my own. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did the extra oil go?', 'Across my thumb and the lighter’s wheel, right as the chimes finished.', 'worried'),
        c('Could that oil be from a clock or a lock?', 'It could be from a dozen things. Mine was a stubborn flame.', 'suspicious'),
        c('The oil means nothing.', 'Then stop sniffing my fingers.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the oiled lighter to the exact stroke of the clock.',
        bargain: c('Give me the hour and I keep the rest off the page?', 'Fair. The lighter jammed on the clock’s stroke — the oil and the time agree, and neither accuses me.', 'thoughtful'),
        challenge: c('You oiled something at the exact stroke of the clock. Well?', 'So my vice keeps good time. A punctual lighter isn’t a plot.', 'angry'),
      }),
    r('columnist-wax', 'social', 'wax-resin', 'Why is there a brittle amber fleck on your cuff?',
      'I seal my riskier notes with wax. A slammed drawer knocked the stick before it cooled.', 'thoughtful',
      s(
        c('What did you need to seal?', 'A note too costly to leave loose in a folio.', 'suspicious'),
        c('Do columnists still bother with sealing wax?', 'The careful ones do. A licked flap protects nothing worth protecting.', 'neutral'),
        c('That’s not ordinary letter wax. Explain.', 'A sealed secret stays sealed. We’re finished with it.', 'neutral'),
      ),
      s(
        c('How did the wax get on your cuff?', 'It snapped as I pressed the seal — a warm fleck flicked onto my cuff before it set.', 'worried'),
        c('Could that fleck be restoration resin?', 'To a careless eye. Mine came off a sealing stick, not an antique.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then stop scraping at my cuff.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her press the seal again and show how the fleck flicks loose.',
        bargain: c('Show me how it broke and the letter stays sealed?', 'All right. I press here, the stick snaps there, the fleck lands on my cuff. No mystery.', 'thoughtful'),
        challenge: c('That amber fleck ties you to something sealed. Well?', 'So I seal my letters. Watch me do it — the wax breaks, nothing worse.', 'angry'),
      }),
    r('columnist-origins', 'connection', undefined, 'How does a woman like you end up writing about people for a living?',
      'I worked out young that the truth pays better than a diploma, and it’s better company too.', 'thoughtful',
      s(
        c('Who taught you to watch people?', 'My mother. She read a ballroom like a racing form. I got the eye, not the mercy.', 'thoughtful'),
        c('Do you ever tire of other people’s secrets?', 'The dull ones, yes. The dangerous ones keep me young.', 'neutral'),
        c('Spare me the memoir. I have questions.', 'As you like. I didn’t expect you to appreciate it anyway.', 'neutral'),
      ),
      s(
        c('What do you protect, when it comes to it?', 'The ones who can’t outrun a headline. I’ve spiked more stories than I’ve run.', 'worried'),
        c('And what do you never forgive?', 'Cruelty dressed up as charm. I keep a whole drawer for it.', 'suspicious'),
        c('We’re done reminiscing.', 'Pity. I was almost being honest.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what really keeps you in this trade?', 'Off the record: I still think the right sentence, printed at the right moment, can protect someone. Foolish, I know.', 'thoughtful'),
        challenge: c('All this charm — what are you hiding behind it?', 'Everyone here is hiding something. Mine just has better grammar.', 'angry'),
      }),
    r('columnist-guests', 'intel', undefined, 'Which of these guests do you actually know?',
      'Half of them, professionally. The other half wish I didn’t, which tells you plenty.', 'suspicious',
      s(
        c('Who here have you written about before?', 'A few. One never forgave me the paragraph; another begged me for the next one.', 'thoughtful'),
        c('Do any of them unsettle you?', 'Not really. But two go quiet when I walk in, and quiet is interesting.', 'neutral'),
        c('I need facts, not a guest list.', 'Then I’ll be poor dinner company tonight.', 'neutral'),
      ),
      s(
        c('Whose company do you actually enjoy?', 'The singer. She lies beautifully, and never about anything that matters.', 'thoughtful'),
        c('And whose do you avoid?', 'The ones who mistake my smile for stupidity. There are always a few.', 'suspicious'),
        c('That’s enough society talk.', 'As you wish. The guest list’s closed.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who here should I not turn my back on?', 'Quietly, then: watch the ones who are too composed. Grief has manners; guilt has a rehearsed face.', 'thoughtful'),
        challenge: c('You know them all — so who are you shielding?', 'I shield the powerless, not the guilty. Learn the difference before you accuse me.', 'angry'),
      }),
  ],

  surgeon: [
    r('surgeon-antiseptic', 'room', 'antiseptic', 'You keep washing your hands. What are you trying to get off them?',
      'Nothing sinister. The conservatory shears nicked my thumb and I dressed it properly.', 'neutral',
      s(
        c('What did you clean the cut with?', 'Carbolic solution from my case. It works, and the smell lingers.', 'thoughtful'),
        c('Was the cut serious?', 'Shallow. Your interest in it is misplaced.', 'angry'),
        c('You’ve scrubbed your hands raw. What are you washing off?', 'I don’t diagnose strangers, and I don’t explain myself to them either.', 'neutral'),
      ),
      s(
        c('Where did the carbolic get on your clothes?', 'The stopper slipped in the library. It soaked my cuff before I wiped the bottle.', 'worried'),
        c('Could the smell be plant treatment instead?', 'Possibly. I can’t tell the two apart from here.', 'suspicious'),
        c('Then your hands tell me nothing.', 'On that, we agree.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the carbolic on his cuff to the dressing in the library.',
        bargain: c('Whatever you dressed, I only want the truth of it?', 'Decent of you. I bound a cut in the library; the carbolic caught my cuff there, no more.', 'thoughtful'),
        challenge: c('The carbolic on your cuff matches a fresh dressing. Well?', 'Then it matches. A man who dresses a cut smells of carbolic.', 'angry'),
      }),
    r('surgeon-oil', 'social', 'blade-oil', 'Why bring an instrument case to a house party?',
      'Old habit. One hinge stuck when I opened it for a bandage.', 'suspicious',
      s(
        c('How did you free the hinge?', 'One drop of light oil and a probe. Forcing precision tools is barbaric.', 'thoughtful'),
        c('What’s inside the case?', 'Retired instruments. Their inventory is private and irrelevant.', 'angry'),
        c('Open the case and show me everything. Now.', 'It’s already done. Let the subject drop with it.', 'neutral'),
      ),
      s(
        c('Did the oil stay on the hinge?', 'No. It ran onto my finger and marked my sleeve before I noticed.', 'worried'),
        c('Could it have come from a clock?', 'The weight of it might match. I serviced no clocks.', 'suspicious'),
        c('The mechanism doesn’t matter.', 'Then there’s no reason to continue.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the oil vial from his hand to the hinge and his sleeve.',
        bargain: c('Just account for the case and I’ll leave you be?', 'Fair. The vial’s down one drop — my hand, my hinge, my sleeve.', 'thoughtful'),
        challenge: c('Only your hand touched that vial tonight. Shall we confirm?', 'Confirm it. A man oiling his own case gets oil on himself. Hardly damning.', 'angry'),
      }),
    r('surgeon-wax', 'timeline', 'wax-resin', 'What were you sealing earlier?',
      'A private medical letter. Retirement doesn’t stop people asking for an opinion.', 'thoughtful',
      s(
        c('What did you seal it with?', 'An amber stick warmed over a candle, as discretion used to require.', 'neutral'),
        c('Whose condition did it concern?', 'Confidentiality survives a dinner invitation.', 'angry'),
        c('Confidentiality won’t shield you tonight. Who was it for?', 'It will. That closes the matter.', 'neutral'),
      ),
      s(
        c('Did any of that wax leave your desk?', 'It snapped as it cooled. Brittle amber crumbs stuck to my lapel; I brushed them off.', 'worried'),
        c('Could it be restoration resin?', 'It might look it. A test would settle that, not guesswork.', 'suspicious'),
        c('I don’t need an analysis.', 'A rare bit of restraint. We’re finished.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Set the amber on his lapel against the recipient’s half of the seal.',
        bargain: c('Tell me who received it and the letter stays sealed?', 'You keep confidences well. The amber on my lapel is twin to their half.', 'thoughtful'),
        challenge: c('The recipient kept the matching seal. Care to explain?', 'So two halves of one seal agree. That proves I posted a letter.', 'angry'),
      }),
    r('surgeon-observation', 'intel', undefined, 'What have you noticed about the other guests?',
      'Fast pulses, shallow breathing, restless hands. Nerves, mostly — but nerves have a lot of causes.', 'thoughtful',
      s(
        c('Whose manner changed most suddenly?', 'One guest went very still after voices rose in the corridor.', 'suspicious'),
        c('Are you diagnosing nerves across a room?', 'Observing, not diagnosing. Mind the difference.', 'angry'),
        c('Drop the clinical act and tell me who you suspect.', 'Then this consultation’s over.', 'neutral'),
      ),
      s(
        c('What could a witness confirm exactly?', 'The row ended, a door opened, and that guest’s hands started shaking at once.', 'thoughtful'),
        c('Could thunder explain the reaction?', 'Possibly. But the shaking came first.', 'suspicious'),
        c('That’s enough observation.', 'Agreed. Any more would be guessing.', 'neutral'),
      ),
      {
        bargain: c('Between careful men — who worried you most?', 'Since you ask plainly: the still one. Stillness after a scare is rarely calm.', 'thoughtful'),
        challenge: c('You saw who flinched — name them, or should I wonder why not?', 'I’ll give you the symptom, not the name. Draw your own conclusion.', 'angry'),
      }),
    r('surgeon-ink', 'timeline', 'ink-fiber', 'Why are your fingers marked with blue-black ink?',
      'I was writing up a private note. A steady hand still uses a fountain pen — the ink comes with it.', 'neutral',
      s(
        c('When exactly were you writing?', 'Just before the corridor got loud. I noted the hour, as I always do.', 'thoughtful'),
        c('What note needs ink at a party?', 'A clinical opinion. Retirement hasn’t stopped people asking.', 'neutral'),
        c('That’s a lot of ink for a short note. Explain.', 'The nib split. That’s all of it. I won’t say more.', 'angry'),
      ),
      s(
        c('Where did the split nib leave its mark?', 'Across my finger and cuff, at the exact minute I dated the page.', 'worried'),
        c('Could another writer share that ink?', 'Any number could. Ink isn’t a diagnosis.', 'suspicious'),
        c('The ink tells me nothing.', 'On that we agree.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix his dated page to the moment the corridor grew loud.',
        bargain: c('Give me the hour and the patient stays unnamed?', 'Acceptable. The page carries the time I wrote it; ink and clock agree, and no name need leave my lips.', 'thoughtful'),
        challenge: c('You dated that page to a telling minute. Well?', 'So I recorded the hour precisely. Precision is my habit, not my guilt.', 'angry'),
      }),
    r('surgeon-earth', 'room', 'fine-earth', 'What is that pale grit on your cuff?',
      'A dusting powder from my case — bismuth, near enough. It spilled when I steadied the lid.', 'neutral',
      s(
        c('What’s the powder for?', 'Settling a stomach. Harmless, chalk-fine, easily mistaken for ordinary dust.', 'thoughtful'),
        c('Why open a medical case at dinner?', 'Because someone always feels faint before the soup. I came prepared.', 'neutral'),
        c('That’s not from any case. Where did you kneel?', 'Your guess is ahead of your evidence. I won’t follow it.', 'angry'),
      ),
      s(
        c('Where did the spilled powder land?', 'My cuff and glove. Under a lens the grains are far too even for garden soil.', 'thoughtful'),
        c('Could it match the conservatory grit?', 'On the surface. A look under magnification would part them at once.', 'suspicious'),
        c('The powder is irrelevant.', 'Then let’s not magnify it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the grains on his cuff to the powder in his case under a lens.',
        bargain: c('Show me the case and I’ll trouble you no further?', 'Reasonable. Set my cuff beside the tin — the grain matches the powder, not the flowerbeds.', 'thoughtful'),
        challenge: c('That grit could put you in the conservatory. Well?', 'Then examine it properly. My powder is even; garden grit isn’t. The lens will correct you.', 'angry'),
      }),
    r('surgeon-wool', 'social', 'black-wool', 'Where did that black wool thread on your sleeve come from?',
      'My travelling coat. Good wool, old cut. It’s caught on furniture in better houses than this.', 'neutral',
      s(
        c('What did the coat catch on tonight?', 'A rough edge on the library shelving, about where a reaching arm would meet it.', 'thoughtful'),
        c('Why wear a heavy coat indoors?', 'The house is cold and my circulation isn’t what it was. Dull, but true.', 'neutral'),
        c('That thread’s coarser than your coat. Explain.', 'You haven’t examined my coat, so you can’t say that. I won’t indulge the guess.', 'angry'),
      ),
      s(
        c('Where exactly did the seam give?', 'At the left cuff, where I braced on the shelf. The weave there has frayed for years.', 'worried'),
        c('Could the thread be from another dark coat?', 'It could. Which is exactly why it names no one on its own.', 'suspicious'),
        c('The thread proves nothing.', 'A rare and welcome conclusion.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show his frayed cuff can’t match the coarser strand found elsewhere.',
        bargain: c('Let me match the coat and clear it properly?', 'Sensible. Lay the strand against my cuff; if the weave differs, it isn’t mine.', 'thoughtful'),
        challenge: c('A black thread ties you to a place you deny. Well?', 'Then compare the weaves first. A shared colour isn’t a shared coat.', 'angry'),
      }),
    r('surgeon-polish', 'room', 'metal-polish', 'Why is there polish residue on your fingertips?',
      'I picked up a steel instrument to check its edge and found someone had waxed it like a trophy.', 'suspicious',
      s(
        c('Which instrument had been polished?', 'A blade from the case by the sideboard. Freshly buffed — an amateur’s idea of care.', 'thoughtful'),
        c('Why handle blades at a dinner party?', 'Old reflex. I can’t leave a badly kept edge alone.', 'neutral'),
        c('You handled more than one blade. What else?', 'I won’t inventory my own hands for you. That’s enough.', 'angry'),
      ),
      s(
        c('Where did the polish transfer?', 'From the handle to my thumb, then to the cloth I wiped it on. A clear little chain.', 'worried'),
        c('Could that residue be from the silver?', 'The compound’s much the same. Only its history tells you which object it’s from.', 'thoughtful'),
        c('The polish is meaningless.', 'Then we can set it down.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the polish from the waxed blade to his thumb and cloth.',
        bargain: c('Walk me through what you handled and I’ll keep it brief?', 'Fair. Handle to thumb, thumb to cloth — one blade, one chain, nothing past it.', 'thoughtful'),
        challenge: c('That polish links you to the silver. Well?', 'Then follow it from the blade I named, not the plate. It doesn’t reach where you hope.', 'angry'),
      }),
    r('surgeon-perfume', 'social', 'floral-perfume', 'Why does an expensive perfume cling to your lapel?',
      'A woman felt faint and I steadied her. Her scent stayed on my coat longer than my sympathy did.', 'neutral',
      s(
        c('Who was it you steadied?', 'A guest near the drawing room. I took her weight on my shoulder for a moment, no more.', 'thoughtful'),
        c('Do you make a habit of catching fainting women?', 'I make a habit of not letting people fall. Forty years is hard to unlearn.', 'neutral'),
        c('That scent is worn, not brushed on. Explain.', 'Your nose is wrong, and I’m not obliged to correct it.', 'angry'),
      ),
      s(
        c('Where did her perfume settle?', 'My lapel and sleeve, where she leaned. She can tell you so herself.', 'thoughtful'),
        c('Couldn’t you just be wearing it yourself?', 'A retired surgeon in gardenia? Ask anyone who knows me.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then let it evaporate out of your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the transfer against the woman he steadied.',
        bargain: c('Name her and I keep it quietly between us?', 'Decent. The woman I steadied will confirm it — her scent came to my lapel, not from me.', 'thoughtful'),
        challenge: c('That perfume puts you close to someone. Well?', 'Close enough to keep her upright. Ask her. Proximity isn’t proof.', 'angry'),
      }),
    r('surgeon-powder', 'timeline', 'face-powder', 'How did ivory face powder get onto your cuff?',
      'When the woman I steadied swayed, her compact sprang open and dusted us both.', 'surprised',
      s(
        c('What happened to the compact?', 'It flew from her hand. I caught her first and the powder second, all over my cuff.', 'thoughtful'),
        c('Why should I believe it was hers?', 'Because I’ve no use for ivory powder, and she plainly did.', 'neutral'),
        c('That powder was pressed on deliberately. Explain.', 'You’re building a scandal out of a spilled compact. I won’t help.', 'angry'),
      ),
      s(
        c('Show me how the compact sprang open?', 'She tipped, her hand opened, the lid snapped back, and the puff burst against my sleeve.', 'worried'),
        c('Could the powder be your own?', 'Only in a very different life. My case holds instruments, not cosmetics.', 'suspicious'),
        c('The powder means nothing.', 'Then we needn’t dust it further.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him reconstruct the catch that scattered the compact.',
        bargain: c('Show me exactly how it fell and I’ll keep her name out?', 'Gladly. She tips here, I catch there, the compact bursts — the powder does the rest.', 'thoughtful'),
        challenge: c('That powder ties you to something. Well?', 'Then let me show you how it spilled. The sequence blames the clasp, not the surgeon.', 'angry'),
      }),
    r('surgeon-note', 'suspicion', 'torn-note', 'What were you jotting in that cramped shorthand?',
      'Clinical notes. My own shorthand — times, symptoms, a dose. I tore off the used strip out of habit.', 'thoughtful',
      s(
        c('What did the notes record?', 'Observations on a guest who looked unwell. I write things down before memory tidies them.', 'suspicious'),
        c('Can anyone else read your shorthand?', 'A trained eye, maybe. To most people it’s a hedge of scratches.', 'neutral'),
        c('Those aren’t medical notes. Hand them over.', 'A clinician’s notes are confidential. That’s the end of it.', 'angry'),
      ),
      s(
        c('What happened to the torn strip?', 'It left my folio when I stood. I assumed it went in a bin, but perhaps not.', 'worried'),
        c('Could the marks pass for something else?', 'To an untrained reader, they could read as anything.', 'thoughtful'),
        c('I’ll ask the guest directly.', 'Do. They remember the evening less clearly than my notes.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Misread one symbol aloud and let him correct the record.',
        bargain: c('Read me the note plainly and the patient stays unnamed?', 'Very well — but you have the dose wrong. Read it correctly and it’s only a chart.', 'thoughtful'),
        challenge: c('This note reads like an admission. Well?', 'You’ve misread the symbol. Correct it and the “admission” becomes a dosage.', 'angry'),
      }),
    r('surgeon-retirement', 'connection', undefined, 'Why retire from a craft you clearly still love?',
      'Because a craft practised too long starts to cost more than it heals. I stopped before the sums turned against me.', 'thoughtful',
      s(
        c('Would you tell me what wore you down?', 'The hours, and one mistake I couldn’t undo. A tired hand is an honest one’s worst enemy.', 'worried'),
        c('Do you miss the work?', 'Every day. You don’t stop being a surgeon; you just stop being allowed.', 'neutral'),
        c('I didn’t ask for your memoirs.', 'No. Few people do, until they need one of us.', 'neutral'),
      ),
      s(
        c('What would you still fight for?', 'An honest record. I’ve signed enough that weren’t.', 'worried'),
        c('And what do you regret?', 'That I learned discretion before I learned courage. The order matters.', 'thoughtful'),
        c('We’re finished here.', 'As you wish. The consultation’s closed.', 'neutral'),
      ),
      {
        bargain: c('Between us — what keeps you awake at night?', 'Between us: a note I revised once, years ago. I’ve wanted to write one true line ever since.', 'worried'),
        challenge: c('You speak of honesty — so what are you concealing?', 'Every man conceals something. Mine’s a mistake, not a motive.', 'angry'),
      }),
    r('surgeon-diagnosis', 'social', undefined, 'What does a clinician’s eye tell you about this company?',
      'That most of them are sicker with nerves than with anything I could treat. Fear has a particular look.', 'thoughtful',
      s(
        c('Whose nerves concern you most?', 'One guest holds a stillness that clearly costs an effort. Calm that expensive is worth watching.', 'suspicious'),
        c('Is everyone here a patient to you?', 'Only in the sense that everyone’s a chart I’ve not been allowed to read.', 'neutral'),
        c('I want facts, not bedside theory.', 'Then you’ll find my company tedious. So be it.', 'neutral'),
      ),
      s(
        c('What symptom would you actually trust?', 'A tremor that comes before the thunder, not after. The nerves confess before the mouth does.', 'thoughtful'),
        c('Could you be reading too much into nerves?', 'Certainly. I said a look, not a diagnosis. Mind the difference.', 'suspicious'),
        c('That’s enough observation.', 'Agreed. Any more would be guessing.', 'neutral'),
      ),
      {
        bargain: c('Speak plainly — who worries you, and why?', 'Plainly: the one who doesn’t flinch. In my experience, practised calm is a symptom of its own.', 'thoughtful'),
        challenge: c('You watch everyone — so what are you watching for?', 'For the tell I missed once before. I won’t condemn a soul on a symptom.', 'angry'),
      }),
  ],

  curator: [
    r('curator-antiseptic', 'room', 'antiseptic', 'What were you spraying in the conservatory?',
      'An orchid was going rotten. I treated it before it could spread.', 'worried',
      s(
        c('What was in the sprayer?', 'A sharp sulphur wash. Watered down, but you can’t hide the smell.', 'thoughtful'),
        c('Was the orchid valuable?', 'It’s alive. That’s value enough. Price is a poor way to judge a plant.', 'neutral'),
        c('No more about orchids. What did that spray really clean?', 'Nothing but a plant. This can rest there.', 'neutral'),
      ),
      s(
        c('How did the wash get on your cuff?', 'The nozzle spat back at me. A sharp streak dried across my sleeve.', 'worried'),
        c('Could it be ordinary perfume?', 'Only if someone has very strange taste in perfume.', 'surprised'),
        c('The plant wash is irrelevant.', 'Then let’s stop disturbing the roots.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the wash on her cuff is crate sulphur, not medicine or motor oil.',
        bargain: c('No trouble for the plants — just walk me through it?', 'Gently, then. The sprayer kicked back; that sulphur streak is its doing, not medicine.', 'thoughtful'),
        challenge: c('That’s too concentrated for medicine or a motor — only your crates?', 'You’ve done your reading. It’s plant wash, yes — because I treat plants.', 'angry'),
      }),
    r('curator-earth', 'timeline', 'fine-earth', 'What were you repotting so late?',
      'Night jasmine. Its roots had cramped, and plants don’t wait for dinner to end.', 'neutral',
      s(
        c('What soil did you use?', 'A pale mineral mix, finer than garden earth and dry as chalk.', 'thoughtful'),
        c('Why should I care about a flowerpot?', 'You needn’t. The jasmine doesn’t care about you either.', 'neutral'),
        c('Repotting at this hour? I don’t believe it. Explain.', 'Believe what you like. We’re done digging here.', 'neutral'),
      ),
      s(
        c('Where did the pale mix end up?', 'On my shoes and hem. I tracked the grit out before I noticed.', 'worried'),
        c('Could old plaster look the same?', 'To an impatient eye, yes. The texture would tell them apart.', 'thoughtful'),
        c('Enough gardening.', 'Then this bed’s exhausted.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Trace the pale grit from her hem toward the study vent.',
        bargain: c('Show me the route and I’ll keep the plants out of it?', 'If you must. Someone swapped a root ball; the grit runs from the gallery rug toward the study vent.', 'thoughtful'),
        challenge: c('The grit trail runs to the study vent. Your doing?', 'So mineral mix travels on a hem. Follow it — it leads to a searched pot, not to me.', 'angry'),
      }),
    r('curator-note', 'social', 'torn-note', 'Why keep notes beside the flower beds?',
      'Growing records — dates, cuttings, what failed. I write them down before I forget.', 'thoughtful',
      s(
        c('What did you write down tonight?', 'A time, a slammed door, and some initials, in my own shorthand.', 'suspicious'),
        c('Do plants need initials?', 'People do. Plants are usually more honest.', 'neutral'),
        c('Those aren’t garden notes. Hand them over.', 'I will. We can prune this subject.', 'neutral'),
      ),
      s(
        c('What happened to that entry?', 'I tore off the margin to label a pot. Later the scrap was gone.', 'worried'),
        c('Could anyone read your shorthand?', 'Another grower might. To others it looks like nervous scratches.', 'thoughtful'),
        c('I’ll inspect the greenhouse myself.', 'Mind the roots. We’re done here.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Match the “12:10” in her shorthand to the overseas cable copy.',
        bargain: c('Your notes are safe with me — what does the shorthand hold?', 'Kindly meant. Read plainly, it gives a date, some initials, and 12:10.', 'thoughtful'),
        challenge: c('Your shorthand and the cable copy agree at twelve-ten. Well?', 'So a growing record and a cable agree on an hour. That’s a payment noted down, not a plot.', 'angry'),
      }),
    r('curator-growth', 'intel', undefined, 'Has anything in the house seemed out of place?',
      'A door that kept opening when the air was still. People used it more than they’ll admit.', 'thoughtful',
      s(
        c('Which movement struck you as deliberate?', 'Someone waited for the corridor to empty, then crossed without a glance at the plants.', 'suspicious'),
        c('Could they just dislike plants?', 'Plenty do. That alone proves very little.', 'neutral'),
        c('Stop tending your riddles and tell me who crossed.', 'As you wish. Some shoots aren’t worth training.', 'neutral'),
      ),
      s(
        c('What detail could identify the crossing?', 'A wet sole squeaked twice, right after the hall clock chimed.', 'thoughtful'),
        c('Could it have been a servant?', 'The stride was wrong. Though I can’t give you a name.', 'suspicious'),
        c('Nothing more on this.', 'Then we’ve pruned it cleanly.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who moved when they thought no one was watching?', 'Quietly, then. One figure crossed on a wet sole just as the clock chimed the hour.', 'thoughtful'),
        challenge: c('You clocked that crossing — withholding it helps no one?', 'I’m withholding a name I don’t have. The stride was wrong for a servant.', 'angry'),
      }),
    r('curator-ink', 'timeline', 'ink-fiber', 'How did blue-black ink get on your fingers?',
      'I ink my plant labels by hand. A written label outlasts a pencil, and a garden forgets everything else.', 'neutral',
      s(
        c('When were you writing labels tonight?', 'Just before the corridor stirred. I mark the hour on each cutting, so the time’s in my hand too.', 'thoughtful'),
        c('Why label plants during a party?', 'A cutting doesn’t wait for the guests to leave.', 'neutral'),
        c('That’s more ink than labels need. Explain.', 'The nib caught the card and flooded. That’s all. I’ll say no more.', 'angry'),
      ),
      s(
        c('Where did the flooded ink spread?', 'Across my finger and the label’s edge, at the hour I’d just written down.', 'worried'),
        c('Could another hand share that ink?', 'Many could. Ink keeps no loyalty to a gardener.', 'suspicious'),
        c('The ink tells me nothing.', 'Then let it dry, unremarked.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix her dated label to the moment the corridor stirred.',
        bargain: c('Give me the hour on the label and I keep the rest quiet?', 'Gently, then. The label carries the time I wrote it; ink and hour agree, and neither condemns me.', 'thoughtful'),
        challenge: c('You dated that label to a telling minute. Well?', 'So a cutting is time-stamped. Careful record-keeping isn’t a crime.', 'angry'),
      }),
    r('curator-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My work wrap — dark, coarse, older than most of my ferns. It snags on anything with a splinter.', 'neutral',
      s(
        c('What did the wrap catch on tonight?', 'An old cabinet by the passage. There’s a raised nail that took a thread as I passed.', 'thoughtful'),
        c('Why wear something so rough to a party?', 'Because a curator’s always a moment from lifting a heavy pot. Silk’s no help for that.', 'neutral'),
        c('That wrap took you somewhere you deny. Explain.', 'A snagged thread is a poor map. I won’t follow it for you.', 'angry'),
      ),
      s(
        c('Where did the thread travel after?', 'From the cabinet nail to my shoulder to the pot I carried past it. A plain trail.', 'worried'),
        c('Could the thread be someone else’s coat?', 'It could. Coarse black wool is common enough to accuse half the house.', 'suspicious'),
        c('The thread proves nothing.', 'Then let it lie where it fell.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the thread from the cabinet nail to her wrap and the pot.',
        bargain: c('Show me the trail and I keep the specimens out of it?', 'If you must. Nail to shoulder to pot — the whole quiet trip, nothing sinister on it.', 'thoughtful'),
        challenge: c('That thread puts you at the cabinet. Well?', 'So my wrap brushed a nail. Passing a cabinet isn’t a plot.', 'angry'),
      }),
    r('curator-polish', 'room', 'metal-polish', 'Why is there metal polish on your hands?',
      'I keep the brass sprayers and name-plates bright. Tarnish looks like neglect, and neglect frightens the patrons.', 'neutral',
      s(
        c('Which fittings did you polish?', 'The name-plates on the rarer plants, and the long brass sprayer I use each evening.', 'thoughtful'),
        c('Why does shiny brass matter to a plant?', 'It doesn’t. It matters to the patrons who pay for the plant.', 'neutral'),
        c('You polished more than plant fittings. What else?', 'I don’t keep a record of my own fingerprints. That’s enough.', 'angry'),
      ),
      s(
        c('Where did the polish transfer?', 'Only to the parts a hand grips — the sprayer’s neck, the plate’s edge.', 'worried'),
        c('Could that smear come from the silver?', 'The compound’s much alike. Its history, not its shine, tells you which.', 'thoughtful'),
        c('The polish is irrelevant.', 'Then we can let it dull.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the plate’s face too, and watch her correct you.',
        bargain: c('Help me quietly and the patrons stay unnamed?', 'Kindly. I brightened only the grips, never the faces — whoever handled the silver was less careful than I.', 'thoughtful'),
        challenge: c('That polish ties you to the silver. Well?', 'I polished brass. If the smear troubles you, follow it to the sprayers, not the plate.', 'angry'),
      }),
    r('curator-perfume', 'social', 'floral-perfume', 'That heavy perfume — surely a gardener’s vanity?',
      'A gardener smells of soil and sap, not a bottled garden. That perfume is someone else’s, caught on me.', 'suspicious',
      s(
        c('Then how did it get on you?', 'A guest hugged me by the conservatory door and left half her bottle on my collar.', 'thoughtful'),
        c('You really wear no scent at all?', 'Only what the plants lend me. Bottled gardenia insults the real thing.', 'neutral'),
        c('That scent is worn, not borrowed. Explain.', 'Insist all you like. I know my flowers from her chemist’s.', 'angry'),
      ),
      s(
        c('Where did the perfume transfer?', 'My collar and shoulder, where she leaned. My hands still smell of soil under it.', 'worried'),
        c('Could you have just brushed the blooms?', 'My blooms don’t smell that loud. This is a bottled scent, and not mine.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then stop breathing it in for me.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the bottled scent can’t come from her soil-and-sap hands.',
        bargain: c('Point me to who hugged you and I keep it quiet?', 'Gently. Smell my hands — soil, not gardenia. The perfume came off her, not out of any bottle of mine.', 'thoughtful'),
        challenge: c('That perfume puts you where you deny. Well?', 'Compare the scents. Mine’s green and low; hers is loud and bottled. Not the same.', 'angry'),
      }),
    r('curator-powder', 'room', 'face-powder', 'How did ivory powder get onto your shoulder?',
      'Someone squeezed past me in a narrow doorway and left half her compact on my sleeve.', 'neutral',
      s(
        c('Who pressed past you?', 'A woman in a hurry toward the hall. I felt her more than saw her face.', 'thoughtful'),
        c('Isn’t that just your own powder?', 'I dust plants with sulphur, not my face with ivory. It’s not mine.', 'neutral'),
        c('That powder was applied, not brushed. Explain.', 'You can build a fantasy out of a smudge. I won’t help.', 'angry'),
      ),
      s(
        c('Where did the powder settle?', 'My shoulder and upper sleeve — right where a passing arm would meet me.', 'worried'),
        c('Could several women wear that shade?', 'Several might. Only one wears it thick enough to shed it on strangers.', 'suspicious'),
        c('The powder means nothing.', 'Then let it settle out of your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the shade on her shoulder to the compact that shed it.',
        bargain: c('Help me find whose compact it is and I keep you clear?', 'Kindly meant. Match the shade to her compact, not my face — mine has never held ivory.', 'thoughtful'),
        challenge: c('That powder puts you near someone. Well?', 'Near a careless shoulder in a doorway. Compare the shade; it’s hers, not mine.', 'angry'),
      }),
    r('curator-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'The conservatory vent seized in the damp. One drop of oil on the ratchet and it opened again.', 'neutral',
      s(
        c('What exactly did you oil?', 'The vent’s winding gear, and my shears while the tin was open. Both had gone stiff.', 'thoughtful'),
        c('Why fuss with a vent tonight?', 'A closed vent in this wet would rot my orchids by morning. It couldn’t wait.', 'neutral'),
        c('That oil went somewhere it shouldn’t. Explain.', 'You suppose a lot from a slick thumb. I won’t indulge it.', 'angry'),
      ),
      s(
        c('Where did the oil end up?', 'On my thumb and cuff when the ratchet sprang back. It marks whatever I touch after.', 'worried'),
        c('Could that oil come from a clock or a lock?', 'The same light oil serves them all. Only its use tells you which.', 'suspicious'),
        c('The oil is irrelevant.', 'Then let the matter rust.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her work the seized vent again and show where the oil sprang.',
        bargain: c('Show me how the vent freed and I keep the plants out of it?', 'Gladly. I turn the gear here, the ratchet springs there, and the oil catches my thumb. No mystery.', 'thoughtful'),
        challenge: c('That oil ties you to a mechanism. Well?', 'A garden vent. Watch me free it; the oil lands exactly where honest work would put it.', 'angry'),
      }),
    r('curator-wax', 'social', 'wax-resin', 'What’s that amber fleck on your sleeve?',
      'Grafting wax. I seal the join where two cuttings meet, so the graft doesn’t weep sap and fail.', 'thoughtful',
      s(
        c('What were you grafting tonight?', 'A rose stock onto hardier root. The wax goes on warm, and warm wax flicks where it likes.', 'suspicious'),
        c('Is grafting really a job for a party?', 'A graft takes when it takes, not when the invitations allow.', 'neutral'),
        c('That’s sealing wax, not garden wax. Explain.', 'You mistake my work for a clerk’s. I won’t argue over a guess.', 'neutral'),
      ),
      s(
        c('How did the wax reach your sleeve?', 'It snapped off the warming stick and caught my cuff. The under-gardener held the graft; ask him.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'Similar to look at. A grower could tell my grafting wax from his relic-resin at a glance.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then let the graft heal in peace.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the grafting wax against the joined cutting it sealed.',
        bargain: c('Show me the graft and I keep the collection out of it?', 'Kindly. The sealed cutting’s right there; its wax is twin to my sleeve, and both are honest garden work.', 'thoughtful'),
        challenge: c('That wax ties you to something sealed. Well?', 'To a rose graft. Look at the cutting — the wax matches it, not any hidden thing.', 'angry'),
      }),
    r('curator-calling', 'connection', undefined, 'What draws a person to spend a life among plants?',
      'They ask nothing and forgive everything, if you’re patient. People rarely manage either.', 'thoughtful',
      s(
        c('Would you tell me how you started?', 'One sick fern I refused to give up on. It lived. I’ve been outnumbered by green things ever since.', 'thoughtful'),
        c('Do you honestly prefer plants to people?', 'Plants don’t lie about where they’ve been. That alone recommends them.', 'neutral'),
        c('I’ve no time for gardening philosophy.', 'Few do, until something they love starts to wilt.', 'neutral'),
      ),
      s(
        c('What would you protect above all?', 'The living collection. Some of those plants exist nowhere else.', 'worried'),
        c('And what would you never do?', 'Trade a living thing for my own comfort. I’ve been asked. I refused.', 'suspicious'),
        c('We’re finished here.', 'Then mind the roots on your way out.', 'neutral'),
      ),
      {
        bargain: c('Quietly — what are you truly afraid of tonight?', 'Quietly: that someone seizes the glasshouse and lets the rarest of them wither to make a point. That would be the real crime.', 'worried'),
        challenge: c('All this patience — what’s it covering?', 'Not guilt. A gardener who tends contraband is still a gardener. Learn the difference before you dig.', 'angry'),
      }),
    r('curator-company', 'intel', undefined, 'What do you make of the other guests?',
      'They crowd toward whoever shines brightest, like seedlings to a lamp. It tells you who needs watching.', 'thoughtful',
      s(
        c('Who here leans the wrong way?', 'One turns away from the light instead of toward it. In a plant that means rot; in a person, secrets.', 'suspicious'),
        c('Do you judge everyone by their leaves?', 'It’s a surer method than conversation. Leaves can’t flatter.', 'neutral'),
        c('I want names, not gardening.', 'Names I don’t have. Impressions I have plenty of.', 'neutral'),
      ),
      s(
        c('Whose company do you value?', 'The surgeon. He listens the way a good grower does — slowly, to the quiet parts.', 'thoughtful'),
        c('And whose unsettles you?', 'The one who admired my rarest plant and asked only what it would fetch.', 'suspicious'),
        c('That’s enough.', 'Then the bed’s turned over. We can stop.', 'neutral'),
      ),
      {
        bargain: c('Off the record — who worries you most?', 'Off the record: the one who priced my orchid instead of seeing it. People who value only price frighten me.', 'thoughtful'),
        challenge: c('You watch them all — so whom are you shielding?', 'I shield living things, not the guilty. Don’t confuse my care for complicity.', 'angry'),
      }),
  ],
}
