// Pack B — Stage Magician, War Correspondent, Estate Accountant.
// Owned by the key/route & paper/payments writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_B: Record<Extract<ArchetypeId, 'magician' | 'correspondent' | 'accountant'>, AuthoredDialogueRoute[]> = {
  magician: [
    r('magician-wool', 'room', 'black-wool', 'Where did that black wool thread on your sleeve come from?',
      'My coat — black stage wool, old and much-abused. It caught on something tonight and gave up a thread or two.', 'neutral',
      s(
        c('What did it catch on?', 'A brass tooth in the west passage. The hidden pocket snagged and the weave started to give.', 'worried'),
        c('What do you carry in a coat like that?', 'A magician’s pocket holds disappointment and a contract or two.', 'suspicious'),
        c('What did that snag really cost you?', 'A thread and a good exit. We’ll leave the coat closed.', 'neutral'),
      ),
      s(
        c('Where exactly did the thread pull free?', 'As I stepped clear, a short dark strand stayed hooked on the tooth behind me.', 'thoughtful'),
        c('Could another black coat leave that thread?', 'Certainly. Black wool is far less exclusive than my billing.', 'neutral'),
        c('The coat alone isn’t enough.', 'No — and that’s where we’ll stop.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the latch to his coat seam.',
        bargain: c('Tell me what you reached for — I’ll keep the name out of it.', 'Between us: a paper that ought to bear another man’s name. The coat caught as I reached for it.', 'worried'),
        challenge: c('You tore that coat doing something you won’t admit.', 'You have me at a door, not at any crime. I went for a contract, not for a soul.', 'angry'),
      }),
    r('magician-powder', 'social', 'face-powder', 'Where did that pale powder on your hands come from?',
      'Stage powder. A pale face floats beautifully once the room goes dark — I dust it on for the effect, and my compact chose tonight to crack.', 'surprised',
      s(
        c('How did you prepare the effect?', 'Ivory stage powder, a puff, and a compact that spilled more than it should have.', 'thoughtful'),
        c('Did anyone watch you set it up?', 'Rehearsals are private. Nobody watches the seams being sewn.', 'angry'),
        c('Why is your powder somewhere you say you weren’t?', 'Now that’s the real question. And that’s where I stop.', 'neutral'),
      ),
      s(
        c('Where did the spilled powder settle?', 'My lapel, a lamp I’d hidden, and the little case I palm cards from.', 'worried'),
        c('Couldn’t that be ordinary face powder?', 'The powder could pass. The skill behind it couldn’t.', 'neutral'),
        c('A cracked compact is hardly proof.', 'Then the mirror goes dark, and so does this.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder on the switch to his cracked compact.',
        bargain: c('Show me the effect and I leave your method out of it.', 'Watch the lamp, not my hands — that’s exactly where the powder gives the method away.', 'thoughtful'),
        challenge: c('That powder marks more than a stage trick. Where else did it land?', 'A lamp, a switch — stage props, not proof. Ivory dust signs no confession.', 'suspicious'),
      }),
    r('magician-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'A prop with a sulky spring — the Mercy Box, if you want its stage name. One drop of oil along the false back and it behaved.', 'suspicious',
      s(
        c('How did you free the spring?', 'A pin, some patience, and one drop of precision oil along the false back.', 'thoughtful'),
        c('What does the Mercy Box actually do?', 'It performs mercy. The workings are older than my name on the poster.', 'neutral'),
        c('Open the box. Show me what you oiled.', 'Not tonight. That subject closes with the lid.', 'neutral'),
      ),
      s(
        c('Where did the extra oil end up?', 'On my thumb, then my cuff, when I reset the mechanism behind my back.', 'worried'),
        c('Wouldn’t a sewing machine use that oil?', 'And clocks, and adding machines. A crowded little alibi, detective.', 'suspicious'),
        c('The oil’s too common to matter.', 'A poor audience indeed. We’re finished.', 'angry'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him open the false back the same way again.',
        bargain: c('Show me how you freed it and I won’t pry into the contracts.', 'Then watch: oil here, the back lifts here. The hands are mine; the invention wasn’t.', 'thoughtful'),
        challenge: c('That oil went somewhere it shouldn’t. What are you hiding in there?', 'I oiled a spring. What it hides is a matter of contracts, not of guilt.', 'angry'),
      }),
    r('magician-sightline', 'intel', undefined, 'What did everyone else miss tonight?',
      'They watched the loud hand. The quiet one opened a side door while every head turned.', 'suspicious',
      s(
        c('What made them look away?', 'A dropped tray. Everyone glanced at the noise.', 'thoughtful'),
        c('So someone used the distraction?', 'Only the useful accidents get used.', 'neutral'),
        c('Who opened the door?', 'That’s where I stop.', 'neutral'),
      ),
      s(
        c('Did you see anything that could identify them?', 'A polished ring caught the lamp for a second beside the doorframe.', 'surprised'),
        c('Could that just have been glass?', 'Glass doesn’t curl its fingers around a handle.', 'suspicious'),
        c('That’s too thin to chase.', 'Then we’re done.', 'neutral'),
      )),
    r('magician-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink on your fingers?',
      'A prediction trick. The volunteer names a word, I write it, and the ink’s meant to vanish. Tonight it sulked.', 'surprised',
      s(
        c('When did you perform the effect?', 'Just as the clock struck. I like to time a reveal to a chime; it steals the applause.', 'thoughtful'),
        c('What’s the trick, exactly?', 'A magician who explains it is just a man with a wet pen. Watch, don’t audit.', 'neutral'),
        c('That’s far too much ink for a card.', 'The vanishing part failed and the pen wept. That’s the whole of it.', 'neutral'),
      ),
      s(
        c('Where did the stubborn ink settle?', 'My fingers and the card’s edge, at the exact stroke I performed against.', 'worried'),
        c('Could another writer own that ink?', 'Half the house scribbles. The ink’s a common prop, not a signed confession.', 'suspicious'),
        c('That’s enough about the ink.', 'Then the curtain falls on it.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the inked card to the clock stroke he named.',
        bargain: c('Give me the time of the trick — I’ll leave the flourish alone.', 'Generous. The card’s inked to the chime I played to; the hour and the stain agree, nothing more.', 'thoughtful'),
        challenge: c('That’s a lot of ink for one card. You timed more than a trick.', 'So my timing’s theatrical. A punctual flourish isn’t a plot.', 'angry'),
      }),
    r('magician-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply of medicine?',
      'Spirit-gum solvent. It lifts a false moustache and reeks like a sickroom, but it’s pure stagecraft.', 'neutral',
      s(
        c('What were you gumming and un-gumming?', 'A quick-change disguise for the second act. The solvent bites worse than the glue.', 'thoughtful'),
        c('Why should I believe it isn’t the real thing?', 'Because a surgeon’s carbolic and my solvent only share a smell, not a purpose.', 'neutral'),
        c('That smell’s a doctor’s, not a conjuror’s.', 'You trust your nose over my craft. The trick, and this, are closed.', 'neutral'),
      ),
      s(
        c('Where did the solvent touch you?', 'My fingertips and cuff, where I peeled the disguise. It dries fast and smells loud.', 'worried'),
        c('Could it be surgical antiseptic instead?', 'Only to a nose in a hurry. Test the fluid and it’ll admit it’s theatre, not medicine.', 'suspicious'),
        c('That’s enough about the smell.', 'Then stop breathing in my props.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the smell is stage solvent, not carbolic.',
        bargain: c('Let me test the fluid — I’ll keep the disguise quiet.', 'Fair trade. Test it — spirit gum, not carbolic. The smell’s the only thing they share.', 'thoughtful'),
        challenge: c('That smells like a surgeon’s antiseptic. You’re covering a wound.', 'Analyse it. My solvent lifts glue; it never touched a wound. A shared reek isn’t a shared crime.', 'angry'),
      }),
    r('magician-earth', 'social', 'fine-earth', 'What’s that pale grit ground into your palms?',
      'Grip chalk, near enough — a fine powder I dust on for a clean palm and a cleaner vanish.', 'neutral',
      s(
        c('What do you use the powder for?', 'To keep a coin from betraying me with sweat. A slick palm ruins the best sleight.', 'thoughtful'),
        c('Isn’t that just garden dust?', 'It’s far finer than any flowerbed, and it’s from my own tin, not your conservatory.', 'neutral'),
        c('That grit came off a floor, not a tin.', 'You’d rewrite my act into a crawl through the dirt. I decline.', 'neutral'),
      ),
      s(
        c('Where did the powder end up?', 'My palms, my cuffs, and the little case I load coins from. It clings to everything.', 'worried'),
        c('Could it match the conservatory grit?', 'At a glance, maybe. Side by side, my chalk’s finer and paler than any soil.', 'suspicious'),
        c('The grit isn’t helping.', 'Then let the dust settle where it likes.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the powder on his palms to his grip tin.',
        bargain: c('Show me your tin and I won’t chase the conservatory.', 'Kindly done. Set my palm beside the tin; the grip chalk matches, the garden grit doesn’t.', 'thoughtful'),
        challenge: c('That grit came from the conservatory. Your chalk story won’t hold.', 'Compare it properly. My chalk’s even; soil isn’t. The samples will part ways.', 'angry'),
      }),
    r('magician-polish', 'room', 'metal-polish', 'Why are your hands filmed with metal polish?',
      'The linking rings have to catch the light or the illusion dies. I buff them till they almost wink at the crowd.', 'thoughtful',
      s(
        c('Which props did you polish?', 'The rings and a steel cup or two. A dull prop shows its seams; a bright one keeps my secrets.', 'suspicious'),
        c('Do you polish everything you touch?', 'Only the things that have to lie convincingly under a lamp.', 'neutral'),
        c('What else did you buff tonight?', 'A magician doesn’t catalogue his own hands. Let it go.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the ring’s inner curve — right where a grip would sit.', 'worried'),
        c('Could that film be from the silver?', 'It’s a cousin to it. Only its history tells you which object it left.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then let it lose its shine.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he polished the outer face — see if he corrects you.',
        bargain: c('Help me quietly and I leave the method alone.', 'Obliging. I brighten only the inner curve I grip; whoever handled the silver was less tidy than I.', 'thoughtful'),
        challenge: c('That polish matches the silver. You handled more than a prop.', 'I shine props. Follow the film to my rings, not to a plate I never lifted.', 'angry'),
      }),
    r('magician-perfume', 'social', 'floral-perfume', 'Why does a lady’s perfume cling to your sleeve?',
      'The vanishing bouquet. I produce flowers, a lady takes them, and her scent stays on me after the blooms are gone.', 'neutral',
      s(
        c('Who took the bouquet from you?', 'A guest near the ballroom who played my volunteer. The whole room watched.', 'thoughtful'),
        c('Are the flowers real or an illusion?', 'Real enough to smell, false enough to vanish. The perfume, sadly, won’t obey me.', 'neutral'),
        c('That scent looks worn, not brushed on.', 'You mistake stagecraft for vanity. The act’s over and so is this.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My cuff and lapel, where she pressed the bouquet back into my hands. Witnesses aplenty.', 'thoughtful'),
        c('Couldn’t you just be wearing the scent?', 'A conjuror in gardenia? Ask the room; they saw the lady, not a bottle in my pocket.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then let it fade with the applause.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the guests who watched the bouquet trick.',
        bargain: c('Name the volunteer and I keep it off the record.', 'Fair. The volunteer and the room will confirm it — her scent came to my sleeve in full view.', 'thoughtful'),
        challenge: c('That perfume puts you alone with someone. Who was it really?', 'To a volunteer, in front of an audience. Ask them. A witnessed trick isn’t a secret meeting.', 'angry'),
      }),
    r('magician-wax', 'timeline', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'A sealed prediction. I write the outcome, seal it in wax before witnesses, and open it at the finish. The stick snapped as I pressed it.', 'thoughtful',
      s(
        c('What did the prediction say?', 'That would spoil the ending. The seal matters more than the words — a broken one ruins the wonder.', 'suspicious'),
        c('Do conjurors still use sealing wax?', 'The honest ones do. A licked flap can be steamed; hot wax can’t be faked mid-trick.', 'neutral'),
        c('That’s no stage prop. Explain the wax.', 'A sealed prediction stays sealed until the reveal. The subject seals with it.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'It snapped off the warming stick as I pressed the envelope; a warm fleck flicked to my cuff.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'To a hasty eye. Mine came off a sealing stick, not a relic.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then let the envelope keep its secret.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him seal another envelope and show how the fleck lands.',
        bargain: c('Show me how you seal it and I leave the prediction unread.', 'Watch: I press here, the stick cracks there, the fleck lands on my cuff. No mystery, only method.', 'thoughtful'),
        challenge: c('That wax sealed something you won’t show me. What?', 'To a prediction envelope. Have me seal another; the wax breaks the same, and proves nothing worse.', 'angry'),
      }),
    r('magician-note', 'social', 'torn-note', 'What’s that torn scrap of shorthand you keep palming?',
      'A cue card. My own cramped marks — running order, a gag, the beat to drop a coin. I tore the used corner off between effects.', 'suspicious',
      s(
        c('What was written on the card?', 'The order of the act and a private note or two. Meaningless to anyone who can’t read a conjuror’s hand.', 'thoughtful'),
        c('Can anyone else read your marks?', 'A fellow performer, perhaps. To the rest it’s a hedge of scribbles.', 'neutral'),
        c('That’s no cue card. Hand it over.', 'A magician’s notes stay in a magician’s palm.', 'neutral'),
      ),
      s(
        c('What happened to the torn corner?', 'It slipped from my palm mid-flourish. From my hand to my pocket to the floor — I couldn’t swear which.', 'worried'),
        c('Could the marks pass for something sinister?', 'To a suspicious reader, anything can. That’s the trouble with reading over a shoulder.', 'thoughtful'),
        c('I’ll read it myself.', 'Then mind you don’t mistake the running order for a plot.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the torn cue card from his palm to where it fell.',
        bargain: c('Tell me where the card went — I won’t dig into the running order.', 'Fair. Palm to pocket to floor — the whole clumsy trip, and nothing but a running order on it.', 'thoughtful'),
        challenge: c('That scrap puts you somewhere you deny. Own the path.', 'A dropped cue card. Follow it from my palm; it leads to a stage, not a scheme.', 'angry'),
      }),
    r('magician-craft', 'connection', undefined, 'How did you end up doing this for a living?',
      'I learned young that the truth disappoints and a good trick never does. I chose the kinder one.', 'thoughtful',
      s(
        c('Who taught you?', 'A woman with faster hands than mine. The posters never named her. I owe her more than a flourish.', 'worried'),
        c('Is it lonely work?', 'A little. The audience loves the trick, never the man working it.', 'neutral'),
        c('I have other questions.', 'Of course. Everyone skips to the ending.', 'neutral'),
      ),
      s(
        c('What would you fix if you could?', 'A name. Someone’s invention wears my billing, and that’s weighed on me a long time.', 'worried'),
        c('What will you never tell?', 'How the trick’s done — and what it cost the person who first dreamed it.', 'suspicious'),
        c('We’re finished here.', 'Pity.', 'neutral'),
      ),
      {
        bargain: c('Honestly — what do you want tonight?', 'To hand back a credit I borrowed too long.', 'thoughtful'),
        challenge: c('What are you steering me away from?', 'The method, not a crime. Guarding secrets is my job — not my guilt.', 'angry'),
      }),
    r('magician-audience', 'intel', undefined, 'Looking at this room — what do you see?',
      'Everyone here is running an act, and most of them are under-rehearsed. I can see the wires.', 'suspicious',
      s(
        c('Who’s slipping?', 'One guest keeps checking a pocket the way an amateur checks a hidden card.', 'thoughtful'),
        c('You think everyone’s performing?', 'Everyone in evening dress. Question is who practised their story and who made it up.', 'neutral'),
        c('I need a name.', 'Then you’ll be a hard house tonight.', 'neutral'),
      ),
      s(
        c('What would you trust as a real sign?', 'The pause before an answer. A prepared lie comes too smoothly.', 'thoughtful'),
        c('Could you just be reading nerves?', 'Every showman can. I’m offering what I see, not a verdict.', 'suspicious'),
        c('That’s enough.', 'Then we’re done.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who’s trying too hard to look calm?', 'The one whose hands are too still. That stillness is a performance, and a poor one up close.', 'thoughtful'),
        challenge: c('Who are you covering for?', 'No one. I guard methods, not culprits.', 'angry'),
      }),
  ],

  correspondent: [
    r('correspondent-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink on your fingers?',
      'Drafting a story — storm, stranded guests, short tempers. Blue-black ink, and a page I tore straight through when something startled me mid-line.', 'neutral',
      s(
        c('What startled you?', 'The gallery door slammed and my pen went straight through the page.', 'suspicious'),
        c('Who’s the story about?', 'Everyone. Names wait until the facts show up.', 'neutral'),
        c('Show me the draft. What time did you write down?', 'Copy’s spiked. Topic’s closed.', 'neutral'),
      ),
      s(
        c('When exactly did the pen tear it?', 'On the slam. I’d just written the hour, and the nib buried in the crease.', 'thoughtful'),
        c('Couldn’t another writer use that ink?', 'Columnists. Accountants. Anyone with old habits.', 'neutral'),
        c('The draft isn’t helping.', 'Agreed. No more copy.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the torn page to the gallery door slam.',
        bargain: c('Give me the hour — keep your source out of it.', 'Fair trade. The hour on that page is the one thing I’ll stand behind — the name stays mine.', 'thoughtful'),
        challenge: c('You wrote a time you shouldn’t have known yet. How?', 'I wrote what I heard through a door. Hearing a thing isn’t doing it.', 'angry'),
      }),
    r('correspondent-wool', 'room', 'black-wool', 'Where did that black wool thread on your sleeve come from?',
      'Field habit — heavy wool, pockets where I expect them. A seam of it caught on something tonight and opened another inch.', 'neutral',
      s(
        c('What did the seam catch on?', 'A brass latch in the west passage — while I followed a figure whose limp quit the moment it felt unwatched.', 'worried'),
        c('Expecting a battlefield in here?', 'I expect exits. Battlefields are optional.', 'suspicious'),
        c('You didn’t tear that coat sitting still. Where were you?', 'No. But I’ll forget you asked.', 'neutral'),
      ),
      s(
        c('Where exactly did the seam give?', 'On the left sleeve, where the latch bit as I passed it.', 'thoughtful'),
        c('Couldn’t a driver’s uniform shed the same wool?', 'Same colour, similar weave. Test it.', 'neutral'),
        c('The coat isn’t helping.', 'Then stop pulling the thread.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare his coat seam to the fibre on the latch.',
        bargain: c('Tell me what you saw in that passage — off the record.', 'Off the record: someone crossed that passage faking a limp. My coat paid the toll following them.', 'worried'),
        challenge: c('You didn’t tear that coat just watching. What did your hands do?', 'The latch marked my sleeve, not my hands. Watching a man isn’t the same as touching him.', 'angry'),
      }),
    r('correspondent-note', 'social', 'torn-note', 'What’s that torn scrap of shorthand you keep on you?',
      'Notes from a source. Nervous type — gave me a time, a room, and an envelope, all in tight shorthand.', 'suspicious',
      s(
        c('What made the source so nervous?', 'They heard the exchange and feared their initials would put them in it.', 'thoughtful'),
        c('Will you give me the source’s name?', 'No. Source protection outlives a dinner invitation.', 'angry'),
        c('Protecting a source won’t cover you. Read me the page.', 'It stays buried. We’re done.', 'neutral'),
      ),
      s(
        c('What survives on that shorthand page?', 'A time, “gallery,” an envelope — and a false limp. The initials I tore away.', 'worried'),
        c('Could your marks pass for gossip notes?', 'Easily. Meaning depends on who taught the hand.', 'neutral'),
        c('I’ll find another witness.', 'Do. This source is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Match his shorthand to the singer’s coded reply.',
        bargain: c('Confirm the time and room — keep the initials out.', 'That I can do. The hour and the gallery are solid; the name stays out of your notebook.', 'thoughtful'),
        challenge: c('You’re hiding those initials to protect yourself.', 'Believe that if you like. I burned a source once. Never again.', 'angry'),
      }),
    r('correspondent-exits', 'intel', undefined, 'Who’s been using the exits tonight?',
      'Most drifted. One waited, checked both corridors, then moved with purpose.', 'suspicious',
      s(
        c('When?', 'Just after the clock struck. The rain covered the first few steps.', 'thoughtful'),
        c('Couldn’t they just want privacy?', 'Could. Privacy usually walks slower.', 'neutral'),
        c('Who was it?', 'Filed and closed.', 'neutral'),
      ),
      s(
        c('Anything that would identify them?', 'A limp for three steps, then none once they judged the corridor empty.', 'surprised'),
        c('Couldn’t that just be bad shoes?', 'Could. So could an act. Check it yourself.', 'suspicious'),
        c('That’s too thin.', 'Then we’re done.', 'neutral'),
      )),
    r('correspondent-antiseptic', 'room', 'antiseptic', 'Why do your hands reek of something medicinal?',
      'Field kit. Cleaned a cut the way I learned in worse places than this. Sharp stuff. Not the surgeon’s shelf.', 'neutral',
      s(
        c('What did you cut yourself on?', 'A splintered window frame while I watched the drive. Old habit — check the exits, bleed a little.', 'thoughtful'),
        c('Why carry field antiseptic to a dinner?', 'Because I’ve needed it at dinners before. Bad weekends leave marks.', 'neutral'),
        c('That’s a doctor’s antiseptic.', 'It isn’t. Same smell, different bottle. Believe your nose if you like; I’m done.', 'neutral'),
      ),
      s(
        c('Where did the antiseptic touch your clothes?', 'Cuff and knuckle. It dries loud and lingers, same as the surgeon’s — but it isn’t his.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test it. Mine’s a soldier’s bottle. The two only share a reek.', 'suspicious'),
        c('That’s enough about the smell.', 'Agreed. Spike the thread.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid is field antiseptic, not carbolic.',
        bargain: c('Let me test the bottle — I won’t call it a surgeon’s.', 'Fine. Test it — field kit, not carbolic. Two things can stink alike and share nothing else.', 'thoughtful'),
        challenge: c('That’s the surgeon’s antiseptic on your sleeve. Explain it.', 'Analyse it. Mine came from a kit, not an operating tray. A shared smell isn’t a shared hand.', 'angry'),
      }),
    r('correspondent-earth', 'timeline', 'fine-earth', 'How did pale grit get onto your knees and cuffs?',
      'Went low by the conservatory glass to watch the drive without being seen. Old reflex. The floor was gritty.', 'neutral',
      s(
        c('What were you watching for?', 'Whoever came and went in the storm. You learn to read a doorway from the floor up.', 'thoughtful'),
        c('Do you always crawl around a party?', 'When the story’s outside and the crowd’s inside, yes. Beats asking politely.', 'neutral'),
        c('That grit looks like digging, not watching.', 'Think what you like. I knelt, I watched, I left. That’s the whole dispatch.', 'neutral'),
      ),
      s(
        c('Where did the grit end up?', 'Knees, cuffs, the sill I braced on. Pale stuff, finer than dirt. It travelled with me.', 'worried'),
        c('Could it match the conservatory soil?', 'Close, not the same. Someone tracked this in before I ever knelt in it.', 'suspicious'),
        c('The grit isn’t helping.', 'Then strike it.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him take the same watch-post and show how the grit transferred.',
        bargain: c('Show me where you knelt and I leave your watch-post alone.', 'Fair. I go low here, brace on the sill there — the grit lands on my knees. A watcher’s mess, nothing worse.', 'thoughtful'),
        challenge: c('That grit puts you in the conservatory for more than watching.', 'To a watch-post. Have me show you the crouch; it explains every grain.', 'angry'),
      }),
    r('correspondent-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'Cleaned my lighter and flask. Bad habit in a storm — a man tends his small machines when the big story stalls.', 'neutral',
      s(
        c('What exactly did you polish?', 'The lighter’s case and the flask’s cap. Both had gone dull in my pocket. Idle hands.', 'thoughtful'),
        c('Why bother with that tonight?', 'Nerves. I clean brass when I can’t file copy. Everyone waits differently.', 'neutral'),
        c('What else did you polish?', 'I don’t itemise my hands for anyone. Leave it.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'From the flask cap to my thumb to the rag in my pocket. One clean little chain.', 'worried'),
        c('Could that smear be from the silver?', 'Same compound, near enough. Only where it’s been tells you which.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then drop it.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the polish from his flask to his thumb and rag.',
        bargain: c('Show me what’s in your kit and I leave the silver alone.', 'Fine. Cap to thumb to rag — my flask, my lighter, my chain. It doesn’t reach the plate.', 'thoughtful'),
        challenge: c('That polish matches the dining silver. You handled more than a flask.', 'Follow it from my flask, not the dining room. The chain starts in my pocket.', 'angry'),
      }),
    r('correspondent-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your coat?',
      'A source got frightened and held on a second too long before she talked. Her scent stayed. Her name won’t.', 'neutral',
      s(
        c('Who was the source?', 'Not a chance. But others saw us in the corridor. Ask them where I stood, not who I stood with.', 'thoughtful'),
        c('Do sources usually embrace you?', 'When they’re scared enough, yes. Fear makes people grab the nearest steady thing.', 'neutral'),
        c('That scent looks worn, not caught.', 'It’s hers, transferred. I don’t bottle gardenia. That part of the record stays shut.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'Lapel and collar, where she leaned in. Two guests passed and saw the whole thing.', 'thoughtful'),
        c('Couldn’t you just wear it yourself?', 'A war correspondent in gardenia. Ask anyone who’s shared a foxhole with me.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then let it evaporate.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the guests who passed in the corridor.',
        bargain: c('Confirm the spot — keep the source unnamed.', 'Deal. The passers-by will place me in that corridor; the scent came off her, and her name stays mine.', 'thoughtful'),
        challenge: c('That perfume puts you alone with someone. Who?', 'Close to a frightened source, in front of witnesses. Proximity isn’t a confession.', 'angry'),
      }),
    r('correspondent-powder', 'room', 'face-powder', 'How did ivory powder get onto your shoulder?',
      'Someone brushed past me in a doorway, hurrying. Left half her compact on my coat. Doorways are where people collide.', 'neutral',
      s(
        c('Who brushed past you?', 'A woman moving fast toward the hall. I felt the shove more than I saw the face.', 'thoughtful'),
        c('Isn’t that your own powder?', 'A field man in ivory powder? No. It came off someone in a hurry.', 'neutral'),
        c('That powder looks pressed on.', 'It was a collision, not a cosmetic. Read it how you want; I’m finished.', 'neutral'),
      ),
      s(
        c('Where did the powder land?', 'Shoulder and upper sleeve — right where a passing arm clips you.', 'worried'),
        c('Could several women wear that shade?', 'Sure. Only one wore enough to leave it on a stranger.', 'suspicious'),
        c('That’s enough about the powder.', 'Then cut it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder on his shoulder to the compact.',
        bargain: c('Name whose compact it was — I won’t print it.', 'Fair. Match the shade to her compact, not my face. I’ve never owned the stuff.', 'thoughtful'),
        challenge: c('That powder puts you near someone you won’t name. Who?', 'Near a shoulder in a doorway. Compare the shade; it’s hers, not mine.', 'angry'),
      }),
    r('correspondent-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine machine oil?',
      'Typewriter jammed mid-sentence. One drop on the carriage rail and it ran again. Can’t file with a stuck key.', 'neutral',
      s(
        c('When did the machine jam?', 'On the hour — I heard the clock while I was cursing the carriage. Easy time to remember.', 'thoughtful'),
        c('Why type during a storm like this?', 'Copy waits for no weather. The story was half-written and going cold.', 'neutral'),
        c('That’s more oil than a typewriter needs.', 'The bottle slipped. That’s the whole item. Move on.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'Fingers and cuff, right as the clock finished striking. The rail’s still slick.', 'worried'),
        c('Could that oil be from a lock or a blade?', 'Same light oil, different job. A dozen machines take it.', 'suspicious'),
        c('That’s enough about the oil.', 'Then spike it.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the oiled typewriter to the clock stroke.',
        bargain: c('Give me the time it jammed — I’ll leave the rest.', 'Fair trade. The rail was oiled on the clock’s stroke; oil and hour agree, and neither writes me guilty.', 'thoughtful'),
        challenge: c('You oiled something at a minute you’re hiding. What was it?', 'So I mend machines on the hour. Punctual maintenance isn’t a motive.', 'angry'),
      }),
    r('correspondent-wax', 'social', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'Sealed a dispatch the old way — hot wax over the flap so I’d know if anyone steamed it open. Habit from censored posts.', 'suspicious',
      s(
        c('What was in the dispatch?', 'Notes I don’t want read before I file them. The seal’s the point; the words are mine.', 'thoughtful'),
        c('Do reporters still seal with wax?', 'The ones who’ve been read over do. A wax seal can’t be faked without leaving a scar.', 'neutral'),
        c('That’s no press habit.', 'Believe it or don’t. The dispatch stays sealed and so does this.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'Snapped off the stick as I pressed it. Warm fleck, straight to the cuff. Careless.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'Looks close. Mine’s off a sealing stick, not a relic. Test it.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then leave it.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he used black wax — see if he corrects the colour.',
        bargain: c('Show me the seal and I leave the dispatch unread.', 'Fair — and it’s amber, not black. The colour’s wrong in your note; the seal itself is plain enough.', 'thoughtful'),
        challenge: c('You sealed something with that wax you won’t show me.', 'Amber, not black. If you’ve got the colour wrong, mind what else you’ve assumed.', 'angry'),
      }),
    r('correspondent-beat', 'connection', undefined, 'Why keep taking the hard jobs?',
      'If someone writes it down straight, the lie can’t stand. Naive, maybe. It’s kept me moving.', 'thoughtful',
      s(
        c('What story changed you?', 'One where I named a source to make the copy sing. They paid for my byline. I don’t do that anymore.', 'worried'),
        c('Do you ever want to stop?', 'Every filing day. Then something needs saying and my feet start walking.', 'neutral'),
        c('I have other questions.', 'Course you do. Everyone skips to the last line.', 'neutral'),
      ),
      s(
        c('What won’t you do now?', 'Burn a source. Once was enough.', 'worried'),
        c('What are you still after?', 'The version nobody wants written down. Usually the true one.', 'suspicious'),
        c('We’re done here.', 'Fine.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what are you protecting tonight?', 'Someone who trusted me after the last time I failed one. I don’t get to fail twice.', 'worried'),
        challenge: c('What are you hiding behind all that principle?', 'A source, not a crime. Guarding a name is my job.', 'angry'),
      }),
    r('correspondent-map', 'intel', undefined, 'What does this house tell you?',
      'Too many exits, too few honest ones. Half the alibis here are lies holding other lies up.', 'suspicious',
      s(
        c('Whose story sounds weakest?', 'The one that’s too smooth. Honest people fumble the order; liars have it memorised.', 'thoughtful'),
        c('Do you distrust everyone?', 'I check everyone. Trust is a luxury.', 'neutral'),
        c('I need a name.', 'Names come after facts.', 'neutral'),
      ),
      s(
        c('What about the exits?', 'Someone used a door twice they claim not to know. Movement leaves a trail.', 'thoughtful'),
        c('Could you be reading too much into it?', 'Always possible. This one’s not verified yet.', 'suspicious'),
        c('That’s enough.', 'Then we’re done.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who moved when they shouldn’t have?', 'One guest crossed after the clock struck, checked both corridors first. That’s not a stroll.', 'thoughtful'),
        challenge: c('Whose trail are you hiding?', 'None. I hide a source’s name, never a movement.', 'angry'),
      }),
  ],

  accountant: [
    r('accountant-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink across your fingers?',
      'An entry that wouldn’t balance. Posting ink makes an error look permanent — and mine flooded the margin when something startled me.', 'angry',
      s(
        c('What startled you into the mess?', 'Someone came in behind me; the nib split and the blue-black went everywhere.', 'suspicious'),
        c('What entry wouldn’t balance?', 'A figure that’s immaterial to you and very material to the estate.', 'neutral'),
        c('That was no slip of the pen. What were you really doing to the books?', 'Gladly. Account settled.', 'neutral'),
      ),
      s(
        c('What happened to the flooded margin?', 'I tore the soaked strip away. The altered zero underneath is still legible.', 'worried'),
        c('Couldn’t a reporter use the same ink?', 'Yes. Ink keeps no loyalty to a profession.', 'neutral'),
        c('The books can wait for morning.', 'Then this entry is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Compare the altered figure to the carbon copy.',
        bargain: c('Show me the entry — I’ll note you were under pressure.', 'That I can do. If the record shows the pressure I was under, I’ll sign the true figure.', 'worried'),
        challenge: c('You didn’t just spill that ink — something in that entry changed.', 'I posted a figure I was ordered to post. A forced hand isn’t a free one.', 'angry'),
      }),
    r('accountant-polish', 'room', 'metal-polish', 'Why is there metal polish filmed on your hands?',
      'Inventory. One candlestick had been moved and left badly tarnished, so I saw to it.', 'suspicious',
      s(
        c('How did you test the tarnish?', 'A dab of waxy polish on the base — it lifted the oxide at once.', 'thoughtful'),
        c('Was the candlestick valuable?', 'Everything carries a value. That answer carries none.', 'angry'),
        c('You didn’t polish silver just for inventory. What were you wiping?', 'With pleasure. Item struck from discussion.', 'neutral'),
      ),
      s(
        c('Where did you polish it, exactly?', 'Only where a hand would grip — the very places prints would sit.', 'worried'),
        c('Couldn’t that be motor-badge polish?', 'Substantially similar. The brand records might part them.', 'thoughtful'),
        c('That’s enough about the inventory.', 'Then strike it from your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he polished the base too — see if he corrects you.',
        bargain: c('Help me quietly and your name stays off it.', 'Then note this: I polished only the grip. Whoever moved it left the base untouched.', 'thoughtful'),
        challenge: c('You cleaned that candlestick to wipe a grip, not tarnish.', 'I cleaned where hands go. If that troubles you, it troubles whoever’s hands were there.', 'angry'),
      }),
    r('accountant-oil', 'social', 'blade-oil', 'Why are your fingers slick with fine machine oil?',
      'The adding machine’s carriage stuck mid-column. I dislike an interrupted total, so a drop of oil put it right.', 'angry',
      s(
        c('What freed the carriage?', 'A tiny drop of machine oil along the precision rail.', 'thoughtful'),
        c('Couldn’t you add by hand?', 'I could also walk home through the flood. Neither’s sensible.', 'neutral'),
        c('Open the machine. Show me what you oiled.', 'Transaction cancelled.', 'neutral'),
      ),
      s(
        c('Where did the oil travel after?', 'The key snapped back and flicked a clear drop onto my hand and the ledger clasp.', 'worried'),
        c('Wouldn’t instrument oil look the same?', 'Likely. Composition, not appearance, answers that.', 'thoughtful'),
        c('That total isn’t helping.', 'Then the account is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the oil from the machine rail to the ledger clasp.',
        bargain: c('Show me what you oiled and I leave the ledgers alone.', 'Gladly — rail, key, clasp. The same drop touched all three, and nothing else of mine.', 'thoughtful'),
        challenge: c('That oil touched more than an adding machine. What else?', 'The clasp, not the crime. A careless drop isn’t a damning one.', 'angry'),
      }),
    r('accountant-ledger', 'intel', undefined, 'Anything odd in the household accounts?',
      'A late charge posted twice, then one copy removed without proper initials.', 'suspicious',
      s(
        c('Who could have changed that entry?', 'Anyone with study access — but only a few knew which book to open.', 'thoughtful'),
        c('Couldn’t it be a simple mistake?', 'Mistakes add ink. They don’t remove pages.', 'angry'),
        c('Who pulled that page?', 'Very well. We’re done with this account.', 'neutral'),
      ),
      s(
        c('What narrows who had access?', 'The cabinet was locked before dinner and open after one guest left the study.', 'suspicious'),
        c('Are you accusing that guest?', 'I’m telling you who had access. Accusation is your job.', 'neutral'),
        c('That’s enough.', 'Fine.', 'neutral'),
      )),
    r('accountant-antiseptic', 'room', 'antiseptic', 'Why do your hands smell sharply of chemicals?',
      'Ink eradicator. When a figure’s posted wrong, you bleach it out. It reeks like a sickroom and costs a fortune.', 'neutral',
      s(
        c('What figure were you correcting?', 'A transposed sum. The fluid lifts the error so a clean one can replace it. Tedious, necessary.', 'thoughtful'),
        c('Why keep such a chemical on you?', 'An accountant without eradicator lives with his mistakes. I prefer to erase mine.', 'neutral'),
        c('That’s a doctor’s chemical.', 'It’s a clerk’s bleach. The smell’s shared; the purpose isn’t. We’re finished.', 'neutral'),
      ),
      s(
        c('Where did the eradicator touch you?', 'Fingertip and cuff, where the dropper slipped over the ledger. It dries loud, like carbolic — but it isn’t.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test the bottle. Mine dissolves ink, not infection. The two only agree on their stink.', 'suspicious'),
        c('That’s enough about the smell.', 'Then strike it from the account.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid dissolves ink, not wounds.',
        bargain: c('Let me test what’s on your cuff — quietly.', 'Reasonable. Test it — eradicator, not carbolic. A shared reek is a poor ledger entry.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve. Explain it.', 'Analyse it. Mine erases figures; his cleans wounds. You’ve posted the wrong column.', 'angry'),
      }),
    r('accountant-earth', 'timeline', 'fine-earth', 'What is that pale grit dusted over your ledger and cuffs?',
      'Pounce — fine sand a clerk shakes over wet ink so a figure dries without smearing. Older than blotting paper, and cleaner.', 'neutral',
      s(
        c('When did you pounce the page?', 'After each correction tonight. The grit tells you a fresh entry was just made and dried in a hurry.', 'thoughtful'),
        c('Why use sand instead of a blotter?', 'A blotter lifts ink and can be read in a mirror. Pounce leaves no ghost of the figure. Discretion.', 'neutral'),
        c('That doesn’t look like desk powder.', 'It’s from a pounce-pot on my desk. Your theory needs auditing.', 'neutral'),
      ),
      s(
        c('Where did the pounce end up?', 'My cuff, the page, the desk edge. Far finer than garden grit — a lens shows even grains.', 'thoughtful'),
        c('Could it match the conservatory soil?', 'Only to a careless eye. Side by side, pounce is uniform; soil isn’t.', 'suspicious'),
        c('The grit isn’t helping.', 'Then let it settle.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the dust on his cuff to the desk pot and the garden grit.',
        bargain: c('Show me the pot on your desk and I won’t chase the garden.', 'Efficient. Set my cuff beside the pot; the grain matches the pounce, not the flowerbeds.', 'thoughtful'),
        challenge: c('That grit came from the conservatory. Your desk story won’t hold.', 'Compare the grains properly. Pounce is milled; soil is chance. They won’t reconcile.', 'angry'),
      }),
    r('accountant-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My suit. Dark, serviceable, worn at the elbow from leaning over ledgers. It catches on rough cabinetry.', 'neutral',
      s(
        c('What did the suit catch on?', 'The cellar cabinet where the estate books are kept. A splintered edge took a thread as I reached in.', 'thoughtful'),
        c('Why wear a working suit to a dinner?', 'Because a man doesn’t audit from an armchair. The accounts don’t keep party hours.', 'neutral'),
        c('That thread came from somewhere you deny.', 'You haven’t examined my suit, so you can’t say. I decline the assumption.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after?', 'Cabinet edge to elbow to the ledger I carried out. A plain, itemised trail.', 'worried'),
        c('Could the thread be another dark coat?', 'It could. Coarse black wool is common enough to implicate half the staff.', 'suspicious'),
        c('The thread isn’t enough.', 'A rare balanced conclusion.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the cellar cabinet to his elbow.',
        bargain: c('Show me where the suit snagged and I keep it quiet.', 'Fair. Cabinet to elbow to ledger — the whole chain, and nothing on it but bookkeeping.', 'thoughtful'),
        challenge: c('That thread puts you in the cellar for more than books.', 'Where the accounts are kept. Reaching for a ledger isn’t a plot.', 'angry'),
      }),
    r('accountant-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your sleeve?',
      'A guest leaned over my shoulder to argue about a figure and left her scent on my coat. Interruptions have a smell now, apparently.', 'suspicious',
      s(
        c('Who leaned over you?', 'A woman disputing an entry in the study. Two others were there; ask them where I sat.', 'thoughtful'),
        c('Do people often read over your shoulder?', 'When money’s involved, constantly. Everyone’s an auditor of their own account.', 'neutral'),
        c('That scent looks worn, not caught.', 'It transferred from her sleeve to mine. I don’t wear gardenia. The matter closes.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'Shoulder and collar, where she bent over the page. The others saw the whole quarrel.', 'thoughtful'),
        c('Could you wear the scent yourself?', 'An estate accountant in perfume. Ask anyone who’s shared an office with me.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then write it off.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the guests who saw her lean over the books.',
        bargain: c('Name who leaned over your figures — off the record.', 'Acceptable. The witnesses place me at the desk; her scent came over my shoulder, not from any bottle of mine.', 'thoughtful'),
        challenge: c('That perfume puts you alone with someone. Who?', 'Close enough to be scolded over a figure, in front of witnesses. Standing near someone isn’t guilt.', 'angry'),
      }),
    r('accountant-powder', 'timeline', 'face-powder', 'How did ivory face powder get onto your ledger and cuff?',
      'The same woman who quarrelled over the figure set her compact on my desk. When she snatched it back, it burst.', 'surprised',
      s(
        c('What happened to the compact?', 'She slapped it down to make a point, then grabbed it too fast. The lid sprang and dusted the page and my cuff.', 'thoughtful'),
        c('Why should I believe it was hers?', 'Because I keep pounce and ink on that desk, not cosmetics. The powder’s plainly a lady’s.', 'neutral'),
        c('That powder looks deliberate.', 'You’re building a fiction from a smear. I won’t endorse it.', 'neutral'),
      ),
      s(
        c('Show me how the compact burst?', 'She sets it here, snatches there, the lid snaps back, and the puff scatters across the ledger. Simple mechanics.', 'worried'),
        c('Could the powder be your own?', 'I balance books, not my complexion. It isn’t mine.', 'suspicious'),
        c('That’s enough about the powder.', 'Then keep it out of your figures.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him show how the compact dusted the ledger.',
        bargain: c('Show me how the powder got on the page — discreetly.', 'Gladly. Set here, snatched there, the lid bursts — the powder writes the whole quarrel across my page.', 'thoughtful'),
        challenge: c('That powder didn’t land by accident. You pressed it into the page.', 'Then have me show you the spill. The sequence posts the blame to her clasp, not my hand.', 'angry'),
      }),
    r('accountant-wax', 'room', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'I sealed an envelope of accounts. Wax over the flap, dated and pressed, so any tampering shows. The stick cracked as I stamped it.', 'thoughtful',
      s(
        c('When did you seal the envelope?', 'On the hour — I stamp the seal and note the time together, so the record and the wax agree.', 'thoughtful'),
        c('Why seal accounts at a party?', 'Because figures don’t keep office hours, and neither, apparently, do the people they implicate.', 'suspicious'),
        c('That’s no ordinary account seal.', 'A sealed account stays sealed until it’s called for. So does this subject.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'It snapped off the stick as I pressed the stamp, right as the clock struck. A fleck caught my cuff.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'To an untrained eye. Mine came off a sealing stick and carries the hour I used it.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then let the seal keep its date.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the dated seal to the clock stroke.',
        bargain: c('Give me the time you stamped it — I leave the contents alone.', 'Fair. The seal carries the time I stamped it; wax and clock agree, and neither posts me guilty.', 'thoughtful'),
        challenge: c('That wax sealed something you won’t open for me.', 'So I date my seals precisely. A punctual stamp isn’t a confession.', 'angry'),
      }),
    r('accountant-note', 'suspicion', 'torn-note', 'What’s that scrap of cramped shorthand about?',
      'Running figures. A private tally in my own marks — sums, initials, a running balance. I tore the finished strip off out of habit.', 'thoughtful',
      s(
        c('What did the tally record?', 'A discrepancy I was chasing across two books. Numbers, not names — though the numbers point somewhere.', 'suspicious'),
        c('Can anyone else read your marks?', 'A trained bookkeeper, perhaps. To most it reads as a fence of scratches.', 'neutral'),
        c('That’s no ledger note. Hand it over.', 'A private tally stays private. The strip’s torn and the topic with it.', 'neutral'),
      ),
      s(
        c('What happened to the torn strip?', 'It left my folio when I stood; desk to floor, I didn’t track it. Careless of me.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious reader, any figure looks like a motive.', 'thoughtful'),
        c('I’ll read it myself.', 'Then mind you don’t misread a subtotal for a threat.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read the total back wrong and let him correct it.',
        bargain: c('Read me the tally — names stay out.', 'Very well — but your total’s off by a decimal. Correct it and you’ll see it’s only a balance.', 'thoughtful'),
        challenge: c('This note reads like a threat. Whose names are you hiding?', 'You’ve misread the figure. Move the decimal and your “threat” becomes a subtotal.', 'angry'),
      }),
    r('accountant-ledgerlife', 'connection', undefined, 'Why trust numbers more than people?',
      'People revise their stories. A column of figures doesn’t. I learned young which one to rely on.', 'thoughtful',
      s(
        c('What taught you that?', 'A family that promised much and delivered nothing. Numbers never promised. They just added up.', 'worried'),
        c('Do you care about the people behind the sums?', 'I feel plenty. I just won’t let that corrupt the arithmetic.', 'neutral'),
        c('I have other questions.', 'As you like.', 'neutral'),
      ),
      s(
        c('What would you fix if you could?', 'One account I signed that only balanced on paper. It’s cost me sleep, not money.', 'worried'),
        c('What will you never do again?', 'Sign my name to a figure I know is false. Once was a lesson.', 'suspicious'),
        c('We’re finished here.', 'Fine.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what’s weighing on you?', 'A set of books I can no longer pretend I didn’t read correctly. Some totals have to be paid.', 'worried'),
        challenge: c('What are you hiding behind all that precision?', 'A false entry, not a false alibi.', 'angry'),
      }),
    r('accountant-audit', 'intel', undefined, 'Looking at these guests — whose money doesn’t add up?',
      'Several. Money leaves a trail even when a person doesn’t. Three of them are running a deficit they won’t admit.', 'suspicious',
      s(
        c('Whose?', 'One who spends like a man expecting money he hasn’t earned yet. That’s dangerous.', 'thoughtful'),
        c('Do you judge everyone by their finances?', 'Only the ones whose finances explain their manners.', 'neutral'),
        c('I need a name.', 'Names follow figures. That’s the order.', 'neutral'),
      ),
      s(
        c('What have you actually seen?', 'A household charge posted, then quietly reversed. Someone tidied a record that didn’t need tidying.', 'suspicious'),
        c('Could that be a clerical error?', 'Errors add entries. They don’t remove them. This was deliberate.', 'angry'),
        c('That’s enough.', 'Fine.', 'neutral'),
      ),
      {
        bargain: c('Quietly — whose money should I follow?', 'Follow the one who reversed the charge. People only erase what they can’t afford to have read.', 'thoughtful'),
        challenge: c('Whose books are you protecting?', 'No one’s. I hold back conclusions, not entries. Draw your own.', 'angry'),
      }),
  ],
}
