// Pack A — Society Columnist, Retired Surgeon, Greenhouse Curator.
// Owned by the paper/payments & material-provenance writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_A: Record<Extract<ArchetypeId, 'columnist' | 'surgeon' | 'curator'>, AuthoredDialogueRoute[]> = {
  columnist: [
    r('columnist-ink', 'social', 'ink-fiber', 'Your hand’s smudged with ink. Where did that come from?',
      'My pen skidded during a row in the gallery and left ink all over my hand. I tore the ruined page clean out.', 'thoughtful',
      s(
        c('What was the row you were writing down?', 'Two guests going at each other. I got a name down before the ink ran everywhere.', 'suspicious'),
        c('Aren’t these just gossip notes?', 'Gossip pays my rent. But no, that isn’t tonight’s useful part.', 'angry'),
        c('Enough. What’s really in that notebook?', 'Now you’re asking properly. And now we’re done with my notebook.', 'neutral'),
      ),
      s(
        c('What happened to the page you tore out?', 'It was soaked with ink, so I ripped it away and tucked the scrap in my cuff to bin later.', 'worried'),
        c('Could someone else have used your pen?', 'Half the room borrows pens. Mine just leaks. That proves nothing.', 'suspicious'),
        c('Just tell me who was arguing.', 'No. Go find their names yourself — the page is mine.', 'angry'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the ink on her hand to the torn page.',
        bargain: c('Help me quietly and I keep your source out of it?', 'Kind, for a hired man. The ink’s mine, yes — but a leaky pen isn’t a crime.', 'thoughtful'),
        challenge: c('That ink matches the torn page. Explain yourself.', 'So compare them. A pen that leaks makes a mess, not a monster.', 'angry'),
      }),
    r('columnist-perfume', 'room', 'floral-perfume', 'Your perfume is awfully strong tonight. Why?',
      'The atomizer overfilled at the drawing-room mirror. The bulb jammed and soaked my glove instead of my wrist — gardenia beats damp wool, believe me.', 'neutral',
      s(
        c('How did it catch the glove and miss your skin?', 'I was holding it up to the light when the bulb stuck. The cloth took the whole spray.', 'thoughtful'),
        c('Is that scent in fashion this year?', 'Fashionable enough that three women will claim it tonight.', 'neutral'),
        c('That’s a lot of perfume for one evening. Why?', 'Nonsense. My perfume doesn’t need cross-examining.', 'neutral'),
      ),
      s(
        c('What did you do with the soaked glove?', 'Carried it around a while. It left gardenia in every room I passed.', 'worried'),
        c('Could the conservatory flowers explain it?', 'Only to someone who can’t tell real gardenia from a bottle.', 'angry'),
        c('That’s enough about the perfume.', 'Then stop sniffing around it.', 'suspicious'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her show how the atomizer soaked the glove.',
        bargain: c('Tell me who else used that atomizer — I won’t print it.', 'You do listen. Someone used it after me; that’s why the scent sits heavier on the glove than on me.', 'thoughtful'),
        challenge: c('You soaked that glove on purpose. Why leave a trail?', 'So a bulb sprayed cloth harder than wrist. That’s a spill, not a plot.', 'angry'),
      }),
    r('columnist-shorthand', 'timeline', 'torn-note', 'What was so important you kept writing through dinner?',
      'A conversation worth keeping. I got it down in shorthand, then tore the margin free when one name on it turned dangerous. A time, a lone letter, half a room — that’s all it holds.', 'thoughtful',
      s(
        c('Which conversation was worth tearing a page for?', 'A meeting two people wanted buried. I keep those; I don’t sell them.', 'suspicious'),
        c('Will you just tell me the gossip?', 'No. Gossip given away for free isn’t worth having.', 'angry'),
        c('Hand over the page.', 'I meant to. We’re done with that page.', 'neutral'),
      ),
      s(
        c('Where’s that torn margin now?', 'It fell out of my folio somewhere after I tore it free.', 'worried'),
        c('Can anyone else read your shorthand?', 'A good reporter could. Most people here struggle with the menu.', 'neutral'),
        c('I’ll just ask the two who argued.', 'Do. They lie better than my notes.', 'suspicious'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Check the time on her scrap against the gallery row.',
        bargain: c('Just give me the time — I’ll leave the rest alone.', 'All right. It reads 12:10, a lone C, and part of a room. A meeting, not an accusation.', 'thoughtful'),
        challenge: c('You’re hiding a name on that scrap. Whose?', 'You read torn paper boldly. A time and half a letter accuse no one.', 'angry'),
      }),
    r('columnist-society', 'intel', undefined, 'Who here looks the most nervous?',
      'Half of them, darling — but one keeps checking the doors between smiles.', 'suspicious',
      s(
        c('Who’s watching the doors?', 'It changes. The nervous looks started after a row near the hall.', 'thoughtful'),
        c('A row about what?', 'I only caught raised voices and a slammed door. Names I haven’t earned yet.', 'neutral'),
        c('Just tell me who looked afraid.', 'Gladly. And now we’re done with this one.', 'neutral'),
      ),
      s(
        c('What exactly did you hear?', 'Two voices, a slammed door, and someone who reached the corridor just as it ended.', 'thoughtful'),
        c('Why won’t you give me the names?', 'Half-heard scraps aren’t fit to print. I won’t hand you gossip I can’t stand behind.', 'suspicious'),
        c('That’s enough for now.', 'Then we’ve finished.', 'neutral'),
      ),
      {
        bargain: c('Off the record — who looked scared?', 'Off the record, then. A quiet man went pale when the hall door slammed.', 'thoughtful'),
        challenge: c('Names. Now.', 'Threaten me and you’ll get nothing. We’re finished.', 'angry'),
      }),
    r('columnist-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply of medicine?',
      'I cut my thumb on a broken glass and borrowed a little bottle from someone’s kit to clean it. It stung like a bad review.', 'worried',
      s(
        c('What was in the bottle you borrowed?', 'Clear stuff, very sharp — carbolic, at a guess. Not mine to keep.', 'thoughtful'),
        c('Is one small cut worth all this?', 'I write by hand. A ruined thumb is a professional disaster.', 'neutral'),
        c('That’s a strong smell for one small cut.', 'Believe what you like. The bottle wasn’t mine to keep. We’re done.', 'neutral'),
      ),
      s(
        c('Whose kit did the bottle come from?', 'Someone pressed it on me in the powder room and watched me dab it on.', 'worried'),
        c('Could that smell come from cleaning something else?', 'Half the house reeks of the sickroom tonight. Mine just closed a cut.', 'suspicious'),
        c('That’s enough about the smell.', 'Then stop breathing in my bad luck.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask whoever lent her the bottle.',
        bargain: c('Name who lent the bottle and I keep your cut out of it.', 'Generous. Ask them — they watched me clean the cut, and the smell explains itself.', 'thoughtful'),
        challenge: c('That smell isn’t from a cut. What did you really clean?', 'Ask. A borrowed bottle and a witness prove I bleed, not that I’m dangerous.', 'angry'),
      }),
    r('columnist-earth', 'timeline', 'fine-earth', 'How did pale grit get on your hem?',
      'I followed a promising row into the conservatory and knelt where a pot had been knocked over.', 'suspicious',
      s(
        c('Why did you kneel in the spilled grit?', 'There was a folded note under the bench. You pick those up gracefully or not at all.', 'thoughtful'),
        c('Do you always ruin a gown for gossip?', 'For the right gossip, I’d ruin a lot more.', 'neutral'),
        c('You didn’t kneel for nothing. What were you after?', 'My knees are my own business. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did that grit go after you stood up?', 'From my hem to my hand to the bench I steadied myself on. It gets everywhere.', 'worried'),
        c('Could the grit just be from the garden?', 'Too pale and too fine for garden soil. Someone tracked it in.', 'thoughtful'),
        c('The grit isn’t helping.', 'Then stop following my hemline.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the grit from the pot to her hem and the bench.',
        bargain: c('Walk me through the grit and I stay discreet.', 'Kind of you. Pot to hem, hem to hand, hand to bench. That’s the whole trip.', 'thoughtful'),
        challenge: c('That grit puts you at the spilled pot. What were you really after?', 'So it does. Kneeling by a spill makes me nosy, not dangerous.', 'angry'),
      }),
    r('columnist-wool', 'social', 'black-wool', 'Where did those black threads on your shoulders come from?',
      'A man draped his coat over me against the draught in the gallery. It shed all over me.', 'neutral',
      s(
        c('Which man lent you the coat?', 'One too dull to name and too warm to refuse. The wool caught on my clasp straight away.', 'thoughtful'),
        c('Do you make a habit of borrowing men’s coats?', 'Only when the house is cold and the company’s colder.', 'neutral'),
        c('That thread’s too coarse for a dinner jacket.', 'Explain it yourself. The coat went back to its owner.', 'neutral'),
      ),
      s(
        c('Where exactly did the wool snag?', 'On my shoulder clasp, the moment he settled it round me.', 'worried'),
        c('Could the thread be from your own wrap?', 'My wrap is silk. That coarse black strand is his, not mine.', 'suspicious'),
        c('The thread isn’t enough.', 'Then stop picking at it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Compare the coarse thread to her silk wrap.',
        bargain: c('Point me to the coat and I keep the man’s name out of it.', 'Decent of you. My wrap’s silk; that strand is coarse wool, so it came off his coat, not me.', 'thoughtful'),
        challenge: c('That thread is yours. Prove it isn’t.', 'Compare them. Silk against wool. Even you can tell those apart.', 'angry'),
      }),
    r('columnist-polish', 'room', 'metal-polish', 'Why is there a waxy metal smear on your fingers?',
      'I picked up a silver cigarette case to read the engraving. Someone had just polished it.', 'neutral',
      s(
        c('Whose case were you reading?', 'One with initials worth a paragraph, if they’re who I think.', 'suspicious'),
        c('Do you handle everything that isn’t yours?', 'Only the shiny, secretive things. They make the best columns.', 'neutral'),
        c('What else did you handle?', 'A lady doesn’t list her own fingerprints. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did the polish end up?', 'On my fingers and the clasp — right where a thumb opens it.', 'worried'),
        c('Could that smear be from your own compact?', 'My compact holds powder, not polish. That’s someone’s freshly shined silver.', 'thoughtful'),
        c('The smear isn’t enough.', 'Then let go of my hand.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she smudged the engraving — see if she corrects you.',
        bargain: c('Help me and the engraving stays out of print.', 'You bargain well. I only touched the lid to read it — whoever polished the base is your man.', 'thoughtful'),
        challenge: c('You wiped more than polish off that case. What else?', 'I read an engraving. Curiosity smudges silver; it isn’t a confession.', 'angry'),
      }),
    r('columnist-powder', 'social', 'face-powder', 'Why is there ivory powder on your sleeve?',
      'The powder room was a scrum of women all patting at once. A cloud like that doesn’t pick favourites.', 'neutral',
      s(
        c('Who were you crowded next to?', 'Two women sharing one mirror and, it seems, one compact’s worth of dust.', 'thoughtful'),
        c('Isn’t that just your own powder?', 'Mine stays on my face, not thrown across a sleeve like confetti.', 'neutral'),
        c('That powder looks pressed on, not dusted.', 'My makeup isn’t evidence. We’re finished.', 'neutral'),
      ),
      s(
        c('Where did the stray powder settle?', 'My sleeve and cuff, where another woman brushed me reaching for the glass.', 'worried'),
        c('Couldn’t every woman here wear that shade?', 'Several claim to. Only one wears it as heavily as this.', 'suspicious'),
        c('That’s enough about the powder.', 'Then stop dusting me for it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder on her sleeve to the compact.',
        bargain: c('Help me match the compact — I won’t name her in print.', 'Kind. The shade on my sleeve is heavier than mine — match it to her compact.', 'thoughtful'),
        challenge: c('That powder was pressed onto you, not brushed. Who did it?', 'Compare the shades. Mine’s lighter. Someone else’s cloud landed on me.', 'angry'),
      }),
    r('columnist-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with machine oil?',
      'My lighter jammed at the worst moment. A drop of oil and some bad language sorted it out.', 'suspicious',
      s(
        c('When did the lighter jam?', 'Just as the hall clock struck. I remember because I swore along with the chimes.', 'thoughtful'),
        c('Why not just ask someone for a light?', 'And owe them a favour? I’d rather oil a hinge than a debt.', 'neutral'),
        c('That’s more oil than one lighter needs.', 'My vices are my own. That’s closed.', 'neutral'),
      ),
      s(
        c('Where did the extra oil go?', 'Across my thumb and the lighter’s wheel, right as the chimes finished.', 'worried'),
        c('Could that oil be from a clock or a lock?', 'It could be from a dozen things. Mine was a stubborn flame.', 'suspicious'),
        c('That’s enough about the oil.', 'Then stop sniffing my fingers.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the oiled lighter to the clock stroke she named.',
        bargain: c('Give me the time the lighter jammed — I’ll leave the rest.', 'Fair. The lighter jammed on the clock’s stroke — the oil and the time agree, and neither accuses me.', 'thoughtful'),
        challenge: c('That’s more oil than a lighter needs. What else did you oil?', 'So test it. A stubborn flame makes a mess, not a plot.', 'angry'),
      }),
    r('columnist-wax', 'social', 'wax-resin', 'Why is there a brittle amber fleck on your cuff?',
      'I seal my riskier notes with wax. A slammed drawer knocked the stick before it cooled.', 'thoughtful',
      s(
        c('What did you need to seal?', 'A note too costly to leave loose in a folio.', 'suspicious'),
        c('Do columnists still bother with sealing wax?', 'The careful ones do. A licked flap protects nothing worth protecting.', 'neutral'),
        c('That’s not ordinary letter wax.', 'A sealed secret stays sealed. We’re finished with it.', 'neutral'),
      ),
      s(
        c('How did the wax get on your cuff?', 'It snapped as I pressed the seal — a warm fleck flicked onto my cuff before it set.', 'worried'),
        c('Could that fleck be restoration resin?', 'To a careless eye. Mine came off a sealing stick, not an antique.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then stop scraping at my cuff.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her seal another note and show how the fleck lands.',
        bargain: c('Show me how the wax broke and I leave the sealed note alone.', 'All right. I press here, the stick snaps there, the fleck lands on my cuff. No mystery.', 'thoughtful'),
        challenge: c('You sealed something you won’t admit. What was it?', 'So I seal my letters. Watch me do it — the wax breaks, nothing worse.', 'angry'),
      }),
    r('columnist-origins', 'connection', undefined, 'How did you end up writing about people for a living?',
      'I worked out young that the truth pays better than a diploma — and it’s better company too.', 'thoughtful',
      s(
        c('Who taught you to watch people?', 'My mother. She could read a room in a glance. I got the eye, not the mercy.', 'thoughtful'),
        c('Do you ever get tired of other people’s secrets?', 'The dull ones, yes. The dangerous ones keep me interested.', 'neutral'),
        c('I have other questions.', 'As you like. I didn’t expect you to care anyway.', 'neutral'),
      ),
      s(
        c('Who do you look out for?', 'The ones who can’t outrun a headline. I’ve spiked more stories than I’ve run.', 'worried'),
        c('What won’t you forgive?', 'Cruelty wearing a smile. I keep a whole drawer for it.', 'suspicious'),
        c('We’re done here.', 'Pity. I was almost being honest.', 'neutral'),
      ),
      {
        bargain: c('Honestly — why stay in this work?', 'Because the right sentence, printed at the right moment, can still protect someone. Foolish, I know.', 'thoughtful'),
        challenge: c('What are you hiding behind all that charm?', 'Everyone here is hiding something. Mine just has better grammar.', 'angry'),
      }),
    r('columnist-guests', 'intel', undefined, 'Which of these guests do you actually know?',
      'Half of them, professionally. The other half wish I didn’t — which tells you plenty.', 'suspicious',
      s(
        c('Who have you written about before?', 'A few. One never forgave me the paragraph; another begged me for the next one.', 'thoughtful'),
        c('Anyone make you uneasy?', 'Two go quiet when I walk in. Quiet is interesting.', 'neutral'),
        c('I need something I can use.', 'Then I’ll be poor company tonight.', 'neutral'),
      ),
      s(
        c('Who do you actually like here?', 'The singer. She lies beautifully, and never about anything that matters.', 'thoughtful'),
        c('Who do you avoid?', 'The ones who mistake my smile for stupidity. There are always a few.', 'suspicious'),
        c('That’s enough.', 'As you wish. Guest list’s closed.', 'neutral'),
      ),
      {
        bargain: c('Between us — who shouldn’t I turn my back on?', 'Watch the ones who are too composed. Grief has manners. Guilt has a practised face.', 'thoughtful'),
        challenge: c('Who are you protecting?', 'The powerless, not the guilty. Learn the difference before you accuse me.', 'angry'),
      }),
  ],

  surgeon: [
    r('surgeon-antiseptic', 'room', 'antiseptic', 'You keep washing your hands. What are you trying to get off them?',
      'Nothing sinister. The conservatory shears nicked my thumb and I dressed it with carbolic from my case. The smell lingers, I know.', 'neutral',
      s(
        c('Where did you dress it?', 'In the library. The stopper slipped and soaked my cuff before I wiped the bottle.', 'worried'),
        c('Was the cut serious?', 'Shallow. Your interest in it is misplaced.', 'angry'),
        c('You’ve scrubbed your hands raw. What else came off?', 'I don’t diagnose strangers, and I don’t explain myself to them either.', 'neutral'),
      ),
      s(
        c('Could that carbolic be plant treatment instead?', 'Possibly. I can’t tell the two apart from here.', 'suspicious'),
        c('Was one nicked thumb worth all that carbolic?', 'A surgeon dresses even a scratch properly. Habit outlives the practice.', 'neutral'),
        c('Then your hands tell me nothing.', 'On that, we agree.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the carbolic on his cuff to the library dressing.',
        bargain: c('Tell me what you cleaned — I won’t make a scene of it.', 'Decent of you. I bound the cut in the library; the carbolic caught my cuff there, no more.', 'thoughtful'),
        challenge: c('That smell is stronger than one dressed thumb. What else took carbolic?', 'A man who dresses a cut smells of carbolic. Nothing in that undoes me.', 'angry'),
      }),
    r('surgeon-oil', 'social', 'blade-oil', 'Why are your fingertips slick with fine oil?',
      'A hinge on my instrument case stuck when I opened it for a bandage. One drop of oil freed it, and it marked my hand.', 'suspicious',
      s(
        c('How did you free the hinge?', 'One drop of light oil and a probe. Forcing precision tools is barbaric.', 'thoughtful'),
        c('What’s inside the case?', 'Retired instruments. Their inventory is private and irrelevant.', 'angry'),
        c('Open the case. Show me what’s inside.', 'It’s already done. Let the subject drop with it.', 'neutral'),
      ),
      s(
        c('Did the oil stay on the hinge?', 'No. It ran onto my finger and marked my sleeve before I noticed.', 'worried'),
        c('Could it have come from a clock?', 'The weight of it might match. I serviced no clocks.', 'suspicious'),
        c('The mechanism doesn’t matter.', 'Then there’s no reason to continue.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the oil from his vial to the hinge and sleeve.',
        bargain: c('Account for the case and I’ll leave you alone.', 'Fair. The vial’s down one drop — my hand, my hinge, my sleeve.', 'thoughtful'),
        challenge: c('Only your hand touched that oil tonight. Prove it stayed on the case.', 'Confirm it. A man oiling his own case gets oil on himself. Hardly damning.', 'angry'),
      }),
    r('surgeon-wax', 'timeline', 'wax-resin', 'Where did that brittle amber fleck on your lapel come from?',
      'I sealed a private medical letter with an amber stick; a fleck of the wax caught my lapel as it cooled. Retirement doesn’t stop people asking for an opinion.', 'thoughtful',
      s(
        c('Who was the letter for?', 'Confidentiality survives a dinner invitation — the recipient keeps their own half of the seal.', 'angry'),
        c('Do people still seal letters by hand?', 'The careful ones do. A licked flap protects nothing worth protecting.', 'neutral'),
        c('Confidentiality won’t cover you tonight.', 'It will. That closes the matter.', 'neutral'),
      ),
      s(
        c('Could that amber be restoration resin instead?', 'It might look it. A test would settle that, not guesswork.', 'suspicious'),
        c('Did any more of that wax leave your desk?', 'Only the fleck on my lapel. I brushed at it and missed.', 'worried'),
        c('I don’t need an analysis.', 'A rare bit of restraint. We’re finished.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Compare the amber on his lapel to the other half of the seal.',
        bargain: c('Name who received the letter — I keep it off the record.', 'You keep confidences well. The amber on my lapel is twin to their half.', 'thoughtful'),
        challenge: c('You sealed something tonight you won’t name. What was it?', 'So I sealed a letter. Amber on a lapel proves a careful hand, not a crime.', 'angry'),
      }),
    r('surgeon-observation', 'intel', undefined, 'What have you noticed about the other guests?',
      'Restless hands. Shallow breathing. Nerves, mostly — but nerves have a lot of causes.', 'thoughtful',
      s(
        c('Who changed the most suddenly?', 'One guest went very still after voices rose in the corridor.', 'suspicious'),
        c('Nerves from what?', 'I can see the signs. I can’t name the cause from across a room.', 'angry'),
        c('Who do you suspect?', 'Then this conversation’s over.', 'neutral'),
      ),
      s(
        c('What did you see, exactly?', 'The row ended, a door opened, and that guest’s hands started shaking at once.', 'thoughtful'),
        c('Could it just have been the storm?', 'Possibly. But the shaking came first.', 'suspicious'),
        c('That’s enough.', 'Agreed. Any more would be guessing.', 'neutral'),
      ),
      {
        bargain: c('Between us — who worried you most?', 'The still one. Stillness after a scare is rarely calm.', 'thoughtful'),
        challenge: c('You saw who flinched. Name them.', 'I’ll give you what I saw, not a name. Draw your own conclusion.', 'angry'),
      }),
    r('surgeon-ink', 'timeline', 'ink-fiber', 'Why are your fingers marked with blue-black ink?',
      'I was writing up a private note. A steady hand still uses a fountain pen — the ink comes with it.', 'neutral',
      s(
        c('When exactly were you writing?', 'Just before the corridor got loud. I noted the hour, as I always do.', 'thoughtful'),
        c('What note needs ink at a party?', 'A clinical opinion. Retirement hasn’t stopped people asking.', 'neutral'),
        c('That’s a lot of ink for a short note.', 'The nib split. That’s all of it. I won’t say more.', 'angry'),
      ),
      s(
        c('Where else did that ink reach?', 'My finger and cuff both, the moment I set the pen down.', 'worried'),
        c('Could another writer share that ink?', 'Any number could. Ink isn’t a diagnosis.', 'suspicious'),
        c('That’s enough about the ink.', 'On that we agree.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin his dated page to when the corridor got loud.',
        bargain: c('Give me the hour — keep the patient unnamed.', 'Acceptable. The page carries the time I wrote it; ink and clock agree, and no name need leave my lips.', 'thoughtful'),
        challenge: c('You timed that page to cover a minute you can’t account for.', 'So I recorded something precisely. Precision is my habit, not my guilt.', 'angry'),
      }),
    r('surgeon-earth', 'room', 'fine-earth', 'What is that pale grit on your cuff?',
      'A dusting powder from my case — bismuth, near enough. It spilled when I steadied the lid.', 'neutral',
      s(
        c('What’s the powder for?', 'Settling a stomach. Harmless, chalk-fine, easily mistaken for ordinary dust.', 'thoughtful'),
        c('Why open a medical case at dinner?', 'Because someone always feels faint before the soup. I came prepared.', 'neutral'),
        c('That doesn’t look like powder from a case. Where did you kneel?', 'Your guess is ahead of your evidence. I won’t follow it.', 'angry'),
      ),
      s(
        c('Where did the spilled powder land?', 'My cuff and glove. Under a lens the grains are far too even for garden soil.', 'thoughtful'),
        c('Could it match the conservatory grit?', 'On the surface. A look under magnification would part them at once.', 'suspicious'),
        c('That’s enough about the powder.', 'Then let’s not magnify it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the grit on his cuff to the powder in his case.',
        bargain: c('Show me the case and I won’t chase the flowerbeds.', 'Reasonable. Set my cuff beside the tin — the grain matches the powder, not the flowerbeds.', 'thoughtful'),
        challenge: c('That grit came from the conservatory. You’re lying about the powder.', 'Then examine it properly. My powder is even; garden grit isn’t. The lens will correct you.', 'angry'),
      }),
    r('surgeon-wool', 'social', 'black-wool', 'Where did that black wool thread on your sleeve come from?',
      'My travelling coat. Good wool, old cut. It’s caught on furniture in better houses than this.', 'neutral',
      s(
        c('What did the coat catch on tonight?', 'A rough edge on the library shelving, about where a reaching arm would meet it.', 'thoughtful'),
        c('Why wear a heavy coat indoors?', 'The house is cold and my circulation isn’t what it was. Dull, but true.', 'neutral'),
        c('That thread’s coarser than your coat.', 'You haven’t examined my coat, so you can’t say that. I won’t indulge the guess.', 'angry'),
      ),
      s(
        c('Where did the thread pull loose from?', 'The left cuff, where the weave’s frayed for years. That’s the only weak point.', 'worried'),
        c('Could the thread be from another dark coat?', 'It could. Which is exactly why it names no one on its own.', 'suspicious'),
        c('The thread isn’t enough.', 'A rare and welcome conclusion.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Compare his frayed cuff to the coarser thread.',
        bargain: c('Let me check the coat against the thread — quietly.', 'Sensible. Lay the strand against my cuff; if the weave differs, it isn’t mine.', 'thoughtful'),
        challenge: c('That thread ties you to a place you deny. Own it.', 'Then compare the weaves first. A shared colour isn’t a shared coat.', 'angry'),
      }),
    r('surgeon-polish', 'room', 'metal-polish', 'Why is there polish residue on your fingertips?',
      'I picked up a steel instrument to check its edge and found someone had waxed it like a trophy.', 'suspicious',
      s(
        c('Which instrument had been polished?', 'A blade from the case by the sideboard. Freshly buffed — an amateur’s idea of care.', 'thoughtful'),
        c('Why handle blades at a dinner party?', 'Old reflex. I can’t leave a badly kept edge alone.', 'neutral'),
        c('What else did you handle?', 'I won’t inventory my own hands for you. That’s enough.', 'angry'),
      ),
      s(
        c('Where did the polish transfer?', 'From the handle to my thumb, then to the cloth I wiped it on. A clear little chain.', 'worried'),
        c('Could that residue be from the silver?', 'The compound’s much the same. Only its history tells you which object it’s from.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then we can set it down.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the polish from the blade to his thumb and cloth.',
        bargain: c('Tell me what you handled and I leave the silver alone.', 'Fair. Handle to thumb, thumb to cloth — one blade, one chain, nothing past it.', 'thoughtful'),
        challenge: c('That polish came off the dining silver. You handled more than a blade.', 'Then follow it from the blade I named, not the plate. It doesn’t reach where you hope.', 'angry'),
      }),
    r('surgeon-perfume', 'social', 'floral-perfume', 'Why does an expensive perfume cling to your lapel?',
      'A woman felt faint and I steadied her. Her scent stayed on my coat longer than my sympathy did.', 'neutral',
      s(
        c('Who was it you steadied?', 'A guest near the drawing room. I took her weight on my shoulder for a moment, no more.', 'thoughtful'),
        c('Do you make a habit of catching fainting women?', 'I make a habit of not letting people fall. Forty years is hard to unlearn.', 'neutral'),
        c('That scent looks worn, not brushed on.', 'Your nose is wrong, and I’m not obliged to correct it.', 'angry'),
      ),
      s(
        c('Where did her perfume settle?', 'My lapel and sleeve, where she leaned. She can tell you so herself.', 'thoughtful'),
        c('Couldn’t you just be wearing it yourself?', 'A retired surgeon in gardenia? Ask anyone who knows me.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then let it evaporate out of your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the woman he steadied.',
        bargain: c('Name her and I keep it quiet.', 'Decent. The woman I steadied will confirm it — her scent came to my lapel, not from me.', 'thoughtful'),
        challenge: c('That perfume puts you alone with someone. Who?', 'Close enough to keep her upright. Ask her. Proximity isn’t proof.', 'angry'),
      }),
    r('surgeon-powder', 'timeline', 'face-powder', 'How did ivory face powder get onto your cuff?',
      'When the woman I steadied swayed, her compact sprang open and dusted us both.', 'surprised',
      s(
        c('What happened to the compact?', 'It flew from her hand. I caught her first and the powder second, all over my cuff.', 'thoughtful'),
        c('Why should I believe it was hers?', 'Because I’ve no use for ivory powder, and she plainly did.', 'neutral'),
        c('That powder looks deliberate.', 'You’re building a scandal out of a spilled compact. I won’t help.', 'angry'),
      ),
      s(
        c('Show me how the compact sprang open?', 'She tipped, her hand opened, the lid snapped back, and the puff burst against my sleeve.', 'worried'),
        c('Could the powder be your own?', 'Only in a very different life. My case holds instruments, not cosmetics.', 'suspicious'),
        c('That’s enough about the powder.', 'Then we needn’t dust it further.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him show how the compact spilled.',
        bargain: c('Show me how it fell — I’ll leave her name out.', 'Gladly. She tips here, I catch there, the compact bursts — the powder does the rest.', 'thoughtful'),
        challenge: c('That powder didn’t get there by accident. You pressed it on.', 'Then let me show you how it spilled. The sequence blames the clasp, not the surgeon.', 'angry'),
      }),
    r('surgeon-note', 'suspicion', 'torn-note', 'You keep filling a page with cramped shorthand. What is it?',
      'Clinical notes. My own shorthand — times, symptoms, a dose. I tore off the used strip out of habit.', 'thoughtful',
      s(
        c('What did the notes record?', 'Observations on a guest who looked unwell. I write things down before memory tidies them.', 'suspicious'),
        c('Can anyone else read your shorthand?', 'A trained eye, maybe. To most people it’s a hedge of scratches.', 'neutral'),
        c('Those don’t look like medical notes. Hand them over.', 'A clinician’s notes are confidential. That’s the end of it.', 'angry'),
      ),
      s(
        c('What happened to the torn strip?', 'It left my folio when I stood. I assumed it went in a bin, but perhaps not.', 'worried'),
        c('Could the marks pass for something else?', 'To an untrained reader, they could read as anything.', 'thoughtful'),
        c('I’ll ask the guest directly.', 'Do. They remember the evening less clearly than my notes.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Misread one symbol and let him correct you.',
        bargain: c('Read me the note plainly — patient stays unnamed.', 'Very well — but you have the dose wrong. Read it correctly and it’s only a chart.', 'thoughtful'),
        challenge: c('This note reads like something you don’t want me to understand.', 'You’ve misread the symbol. Correct it and the “admission” becomes a dosage.', 'angry'),
      }),
    r('surgeon-retirement', 'connection', undefined, 'Why did you retire, if you still love the work?',
      'Because practising too long starts to cost more than it heals. I stopped before that happened.', 'thoughtful',
      s(
        c('What wore you down?', 'The hours, and one mistake I couldn’t undo. A tired hand is dangerous.', 'worried'),
        c('Do you miss it?', 'Every day. You don’t stop being a surgeon. You just stop being allowed.', 'neutral'),
        c('I have other questions.', 'Few people ask until they need one of us.', 'neutral'),
      ),
      s(
        c('What still matters to you?', 'An honest record. I’ve signed enough that weren’t.', 'worried'),
        c('What do you regret?', 'That I learned discretion before courage. The order matters.', 'thoughtful'),
        c('We’re finished here.', 'As you wish.', 'neutral'),
      ),
      {
        bargain: c('Between us — what keeps you awake?', 'A note I revised once, years ago. I’ve wanted to write one true line ever since.', 'worried'),
        challenge: c('What are you hiding?', 'A mistake, not a motive. Every man conceals something.', 'angry'),
      }),
    r('surgeon-diagnosis', 'social', undefined, 'Looking at this room — what do you see?',
      'Most of them are sicker with nerves than with anything I could treat. Fear has a look.', 'thoughtful',
      s(
        c('Who worries you most?', 'One guest holds a stillness that clearly costs effort. That kind of calm is worth watching.', 'suspicious'),
        c('Do you see everyone as a patient?', 'I notice things. Habit. I’m not treating anyone tonight.', 'neutral'),
        c('I need something useful, not impressions.', 'Then you’ll find me tedious. So be it.', 'neutral'),
      ),
      s(
        c('What would you trust as a real sign?', 'A tremor that comes before the thunder, not after. Nerves confess before the mouth does.', 'thoughtful'),
        c('Could you be reading too much into it?', 'Certainly. I said a look, not a diagnosis.', 'suspicious'),
        c('That’s enough.', 'Agreed. Any more would be guessing.', 'neutral'),
      ),
      {
        bargain: c('Plainly — who worries you, and why?', 'The one who doesn’t flinch. Practised calm is a warning of its own.', 'thoughtful'),
        challenge: c('What are you watching for?', 'The sign I missed once before. I won’t condemn anyone on a look.', 'angry'),
      }),
  ],

  curator: [
    r('curator-antiseptic', 'room', 'antiseptic', 'Why does a sharp, medicinal smell cling to your sleeve?',
      'An orchid was going rotten, so I treated it with a sulphur wash. The smell soaked into my sleeve.', 'worried',
      s(
        c('What did you treat it with?', 'A sharp sulphur wash, watered down. You can’t mask that smell.', 'thoughtful'),
        c('Was the orchid valuable?', 'It’s alive. That’s value enough. Price is a poor way to judge a plant.', 'neutral'),
        c('What did that wash really clean?', 'Nothing but a plant. This can rest there.', 'neutral'),
      ),
      s(
        c('How did the wash get on your cuff?', 'The nozzle spat back at me. A sharp streak dried across my sleeve.', 'worried'),
        c('Could it be ordinary perfume?', 'Only if someone has very strange taste in perfume.', 'surprised'),
        c('That’s enough about the wash.', 'Then let’s stop disturbing the roots.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the wash is plant sulphur, not medicine.',
        bargain: c('Tell me what you sprayed — I won’t call it medicine.', 'Gently, then. The sprayer kicked back; that sulphur streak is its doing, not medicine.', 'thoughtful'),
        challenge: c('That’s a doctor’s bottle on a gardener. What did you really treat?', 'You’ve done your reading. It’s plant wash, yes — because I treat plants.', 'angry'),
      }),
    r('curator-earth', 'timeline', 'fine-earth', 'Where did that pale grit on your hem come from?',
      'I repotted a cramped night jasmine — its roots couldn’t wait for dinner to end. The pale mix got all over my hem.', 'neutral',
      s(
        c('What soil did you use?', 'A pale mineral mix, finer than garden earth and dry as chalk.', 'thoughtful'),
        c('Why should I care about a flowerpot?', 'You needn’t. The jasmine doesn’t care about you either.', 'neutral'),
        c('Repotting at this hour? I don’t believe it.', 'Believe what you like. We’re done digging here.', 'neutral'),
      ),
      s(
        c('Where did the pale mix end up?', 'On my shoes and hem. I tracked the grit out before I noticed.', 'worried'),
        c('Could old plaster look the same?', 'To an impatient eye, yes. The texture would tell them apart.', 'thoughtful'),
        c('Enough gardening.', 'Then this bed’s exhausted.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Follow the grit from her hem toward the study vent.',
        bargain: c('Show me the trail and I won’t accuse the plants.', 'If you must. Someone swapped a root ball; the grit runs from the gallery rug toward the study vent.', 'thoughtful'),
        challenge: c('That grit didn’t come from a flowerpot alone. You’re covering a path.', 'So mineral mix travels on a hem. Follow it — it leads to a searched pot, not to me.', 'angry'),
      }),
    r('curator-note', 'social', 'torn-note', 'You keep jotting shorthand tonight. What are you recording?',
      'Growing records — dates, cuttings, a time or two — in my own shorthand. I tore the margin off one to label a pot.', 'thoughtful',
      s(
        c('What did you write down tonight?', 'A time, a slammed door, and some initials, in my own shorthand.', 'suspicious'),
        c('Do plants need initials?', 'People do. Plants are usually more honest.', 'neutral'),
        c('Those aren’t garden notes. Hand them over.', 'I will. We can prune this subject.', 'neutral'),
      ),
      s(
        c('What happened to that torn margin?', 'I tore it off to label a pot. Later the scrap was gone.', 'worried'),
        c('Could anyone read your shorthand?', 'Another grower might. To others it looks like nervous scratches.', 'thoughtful'),
        c('I’ll inspect the greenhouse myself.', 'Mind the roots. We’re done here.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Match the time in her shorthand to the cable copy.',
        bargain: c('Read me the shorthand — I leave the names alone.', 'Kindly meant. Read plainly, it gives a date, some initials, and 12:10.', 'thoughtful'),
        challenge: c('Those aren’t garden notes. You’re hiding a meeting.', 'So a growing record keeps a time. That’s a payment noted down, not a plot.', 'angry'),
      }),
    r('curator-growth', 'intel', undefined, 'Has anything in the house seemed out of place?',
      'A door that kept opening when the air was still. People used it more than they’ll admit.', 'thoughtful',
      s(
        c('Who used it?', 'Someone waited for the corridor to empty, then crossed without a glance at the plants.', 'suspicious'),
        c('Maybe they just don’t like plants?', 'Plenty don’t. That alone proves very little.', 'neutral'),
        c('Just tell me who it was.', 'As you wish. I don’t have a name for you.', 'neutral'),
      ),
      s(
        c('What did you notice about them?', 'A wet sole squeaked twice, right after the hall clock chimed.', 'thoughtful'),
        c('Could it have been a servant?', 'The stride was wrong. Though I can’t give you a name.', 'suspicious'),
        c('Nothing more on this.', 'Then we’re done.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who moved when they thought no one was looking?', 'One figure crossed on a wet sole just as the clock chimed. That’s all I can swear to.', 'thoughtful'),
        challenge: c('You saw them cross. Why won’t you name them?', 'I don’t have a name. The stride was wrong for a servant — that’s all.', 'angry'),
      }),
    r('curator-ink', 'timeline', 'ink-fiber', 'How did blue-black ink get on your fingers?',
      'I ink my plant labels by hand. A written label outlasts a pencil, and a garden forgets everything else.', 'neutral',
      s(
        c('When were you writing labels tonight?', 'Just before the corridor stirred. I mark the hour on each cutting, so the time’s in my hand too.', 'thoughtful'),
        c('Why label plants during a party?', 'A cutting doesn’t wait for the guests to leave.', 'neutral'),
        c('That’s more ink than labels need.', 'The nib caught the card and flooded. That’s all. I’ll say no more.', 'angry'),
      ),
      s(
        c('Where else did that ink reach?', 'Across my finger and the label’s edge, at the hour I’d just written.', 'worried'),
        c('Could another hand share that ink?', 'Many could. Ink keeps no loyalty to a gardener.', 'suspicious'),
        c('That’s enough about the ink.', 'Then let it dry, unremarked.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin her dated label to when the corridor stirred.',
        bargain: c('Give me the hour on the label — I won’t ask for more.', 'Gently, then. The label carries the time I wrote it; ink and hour agree, and neither condemns me.', 'thoughtful'),
        challenge: c('That’s too much ink for plant labels. What were you really dating?', 'So a cutting is time-stamped. Careful record-keeping isn’t a crime.', 'angry'),
      }),
    r('curator-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My work wrap — dark, coarse, older than most of my ferns. It snags on anything with a splinter.', 'neutral',
      s(
        c('What did the wrap catch on tonight?', 'An old cabinet by the passage. There’s a raised nail that took a thread as I passed.', 'thoughtful'),
        c('Why wear something so rough to a party?', 'Because a curator’s always a moment from lifting a heavy pot. Silk’s no help for that.', 'neutral'),
        c('That wrap took you somewhere you won’t name.', 'A snagged thread is a poor map. I won’t follow it for you.', 'angry'),
      ),
      s(
        c('Where did the thread travel after?', 'From the cabinet nail to my shoulder to the pot I carried past it. A plain trail.', 'worried'),
        c('Could the thread be someone else’s coat?', 'It could. Coarse black wool is common enough to accuse half the house.', 'suspicious'),
        c('The thread isn’t enough.', 'Then let it lie where it fell.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the cabinet nail to her wrap.',
        bargain: c('Show me where the wrap snagged and I keep it quiet.', 'If you must. Nail to shoulder to pot — the whole quiet trip, nothing sinister on it.', 'thoughtful'),
        challenge: c('That thread puts you at more than a cabinet. Where else did you go?', 'So my wrap brushed something in passing. That’s not a plot.', 'angry'),
      }),
    r('curator-polish', 'room', 'metal-polish', 'Why is there metal polish on your hands?',
      'I keep the brass sprayers and name-plates bright. Tarnish looks like neglect, and neglect frightens the patrons.', 'neutral',
      s(
        c('Which fittings did you polish?', 'The name-plates on the rarer plants, and the long brass sprayer I use each evening.', 'thoughtful'),
        c('Why does shiny brass matter to a plant?', 'It doesn’t. It matters to the patrons who pay for the plant.', 'neutral'),
        c('What else did you polish?', 'I don’t keep a record of my own fingerprints. That’s enough.', 'angry'),
      ),
      s(
        c('Where did the polish transfer?', 'Only to the parts a hand grips — the sprayer’s neck, the plate’s edge.', 'worried'),
        c('Could that smear come from the silver?', 'The compound’s much alike. Its history, not its shine, tells you which.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then we can let it dull.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the plate’s face — see if she corrects you.',
        bargain: c('Help me quietly and the patrons stay unnamed.', 'Kindly. I brightened only the grips, never the faces — whoever handled the silver was less careful than I.', 'thoughtful'),
        challenge: c('That polish came off the dining silver, not your brass.', 'I polished brass. If the smear troubles you, follow it to the sprayers, not the plate.', 'angry'),
      }),
    r('curator-perfume', 'social', 'floral-perfume', 'That heavy perfume — surely a gardener’s vanity?',
      'A gardener smells of soil and sap, not a bottled garden. That perfume is someone else’s, caught on me.', 'suspicious',
      s(
        c('Then how did it get on you?', 'A guest hugged me by the conservatory door and left half her bottle on my collar.', 'thoughtful'),
        c('You really wear no scent at all?', 'Only what the plants lend me. Bottled gardenia insults the real thing.', 'neutral'),
        c('That scent looks worn, not borrowed.', 'Insist all you like. I know my flowers from her chemist’s.', 'angry'),
      ),
      s(
        c('Where did the perfume transfer?', 'My collar and shoulder, where she leaned. My hands still smell of soil under it.', 'worried'),
        c('Could you have just brushed the blooms?', 'My blooms don’t smell that loud. This is a bottled scent, and not mine.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then stop breathing it in for me.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Compare the bottled scent to the soil on her hands.',
        bargain: c('Name who hugged you — I won’t print it.', 'Gently. Smell my hands — soil, not gardenia. The perfume came off her, not out of any bottle of mine.', 'thoughtful'),
        challenge: c('That perfume puts you somewhere you deny. Own the meeting.', 'Compare the scents. Mine’s green and low; hers is loud and bottled. Not the same.', 'angry'),
      }),
    r('curator-powder', 'room', 'face-powder', 'How did ivory powder get onto your shoulder?',
      'Someone squeezed past me in a narrow doorway and left half her compact on my sleeve.', 'neutral',
      s(
        c('Who pressed past you?', 'A woman in a hurry toward the hall. I felt her more than saw her face.', 'thoughtful'),
        c('Isn’t that just your own powder?', 'I dust plants with sulphur, not my face with ivory. It’s not mine.', 'neutral'),
        c('That powder looks applied, not brushed.', 'You can build a fantasy out of a smudge. I won’t help.', 'angry'),
      ),
      s(
        c('Where did the powder settle?', 'My shoulder and upper sleeve — right where a passing arm would meet me.', 'worried'),
        c('Could several women wear that shade?', 'Several might. Only one wears it thick enough to shed it on strangers.', 'suspicious'),
        c('That’s enough about the powder.', 'Then let it settle out of your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder on her shoulder to the compact.',
        bargain: c('Help me find whose compact it is — quietly.', 'Kindly meant. Match the shade to her compact, not my face — mine has never held ivory.', 'thoughtful'),
        challenge: c('That powder puts you near someone you won’t name. Who?', 'Near a careless shoulder in a doorway. Compare the shade; it’s hers, not mine.', 'angry'),
      }),
    r('curator-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'The conservatory vent seized in the damp. One drop of oil on the ratchet and it opened again.', 'neutral',
      s(
        c('What exactly did you oil?', 'The vent’s winding gear, and my shears while the tin was open. Both had gone stiff.', 'thoughtful'),
        c('Why fuss with a vent tonight?', 'A closed vent in this wet would rot my orchids by morning. It couldn’t wait.', 'neutral'),
        c('That oil went somewhere it shouldn’t.', 'You suppose a lot from a slick thumb. I won’t indulge it.', 'angry'),
      ),
      s(
        c('Where did the oil end up?', 'On my thumb and cuff when the ratchet sprang back. It marks whatever I touch after.', 'worried'),
        c('Could that oil come from a clock or a lock?', 'The same light oil serves them all. Only its use tells you which.', 'suspicious'),
        c('That’s enough about the oil.', 'Then let the matter rust.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her free the vent again and show where the oil went.',
        bargain: c('Show me how you freed the vent and I leave the oil alone.', 'Gladly. I turn the gear here, the ratchet springs there, and the oil catches my thumb. No mystery.', 'thoughtful'),
        challenge: c('That oil touched more than a garden vent. What else did you free?', 'A garden vent. Watch me free it; the oil lands exactly where honest work would put it.', 'angry'),
      }),
    r('curator-wax', 'social', 'wax-resin', 'What’s that amber fleck on your sleeve?',
      'Grafting wax. I seal the join where two cuttings meet, so the graft doesn’t weep sap and fail.', 'thoughtful',
      s(
        c('What were you grafting tonight?', 'A rose stock onto hardier root. The wax goes on warm, and warm wax flicks where it likes.', 'suspicious'),
        c('Is grafting really a job for a party?', 'A graft takes when it takes, not when the invitations allow.', 'neutral'),
        c('That’s sealing wax, not garden wax.', 'You mistake my work for a clerk’s. I won’t argue over a guess.', 'neutral'),
      ),
      s(
        c('How did the wax reach your sleeve?', 'It snapped off the warming stick and caught my cuff. The under-gardener held the graft; ask him.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'Similar to look at. A grower could tell my grafting wax from his relic-resin at a glance.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then let the graft heal in peace.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Check the wax against the graft she sealed.',
        bargain: c('Show me the graft and I won’t call it sealing wax.', 'Kindly. The sealed cutting’s right there; its wax is twin to my sleeve, and both are honest garden work.', 'thoughtful'),
        challenge: c('That wax came from something you sealed and hid. What?', 'To a rose graft. Look at the cutting — the wax matches it, not any hidden thing.', 'angry'),
      }),
    r('curator-calling', 'connection', undefined, 'Why spend a life among plants?',
      'They ask nothing and forgive everything, if you’re patient. People rarely manage either.', 'thoughtful',
      s(
        c('How did you get started?', 'One sick fern I refused to give up on. It lived. I’ve been outnumbered by green things ever since.', 'thoughtful'),
        c('Do you prefer plants to people?', 'Plants don’t lie about where they’ve been. That recommends them.', 'neutral'),
        c('I have other questions.', 'Few people ask until something they love starts to wilt.', 'neutral'),
      ),
      s(
        c('What would you protect?', 'The living collection. Some of those plants exist nowhere else.', 'worried'),
        c('What would you never do?', 'Trade a living thing for my own comfort. I’ve been asked. I refused.', 'suspicious'),
        c('We’re finished here.', 'Mind the roots on your way out.', 'neutral'),
      ),
      {
        bargain: c('What are you afraid of tonight?', 'That someone lets the rarest plants wither to make a point. That would be the real crime.', 'worried'),
        challenge: c('What is all this care covering?', 'Not guilt. Looking after plants isn’t the same as hiding something.', 'angry'),
      }),
    r('curator-company', 'intel', undefined, 'What do you make of the other guests?',
      'They crowd toward whoever shines brightest. It tells you who needs watching.', 'thoughtful',
      s(
        c('Who needs watching?', 'One turns away from attention instead of toward it. That usually means secrets.', 'suspicious'),
        c('Anyone in particular?', 'I notice habits. I don’t always get names.', 'neutral'),
        c('I need a name, not impressions.', 'Names I don’t have. Impressions I have plenty of.', 'neutral'),
      ),
      s(
        c('Who do you like here?', 'The surgeon. He listens slowly — to the quiet parts.', 'thoughtful'),
        c('Who bothers you?', 'The one who admired my rarest plant and only asked what it would fetch.', 'suspicious'),
        c('That’s enough.', 'Then we can stop.', 'neutral'),
      ),
      {
        bargain: c('Off the record — who worries you most?', 'The one who priced my orchid instead of seeing it. People who only see price frighten me.', 'thoughtful'),
        challenge: c('Who are you protecting?', 'Living things, not the guilty. Don’t confuse the two.', 'angry'),
      }),
  ],
}
