// Pack C — Jazz Vocalist, Antiquarian, Off-Duty Chauffeur, Debutante.
// Owned by the performance/false-presence & key/route writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_C: Record<Extract<ArchetypeId, 'vocalist' | 'antiquarian' | 'chauffeur' | 'debutante'>, AuthoredDialogueRoute[]> = {
  vocalist: [
    r('vocalist-perfume', 'room', 'floral-perfume', 'That floral scent follows you. What happened?',
      'My atomizer leaked before the first set. Gardenia got the encore instead of me.', 'neutral',
      s(
        c('What did the perfume soak?', 'My scarf, mostly. One little bulb and the whole thing was drenched.', 'thoughtful'),
        c('Is gardenia your signature?', 'A singer keeps some signatures off the program, sugar.', 'neutral'),
        c('That scent turned up where you say you were not. Explain.', 'All right. That song is over.', 'neutral'),
      ),
      s(
        c('Where did you carry that scarf?', 'That’s the thing — I didn’t. It sat in my case while the scent turned up in a hall I never walked.', 'worried'),
        c('Could the conservatory flowers smell the same?', 'Close enough to fool a hurried nose, not a patient one.', 'thoughtful'),
        c('The scent leads nowhere.', 'Then let it fade.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Set the scented corridor against the scarf that never left your case.',
        bargain: c('Someone used your perfume against you — help me show it.', 'Gladly. That trail is gardenia I never spilled, on a route I never took.', 'thoughtful'),
        challenge: c('Your perfume puts you in that corridor.', 'It puts my scent there. Scent travels where my feet never did.', 'angry'),
      }),
    r('vocalist-powder', 'social', 'face-powder', 'Were you fixing your face before the set?',
      'Just a touch-up. The lamps turn every tired face into a confession.', 'neutral',
      s(
        c('What went wrong with the touch-up?', 'My ivory compact cracked and jumped clean across the dressing table.', 'surprised'),
        c('Who were you hoping to impress?', 'The whole room. Never one soul when an audience is going spare.', 'neutral'),
        c('Your powder is on a door you never touched. How?', 'Then the mirror goes quiet.', 'neutral'),
      ),
      s(
        c('Where did that powder end up?', 'On my collar — and pressed into the dressing-room door where somebody leaned to listen.', 'worried'),
        c('Couldn’t anyone own stage powder?', 'Anybody can own it. Wearing it well is rarer.', 'neutral'),
        c('A cracked compact proves nothing.', 'Then close it, and this too.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the seam in the door’s powder to that card carrier’s edge.',
        bargain: c('Tell me who leaned on that door and I’ll keep you clear.', 'Whoever it was pressed a card carrier into my spilled powder. The seams match, detective.', 'thoughtful'),
        challenge: c('Your powder is on that door — you were listening.', 'My powder is. The print in it wears seams that aren’t mine.', 'suspicious'),
      }),
    r('vocalist-wax', 'timeline', 'wax-resin', 'What were you rubbing into your music case?',
      'A little amber grip wax. Keeps a stubborn clasp moving and my hands from slipping.', 'thoughtful',
      s(
        c('Why warm it by the lamp?', 'Cold wax skips. Warm it and it goes on smooth as a low note.', 'neutral'),
        c('Does wax improve the singing?', 'No, but this conversation may need several coats.', 'suspicious'),
        c('That wax took a key’s shape. Whose key?', 'Fine by me. End of the number.', 'neutral'),
      ),
      s(
        c('What pressed into the soft wax?', 'Something with teeth. A brass key left its shape when it sat against the cake.', 'worried'),
        c('Couldn’t that be sealing wax?', 'Same family of shine, different rhythm. A test would tell.', 'thoughtful'),
        c('The wax is no concern of mine.', 'Then let that note resolve.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Press the brass key back into the wax and show how it lay.',
        bargain: c('Show me how the key sat and I’ll keep it between us.', 'Watch — teeth-down, right here, while I wasn’t looking. The wax remembers what I didn’t see.', 'thoughtful'),
        challenge: c('You took an impression of that key.', 'The wax took it, not me. A cake can’t choose what leans on it.', 'angry'),
      }),
    r('vocalist-ear', 'intel', undefined, 'What did you hear while everyone else was talking?',
      'A door on the offbeat, hurried shoes, then somebody humming to cover their nerves.', 'thoughtful',
      s(
        c('What tune were they humming?', 'Mine, from earlier — but the last phrase came too fast.', 'suspicious'),
        c('Do nervous people always hum?', 'Some pray. Some lie. Some borrow a melody.', 'neutral'),
        c('No more riddles in rhythm. Who was humming?', 'The room goes quiet now.', 'neutral'),
      ),
      s(
        c('Where did the humming move?', 'From the side hall toward the stairs, stopping the moment another guest appeared.', 'thoughtful'),
        c('Could that have been you?', 'I know when I’m singing — even badly.', 'angry'),
        c('That’s not enough to follow.', 'Then the song ends there.', 'neutral'),
      )),
    r('vocalist-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink on your fingers?',
      'I mark my charts in ink before a set — a key change here, a rest there. Tonight the pen bled worse than a torch song.', 'neutral',
      s(
        c('When were you marking the music?', 'Right on the hour. I keep time even off the stage; the chime told me when I smudged it.', 'thoughtful'),
        c('Why ink and not pencil?', 'Pencil fades under the lamps. Ink stays, same as a good lyric.', 'neutral'),
        c('That is more ink than a chart needs. Explain.', 'The nib caught and wept. That’s the whole verse. We can let it end there.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'My fingers and the margin, right at the hour I’d just inked into the score.', 'worried'),
        c('Could another writer share that ink?', 'Half this house scribbles. Ink doesn’t sign a name.', 'suspicious'),
        c('The ink leads nowhere.', 'Then let that note fade.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the inked margin to the exact stroke of the clock she marked it by.',
        bargain: c('Give me the hour on the score and I keep the rest quiet?', 'Sweet of you. The margin’s inked to the chime I marked it by; the hour and the stain sing the same note, nothing more.', 'thoughtful'),
        challenge: c('You inked that score at a telling minute—well?', 'So I keep good time. A singer on the beat isn’t a singer with a motive.', 'angry'),
      }),
    r('vocalist-antiseptic', 'room', 'antiseptic', 'Why do your hands and scarf smell so medicinal?',
      'Throat wash and a menthol chest rub before a set. It bites like a sickroom, but it’s all a singer’s vanity.', 'neutral',
      s(
        c('What exactly do you use it for?', 'To open the pipes. Damp weather closes a voice like a bad review; the rub keeps the low notes low.', 'thoughtful'),
        c('Why should I believe it isn’t the real thing?', 'Because a surgeon’s carbolic and my gargle just happen to share a sting. Different bottles entirely.', 'neutral'),
        c('That smell is a doctor’s, not a singer’s. Explain.', 'Trust your nose over my dressing table if you like. That song’s over.', 'neutral'),
      ),
      s(
        c('Where did the wash touch you?', 'My scarf and fingers, where I dabbed the rub. It clings all night, same as the surgeon’s — but it isn’t.', 'worried'),
        c('Could it be surgical antiseptic instead?', 'Only to a nose in a rush. Taste it and it’s menthol and honey, not medicine.', 'suspicious'),
        c('The smell tells me nothing.', 'Then quit breathing in my vanity.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the scent on her scarf is throat wash, not surgical carbolic.',
        bargain: c('Let me test the bottle and I keep your dressing-room secrets?', 'Sweet. Test it — throat wash, menthol, honey. It shares a sting with carbolic and nothing else.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your scarf—well?', 'Sniff again, detective. Mine soothes a voice; his cleans a wound. A shared sting isn’t a shared crime.', 'angry'),
      }),
    r('vocalist-earth', 'social', 'fine-earth', 'What is that pale grit on your hands and hem?',
      'Grip chalk, near enough — I chalk my palms so the microphone stand doesn’t slide when the room gets warm.', 'neutral',
      s(
        c('What do you use the powder for?', 'A slick grip drops a mic mid-song. A little chalk and the stand stays put.', 'thoughtful'),
        c('Isn’t that just floor dust?', 'Finer than any floor. It comes from my own tin, not your garden.', 'neutral'),
        c('That grit came off a floor, not a tin. Explain.', 'You want to write me crawling in the dirt. That’s not my number.', 'neutral'),
      ),
      s(
        c('Where did the powder settle?', 'My palms, my hem, the stand I gripped. It’s paler and finer than soil, if you look close.', 'worried'),
        c('Could it match the conservatory grit?', 'At a glance, maybe. Side by side, my chalk’s milled even; garden grit never is.', 'suspicious'),
        c('The grit means nothing.', 'Then let the dust settle.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the chalk on her palm to her grip tin against the garden grit.',
        bargain: c('Show me your tin and I leave your act alone?', 'Kindly. Set my palm by the tin; the grip chalk matches, the garden grit doesn’t.', 'thoughtful'),
        challenge: c('That grit could put you in the conservatory—well?', 'Compare it right, detective. My chalk’s even; soil’s a mess. They won’t harmonize.', 'angry'),
      }),
    r('vocalist-wool', 'timeline', 'black-wool', 'Where did that frayed black wool come from?',
      'My performance stole. Black, warm, a little worn — it catches on anything with a rough edge, and this house is all rough edges.', 'neutral',
      s(
        c('What did the stole catch on?', 'A splintered doorframe by the side hall. The weave gave a thread the moment I brushed past.', 'thoughtful'),
        c('Why wear a heavy stole indoors?', 'A cold room steals a voice. I keep my shoulders warm the way a horn player keeps his reed.', 'neutral'),
        c('That thread is coarser than a stole. Explain.', 'You haven’t touched my stole, so you can’t say. I won’t sing to your guess.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after?', 'Doorframe to shoulder to the chair I draped it on. Follow it and it plays straight through.', 'worried'),
        c('Could the thread be another dark coat?', 'Could be. Coarse black wool’s common enough to accuse half the room.', 'suspicious'),
        c('The thread proves nothing.', 'Then let it hang loose.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the thread from the splintered doorframe to her stole and chair.',
        bargain: c('Walk me through the trail and I keep your name off it?', 'Sweet. Doorframe to shoulder to chair — the whole soft little journey, and nothing sharp on it.', 'thoughtful'),
        challenge: c('That thread puts you at the side hall—well?', 'So my stole brushed a door, detective. Passing through a hall isn’t a plot.', 'angry'),
      }),
    r('vocalist-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'I keep my microphone stand and my locket bright. A dull stand under the lights looks like a dull act.', 'thoughtful',
      s(
        c('What exactly did you polish?', 'The stand’s neck and my little silver locket. Both had gone grey in the damp.', 'suspicious'),
        c('Do you shine everything you own?', 'Only the things the audience sees. The rest can tarnish in peace.', 'neutral'),
        c('You buffed more than your own things. What else?', 'A lady doesn’t catalogue her fingerprints. That number’s finished.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the stand’s neck — right where a hand grips to sing.', 'worried'),
        c('Could that smear be from the silver?', 'Same waxy stuff, near enough. Only where it’s been tells you which.', 'thoughtful'),
        c('The polish is meaningless.', 'Then let it go dull.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the locket’s back too, and watch her correct you.',
        bargain: c('Help me quietly and I keep your name clean?', 'Obliging of you. I shined only the front and the neck; whoever handled the silver was messier than me.', 'thoughtful'),
        challenge: c('That polish matches the silver upstairs—well?', 'I shine a mic stand, detective. Follow the smear to my locket, not to a plate I never lifted.', 'angry'),
      }),
    r('vocalist-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'My music case latch seized in the damp. One drop of light oil and it snapped open again, smooth as a slow number.', 'neutral',
      s(
        c('What exactly did you oil?', 'The latch and the little hinge on the lid. Both had rusted stiff in this weather.', 'thoughtful'),
        c('Why fuss with a case tonight?', 'Because my charts live in it, and a stuck latch means no set. Couldn’t wait.', 'neutral'),
        c('That oil went where it shouldn’t. Explain.', 'You suppose a lot from a slick thumb, detective. I won’t sing to it.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the latch sprang back. It marks whatever I touch after.', 'worried'),
        c('Could that oil be from a lock or a blade?', 'Same light oil, different job. A dozen little machines take it.', 'suspicious'),
        c('The oil means nothing.', 'Then let it dry.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her work the seized latch again and show where the oil sprang.',
        bargain: c('Show me how the case opened and I keep it between us?', 'Watch — I oil the latch here, it springs there, the oil catches my thumb. No mystery, just a stuck lid.', 'thoughtful'),
        challenge: c('That oil ties you to a mechanism—well?', 'A music case, detective. Watch me free it; the oil lands right where an honest fix would put it.', 'angry'),
      }),
    r('vocalist-note', 'social', 'torn-note', 'What are those cramped little marks you keep tucking away?',
      'Song requests — a shorthand of my own for who wants what and when. I tear off each one as I sing it.', 'suspicious',
      s(
        c('What was on the marks tonight?', 'A title, a table, a time. Somebody wanted a particular tune at a particular hour.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'Another band singer, maybe. To the rest it’s just scratches and hope.', 'neutral'),
        c('Those aren’t song requests. Hand them over.', 'A singer’s notes stay in a singer’s glove. That verse is done.', 'neutral'),
      ),
      s(
        c('What became of the torn scrap?', 'It slipped from my glove between numbers. From my hand to the floor, I couldn’t swear where.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious eye, a shopping list looks like a scheme.', 'thoughtful'),
        c('I’ll ask whoever made the request.', 'Do. They’ll hum it back the same as my note.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm her request shorthand against the guest who asked for the tune.',
        bargain: c('Point me to who requested it and I keep your book quiet?', 'Sweet. The guest who asked will confirm the tune and the hour; my note just sings back what they wanted.', 'thoughtful'),
        challenge: c('That scrap ties you to something arranged—well?', 'To a song request, detective. Ask the guest; my marks and their wish are the same tune.', 'angry'),
      }),
    r('vocalist-road', 'connection', undefined, 'How does a voice like yours end up singing in a house like this?',
      'You follow the work, and the work follows the money — into ballrooms far colder than the clubs I came up in.', 'thoughtful',
      s(
        c('Where did you learn to sing?', 'Rooms full of smoke and second chances. I learned the blues before I learned my letters.', 'thoughtful'),
        c('Is it lonely, always singing for strangers?', 'A little. The room loves the song, never quite the girl singing it. You get used to the dark past the footlights.', 'neutral'),
        c('Spare me the ballad. I have questions.', 'Course you do. Nobody stays for the second verse.', 'neutral'),
      ),
      s(
        c('What would you protect, if it came to it?', 'A friend who kept me singing when a powerful man tried to take my voice for himself.', 'worried'),
        c('And what won’t you ever do?', 'Sing someone else’s lie because the pay is good. I did it once. Never again.', 'suspicious'),
        c('We’re done here.', 'Then the band packs up. Pity.', 'neutral'),
      ),
      {
        bargain: c('Off the record—what are you really carrying tonight?', 'Off the record: a tune that isn’t mine to lose, and a friend I won’t let anyone silence. That’s the whole song.', 'thoughtful'),
        challenge: c('All that smoke and rhythm—what are you hiding behind it?', 'A friend’s name, detective, not a crime. Keeping someone safe isn’t the same as being guilty.', 'angry'),
      }),
    r('vocalist-room', 'intel', undefined, 'You read a room for a living—what’s this one telling you?',
      'That everybody’s singing a little flat tonight. Fear pulls a voice off pitch, and I hear it all over this house.', 'suspicious',
      s(
        c('Whose tune is off the most?', 'One guest laughs a half-beat late — like they’re listening for something else under the music.', 'thoughtful'),
        c('Do you judge everyone by their pitch?', 'It’s truer than words. A voice can’t hide the way a face can.', 'neutral'),
        c('I want names, not music talk.', 'Then I’m poor company tonight.', 'neutral'),
      ),
      s(
        c('What would you actually trust?', 'The breath before a lie. It catches, every time, like a singer missing a cue.', 'thoughtful'),
        c('Could you be hearing it wrong?', 'Sure. I give you the sound, not the sentence.', 'suspicious'),
        c('That’s enough of the room.', 'Then the set’s over.', 'neutral'),
      ),
      {
        bargain: c('Quietly—who’s working hardest to sound calm?', 'Quietly: the one who’s too smooth. Real calm breathes; a fake one holds the note too long.', 'thoughtful'),
        challenge: c('You hear everything—so who are you covering for?', 'Nobody guilty, detective. I keep a friend’s name off my lips, not a culprit’s. Different tune entirely.', 'angry'),
      }),
  ],

  antiquarian: [
    r('antiquarian-earth', 'room', 'fine-earth', 'What object were you examining on the floor?',
      'A small reliquary with a regrettably modern hinge and an undocumented base.', 'thoughtful',
      s(
        c('What was packed beneath the base?', 'Pale pumice-like dust — display packing, finer than any garden soil.', 'thoughtful'),
        c('How old is the piece, truly?', 'Late medieval in aspiration. Rather more recent in execution.', 'angry'),
        c('Spare me the history. What was under that false base?', 'Object returned; inquiry concluded.', 'neutral'),
      ),
      s(
        c('Where did that dust travel?', 'From the false base to my fingertips, then along the hem to the west panel.', 'worried'),
        c('Couldn’t it just be plaster?', 'To an untrained eye. The grain deserves magnification.', 'suspicious'),
        c('The dust is not important.', 'Philistinism noted. We are done.', 'angry'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the packing dust from the false base to the west panel.',
        bargain: c('Tell me what the false base hid and I’ll protect the patron.', 'Hear it gently: the base opened to a compartment, and its dust marks the road I walked to the panel.', 'worried'),
        challenge: c('You opened that reliquary and went straight to the panel.', 'I followed dust, not a plan. Where packing falls is not where guilt lies.', 'angry'),
      }),
    r('antiquarian-polish', 'timeline', 'metal-polish', 'Why were you polishing the brass fittings?',
      'Authentication. Old brass takes wax differently from a modern plate.', 'neutral',
      s(
        c('What did you apply?', 'A pinhead of waxy polish to one inconspicuous corner.', 'thoughtful'),
        c('Did you have permission?', 'History outranks temporary ownership, within reason.', 'suspicious'),
        c('You handled far more than brass tonight. What else?', 'I have stopped discussing it, at least.', 'neutral'),
      ),
      s(
        c('How did the polish reach you?', 'My glove split at the thumb; the streak crossed skin, cuff, and a catalog card.', 'worried'),
        c('Couldn’t silver polish match it?', 'Closely. Composition would settle provenance.', 'thoughtful'),
        c('No more conservation lessons.', 'A merciful end to your education.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the streak on the card to the polish tin by the passage.',
        bargain: c('Let me match the tin and I’ll credit your care of the piece.', 'By all means — the streak on the card and the tin by the passage share a formula. Nothing to hide there.', 'thoughtful'),
        challenge: c('You polished a hinge that has no business being new.', 'A new hinge on an old saint, yes. Noticing a forgery is not committing a crime.', 'angry'),
      }),
    r('antiquarian-resin', 'social', 'wax-resin', 'What were you repairing before dinner?',
      'A lifted veneer on the reliquary. Neglect is history’s dullest vandal.', 'angry',
      s(
        c('What held the veneer down?', 'Warm amber restoration resin, sparingly applied beneath the edge.', 'thoughtful'),
        c('Was the reliquary valuable?', 'Culturally, immensely. Financially, ask the ledger worshipper.', 'neutral'),
        c('That resin is fresh, and not just on the relic. Where else?', 'The relic and this topic are now sealed.', 'neutral'),
      ),
      s(
        c('How fresh was the resin?', 'Mine went on tonight — still tacky. The flecks in the old passage are decades cured.', 'worried'),
        c('Couldn’t sealing wax look identical?', 'Superficially. Age would expose the impostor.', 'suspicious'),
        c('I need no provenance lecture.', 'Your loss. The lecture concludes.', 'angry'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Date your fresh resin against the old flecks in the passage.',
        bargain: c('Help me date it and I’ll keep the patron’s name sealed.', 'Then note the ages: my resin is hours old, the passage flecks are generations. Time itself parts them.', 'thoughtful'),
        challenge: c('Your fresh resin is all over that hidden passage.', 'My resin is on the relic, hours old. The passage wears an older hand than mine.', 'angry'),
      }),
    r('antiquarian-history', 'intel', undefined, 'Does this house’s history suggest anything useful?',
      'Its servants once used a narrow route between the public rooms, now hidden behind paneling.', 'thoughtful',
      s(
        c('Is that route still usable?', 'One panel bears fresh scratches around an otherwise ancient catch.', 'suspicious'),
        c('Is every scratch historically important?', 'No. Fresh damage on old wood earns attention.', 'angry'),
        c('Enough lecturing. Which panel was used tonight?', 'The tour and topic end here.', 'neutral'),
      ),
      s(
        c('Where is the scratched panel?', 'Beside the landscape whose frame hangs slightly crooked in the west passage.', 'thoughtful'),
        c('Couldn’t movers have marked it?', 'Possible, though no inventory records a recent move.', 'suspicious'),
        c('I’ll ignore the passage.', 'History is accustomed to being ignored.', 'neutral'),
      )),
    r('antiquarian-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink staining your fingers?',
      'I catalogue in ink, as one should. Pencil is for schoolboys and forgers; a proper provenance is written to last.', 'neutral',
      s(
        c('When were you cataloguing tonight?', 'On the hour precisely — I date every entry as I make it. The ink and the clock keep each other honest.', 'thoughtful'),
        c('Why catalogue during a party?', 'Because a piece unrecorded is a piece half-lost. History does not adjourn for canapés, detective.', 'neutral'),
        c('That is far more ink than an entry needs. Explain.', 'The nib split across the card and flooded. That is the whole of it; I shall say no more.', 'neutral'),
      ),
      s(
        c('Where did the flooded ink settle?', 'My forefinger and the card’s edge, at the very hour I had inscribed upon it.', 'worried'),
        c('Could another writer share that ink?', 'Any scribbler could. Ink respects no discipline, sadly, not even mine.', 'suspicious'),
        c('The ink leads nowhere.', 'Then let it dry, unremarked.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the dated catalog card to the exact stroke of the clock.',
        bargain: c('Give me the hour on the card and I keep the patron’s name out?', 'Civilised of you. The card is dated to the chime I wrote it by; ink and hour concur, and neither indicts me.', 'thoughtful'),
        challenge: c('You dated that card to a telling minute—well?', 'So I record time meticulously, detective. Scholarship is a habit, not a crime.', 'angry'),
      }),
    r('antiquarian-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply medicinal?',
      'Conservation solvent — a spirit I use to lift old varnish. It reeks of the sickroom, but it has never touched a patient, detective.', 'neutral',
      s(
        c('What were you treating with it?', 'A clouded lacquer on a reliquary hinge. The spirit cuts the grime where water would ruin the piece.', 'thoughtful'),
        c('Why should I believe it isn’t surgical?', 'Because a surgeon’s carbolic and a restorer’s spirit merely share a bite. Their purposes could not differ more.', 'neutral'),
        c('That is a doctor’s antiseptic. Explain.', 'It is a conservator’s spirit. Trust your nose if you must; the topic is closed.', 'neutral'),
      ),
      s(
        c('Where did the solvent touch you?', 'Fingertip and cuff, where the swab slipped. It lingers loud, the same as carbolic — yet it is not.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test the fluid. Mine dissolves varnish; his cleans wounds. Chemistry will part them at once.', 'suspicious'),
        c('The smell tells me nothing.', 'Then cease inhaling my materials.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the spirit on his cuff lifts varnish, not the surgeon’s carbolic.',
        bargain: c('Let me test the bottle and I keep the restoration quiet?', 'Reasonable. Test it — a restorer’s spirit, not carbolic. A shared reek is poor provenance, detective.', 'thoughtful'),
        challenge: c('That is a surgeon’s antiseptic on your sleeve—well?', 'Analyse it. Mine strips lacquer; his strips infection. You have mis-attributed the fluid entirely.', 'angry'),
      }),
    r('antiquarian-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My scholar’s coat — dark, decades old, and forever catching on the very cases I lean over to admire.', 'neutral',
      s(
        c('What did the coat catch on?', 'A display case in the west passage, at the corner where the glass meets a rough brass edge.', 'thoughtful'),
        c('Why wear such an old coat here?', 'Sentiment and warmth, detective. A garment, like an antique, improves with documented age.', 'neutral'),
        c('That thread is coarser than your coat. Explain.', 'You have not examined my coat, so the claim is baseless. I decline to argue provenance blind.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after?', 'From the case corner to my elbow to the ledge I steadied a piece upon. A traceable little chain.', 'worried'),
        c('Could the thread be another dark coat?', 'Entirely possible. Coarse black wool is a poor witness; it accuses everyone and no one.', 'suspicious'),
        c('The thread proves nothing.', 'A conclusion of rare good sense.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the thread from the display case to his elbow and the ledge.',
        bargain: c('Walk me through the trail and I keep the collection out of it?', 'Very well. Case to elbow to ledge — the whole scholarly little journey, and nothing untoward upon it.', 'thoughtful'),
        challenge: c('That thread puts you at the west passage case—well?', 'Admiring a case, detective. Leaning near glass is not a plot.', 'angry'),
      }),
    r('antiquarian-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your coat?',
      'A guest leaned close over my shoulder to admire a piece and left her scent behind. Enthusiasm has a fragrance, it seems.', 'neutral',
      s(
        c('Who leaned over you?', 'A woman charmed by the reliquary. She pressed close for a better look; two others watched her do it.', 'thoughtful'),
        c('Do admirers usually crowd you so?', 'When the object is fine enough, yes. People forget themselves before beautiful things.', 'neutral'),
        c('That scent is worn, not caught. Explain.', 'It transferred from her sleeve to mine. I do not wear gardenia; the matter is closed.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My shoulder and collar, where she bent to see. The onlookers will confirm the whole scene.', 'thoughtful'),
        c('Could you wear the scent yourself?', 'An antiquarian in gardenia? Ask anyone who has endured my lectures.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then let it evaporate from the record.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the admiring guest against the onlookers who watched.',
        bargain: c('Name who admired the piece and I keep it discreet?', 'Decent. The onlookers place her at my shoulder; her scent came from her sleeve, not from any bottle of mine.', 'thoughtful'),
        challenge: c('That perfume puts you close to someone—well?', 'Close to an admirer, detective, before witnesses. Proximity authenticates nothing against me.', 'angry'),
      }),
    r('antiquarian-powder', 'room', 'face-powder', 'How did ivory powder come to be on your sleeve?',
      'A lady brushed past me at the display and left half her compact on my coat. The passage is narrow; collisions are inevitable.', 'neutral',
      s(
        c('Who brushed past you?', 'A woman hurrying from the gallery. I registered the brush of her more than the face, I confess.', 'thoughtful'),
        c('Is that not simply your own powder?', 'I handle whiting for restoration, detective, not ivory for my complexion. It is a lady’s.', 'neutral'),
        c('That powder was applied, not brushed. Explain.', 'You reconstruct a fiction from a smudge. I shall not authenticate it.', 'neutral'),
      ),
      s(
        c('Where did the powder settle?', 'My upper sleeve and shoulder — precisely where a passing arm would meet me.', 'worried'),
        c('Could several women wear that shade?', 'Several might. Only one wears it heavily enough to bequeath it to strangers.', 'suspicious'),
        c('The powder means nothing.', 'Then let it settle out of the catalogue.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the shade on his sleeve to the compact that shed it.',
        bargain: c('Help me find whose compact it is and I keep you clear?', 'Obliging. Match the shade to her compact, not my sleeve; my whiting is chalk-white, not ivory.', 'thoughtful'),
        challenge: c('That powder puts you near someone—well?', 'Near a careless shoulder, detective. Compare the shade; it is hers, and demonstrably not mine.', 'angry'),
      }),
    r('antiquarian-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'I eased a seized antique lock to examine its wards. One drop of light oil and a mechanism two centuries old turned sweetly again.', 'neutral',
      s(
        c('What lock were you examining?', 'A period escutcheon on a cabinet. The wards tell you the maker; a frozen lock tells you nothing.', 'thoughtful'),
        c('Why oil someone else’s cabinet?', 'To read it, detective. A conservator cannot resist a mechanism begging to be understood.', 'neutral'),
        c('That oil went where it shouldn’t. Explain.', 'You infer a great deal from a slick thumb. I decline to indulge it.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the bolt sprang. It marks whatever I handle thereafter.', 'worried'),
        c('Could that oil be from a blade or a clock?', 'The same light oil serves them all. Only its use distinguishes them.', 'suspicious'),
        c('The oil is irrelevant.', 'Then permit the matter to rust.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him work the seized lock again and show where the oil sprang.',
        bargain: c('Show me how the lock freed and I keep the cabinet out of it?', 'Gladly. I oil the ward here, the bolt springs there, and the oil catches my thumb — a scholar’s fix, nothing worse.', 'thoughtful'),
        challenge: c('That oil ties you to a mechanism—well?', 'An antique lock, detective. Watch me ease it; the oil falls exactly where honest curiosity would leave it.', 'angry'),
      }),
    r('antiquarian-note', 'social', 'torn-note', 'What are those cramped marks you keep noting down?',
      'Catalogue shorthand — accession codes, condition notes, a date of examination. I tear off each completed slip as I file it.', 'suspicious',
      s(
        c('What did the notes record?', 'The condition of a piece and the hour I examined it. Dull to you; indispensable to posterity.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'A fellow curator, perhaps. To the layman it is a thicket of abbreviations.', 'neutral'),
        c('Those are no catalogue notes. Hand them over.', 'A scholar’s notes remain a scholar’s. The slip is torn and the topic with it.', 'neutral'),
      ),
      s(
        c('What became of the torn slip?', 'It parted from my folio as I rose; from desk to floor, I did not follow it. Careless of me.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious reader, an accession code resembles a conspiracy.', 'thoughtful'),
        c('I will read it myself.', 'Then mind you do not mistake a condition note for a confession.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read one code back wrong, and let him correct the accession number.',
        bargain: c('Read me the slip plainly and the patron stays unnamed?', 'Very well — but your accession number is transposed. Correct it and you will see it is merely a condition report.', 'thoughtful'),
        challenge: c('This note reads like a plot—well?', 'You have misread the code, detective. Restore the digits and your “plot” becomes a catalogue entry.', 'angry'),
      }),
    r('antiquarian-vocation', 'connection', undefined, 'What draws a person to give their life to old objects?',
      'They keep their promises, detective. A genuine piece is honest about its age; only people and their forgeries lie.', 'thoughtful',
      s(
        c('How did you begin in the trade?', 'A cracked Roman lamp my grandfather refused to discard. I have been mending the past’s neglect ever since.', 'thoughtful'),
        c('Do you truly prefer objects to people?', 'Objects do not disappoint you twice. That is a great deal to recommend them.', 'neutral'),
        c('Spare me the lecture. I have questions.', 'Few request the provenance. Very well; ask your questions.', 'neutral'),
      ),
      s(
        c('What would you set right if you could?', 'One authentication I signed that I have since come to doubt. A false attribution weighs on a scholar’s conscience.', 'worried'),
        c('And what would you never do?', 'Knowingly certify a forgery for gain. To do so twice would unmake everything I am.', 'suspicious'),
        c('We are finished here.', 'Then the gallery closes. A pity; I was warming to it.', 'neutral'),
      ),
      {
        bargain: c('Off the record—what troubles you tonight?', 'Off the record: a piece I called genuine that I now suspect is not. Correcting the record may cost me a great deal.', 'worried'),
        challenge: c('All this erudition—what is it concealing?', 'A mistaken attribution, detective, not a motive. A scholar’s error is not a scholar’s crime.', 'angry'),
      }),
    r('antiquarian-guests', 'intel', undefined, 'What do you make of the company here tonight?',
      'A mixed provenance, detective. A few are exactly what their labels claim; several are clever fakes in good frames.', 'suspicious',
      s(
        c('Who strikes you as a fake?', 'One guest handles everything — and everyone — a shade too casually. Careless hands betray a careless conscience.', 'thoughtful'),
        c('Do you appraise people like objects?', 'It is a reliable method. Wear patterns do not flatter, whether on silver or on a smile.', 'neutral'),
        c('I want names, not appraisals.', 'Names I withhold; impressions I have catalogued in abundance.', 'neutral'),
      ),
      s(
        c('Whose company do you value?', 'The curator. She reveres living things as I revere made ones. We understand custodianship alike.', 'thoughtful'),
        c('And whose unsettles you?', 'The one who asked the reliquary’s price before its history. Value without reverence is a kind of vandalism.', 'suspicious'),
        c('That is enough appraisal.', 'Then we may return the topic to its case.', 'neutral'),
      ),
      {
        bargain: c('Off the record—who here worries you most?', 'Off the record: the one who priced a sacred object like a paperweight. People who see only cost frighten me.', 'thoughtful'),
        challenge: c('You judge them all—so whom are you protecting?', 'A coerced patron, detective, not a culprit. Shielding the pressured is not the same as shielding the guilty.', 'angry'),
      }),
  ],

  chauffeur: [
    r('chauffeur-solvent', 'room', 'antiseptic', 'What’s that sharp smell on your hands?',
      'Motor solvent. Battery terminal furred up before the rain came in.', 'neutral',
      s(
        c('What sort of solvent?', 'Clear stuff from the motor kit. Bites the nose. Not the doctor’s sort.', 'thoughtful'),
        c('Will the car start now?', 'Road’s flooded. Starting isn’t leaving.', 'neutral'),
        c('That smell is not just the garage. What did it really touch?', 'Fine. Garage is closed.', 'neutral'),
      ),
      s(
        c('How did it reach your cuff?', 'Bottle kicked when I set it down. Splashed me before I capped it.', 'worried'),
        c('Couldn’t that be medical antiseptic?', 'Smells close. I’m no chemist, but mine came from a motor tin.', 'suspicious'),
        c('The solvent tells me nothing.', 'Then we’re done with it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match your cuff to the motor tin, not the doctor’s shelf.',
        bargain: c('Point me to the tin and I’ll write it up straight.', 'Right there on the bench, sir. Same label as my cuff. Nothing off the doctor’s shelf about it.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve.', 'It’s battery solvent, sir. You smell a workingman and write “guilt”. Match the tin first.', 'angry'),
      }),
    r('chauffeur-wool', 'timeline', 'black-wool', 'Is that your driving uniform coat?',
      'Aye. Black wool. Warm, tough, mostly.', 'neutral',
      s(
        c('Why only mostly tough?', 'Sleeve caught a seat spring. Seam’s been shedding at the wrist since.', 'worried'),
        c('Why dress for work off duty?', 'Car trouble doesn’t check the invitation.', 'neutral'),
        c('Mostly. Where did the rest of it tear off to?', 'Done.', 'neutral'),
      ),
      s(
        c('Where did the passage thread tear?', 'That’s the catch, sir — that one tore at the elbow, and it’s a coarser weave than mine.', 'thoughtful'),
        c('Couldn’t it be another black coat?', 'That’s my point. Two coats, two weaves.', 'suspicious'),
        c('The thread’s useless.', 'Then stop pulling it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show your wrist tear cannot be the coarse elbow thread on the latch.',
        bargain: c('Help me and I’ll clear your coat myself.', 'Appreciated, sir. Mine frayed at the wrist on a seat spring; that passage thread’s elbow-high and coarser. Can’t be the same coat.', 'thoughtful'),
        challenge: c('Your coat left that thread in the passage.', 'Can’t have, sir. Mine tore at the wrist; that one’s at the elbow, coarser weave. Look before you decide.', 'angry'),
      }),
    r('chauffeur-polish', 'social', 'metal-polish', 'Besides your cap, what have you polished?',
      'Bentley’s radiator badge. Butler wanted it bright before the weather turned.', 'neutral',
      s(
        c('What polish did you use?', 'Tin by the garage door. Waxy stuff, smells of pennies and paraffin.', 'thoughtful'),
        c('Why polish a car in this storm?', 'Job came before the rain. Weather doesn’t cancel chores.', 'neutral'),
        c('A badge, in this storm? What else did that polish touch?', 'Ask the glasses. I’m done with the motor.', 'neutral'),
      ),
      s(
        c('How did the polish get on you?', 'No rag. Wiped two fingers in my glove; the split smeared the garage latch and my cuff.', 'worried'),
        c('Couldn’t that smear come from silver?', 'Could. Same sort of compound. I didn’t touch silver.', 'suspicious'),
        c('The badge is irrelevant.', 'Then nothing more to say on it.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the polish from the garage tin through your glove to the latch.',
        bargain: c('Show me the garage and I’ll log your route straight.', 'This way, sir — tin, glove, latch, cuff. One trail, all garage. Nothing near the silver.', 'thoughtful'),
        challenge: c('That polish matches the silver upstairs.', 'Same compound, different job, sir. Follow it from my tin, not from the dining room.', 'angry'),
      }),
    r('chauffeur-traffic', 'intel', undefined, 'Who’s been moving through the halls?',
      'Plenty of trips. One guest used the service door twice and pretended not to know it existed.', 'suspicious',
      s(
        c('How do you know it was the same one?', 'Same step. Heel drags on the left when they hurry.', 'thoughtful'),
        c('You know people by footsteps?', 'Drive long enough, you hear bad bearings.', 'neutral'),
        c('You saw the face. Stop protecting them and say it.', 'All right. Road closed.', 'neutral'),
      ),
      s(
        c('When was the second trip?', 'After the hall clock chimed, before the next thunderclap.', 'thoughtful'),
        c('Couldn’t a servant walk that way?', 'Could. Didn’t look like staff shoes.', 'suspicious'),
        c('That timing’s too vague.', 'Then we’re done.', 'neutral'),
      )),
    r('chauffeur-ink', 'timeline', 'ink-fiber', 'Why’s there blue-black ink on your fingers?',
      'Route log, sir. I write down every run — where, when, who. Pen leaked when I marked the last one.', 'neutral',
      s(
        c('When did you make the last entry?', 'On the hour, sir. Clock chimed while I was writing. I log the time to the minute; always have.', 'thoughtful'),
        c('Why keep a log off duty?', 'Habit. A driver with no record is a driver who takes the blame for other men’s trips.', 'neutral'),
        c('That’s more ink than a log needs. Explain.', 'Nib split. That’s the whole of it. Leave it there.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'Fingers and the page edge, right at the hour I’d just logged. Still wet, sir.', 'worried'),
        c('Couldn’t another writer use that ink?', 'Plenty could. Ink don’t care whose hand holds the pen.', 'suspicious'),
        c('The ink leads nowhere.', 'Then we’re done with it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the logbook entry to the exact stroke of the clock he wrote it by.',
        bargain: c('Give me the hour in the log and I keep your fares private?', 'Fair, sir. The entry’s dated to the chime I wrote by; ink and hour say the same thing, nothing more.', 'thoughtful'),
        challenge: c('You logged that at a telling minute—well?', 'So I keep good time, sir. A careful log’s not a guilty one.', 'angry'),
      }),
    r('chauffeur-earth', 'room', 'fine-earth', 'Where’d that pale grit on your knees come from?',
      'Under the motor, sir. Something rattled on the axle before the rain, so I went down on the drive to look.', 'neutral',
      s(
        c('What were you checking under there?', 'A loose plate throwing grit. Fine pale stuff off the gravel, drier than garden dirt.', 'thoughtful'),
        c('Why crawl under a car in a storm?', 'A rattle at speed’s a broken axle waiting to happen, sir. Rain or not, you check it.', 'neutral'),
        c('That grit’s from indoors, not a drive. Explain.', 'Think what you like. I went under the car, I came out gritty. That’s the run.', 'neutral'),
      ),
      s(
        c('Where did the grit end up?', 'Knees, cuffs, the tin I set down. Paler and finer than soil, if you look close, sir.', 'worried'),
        c('Couldn’t it match the conservatory dust?', 'Close, not the same. Drive grit’s got sand in it; that garden stuff don’t.', 'suspicious'),
        c('The grit means nothing.', 'Then leave it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the grit on his knees to the drive gravel against the garden dust.',
        bargain: c('Show me where you went under and I log it straight?', 'This way, sir. Set my knee-grit by the drive gravel — matches. The garden stuff’s a different grain.', 'thoughtful'),
        challenge: c('That grit could put you in the conservatory—well?', 'Compare it proper, sir. Drive grit’s coarse and sandy; garden dust ain’t. They won’t match.', 'angry'),
      }),
    r('chauffeur-perfume', 'social', 'floral-perfume', 'Why’s a woman’s perfume on your uniform?',
      'Off the last fare, sir. A lady rode in the back this evening; her scent soaked the seat and my collar with it.', 'neutral',
      s(
        c('Who was the passenger?', 'A guest I ran up from the station before the roads flooded. Perfume like a greenhouse, sir. It lingers.', 'thoughtful'),
        c('Do you always smell of your fares?', 'When they wear half a bottle, aye. A back seat holds a scent longer than a memory.', 'neutral'),
        c('That scent’s worn, not caught. Explain.', 'A driver in gardenia? No, sir. It came off the seat, off her, not off me.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My collar and shoulder, where I leaned back over the seat to shut her door.', 'worried'),
        c('Couldn’t you wear the scent yourself?', 'Look at me, sir. A man in oil and wool don’t buy French perfume. It isn’t mine.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then let it air out, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the scent belongs to the fare’s back seat, not to the driver.',
        bargain: c('Point me to the fare and I keep your route clean?', 'Right, sir. Smell the back seat — same gardenia. It came off my passenger, never out of my pocket.', 'thoughtful'),
        challenge: c('That perfume puts you close to a lady—well?', 'Close enough to shut her door, sir. The scent’s on the seat and my collar, not a thing I’d ever wear.', 'angry'),
      }),
    r('chauffeur-powder', 'room', 'face-powder', 'How’d ivory face powder get on your shoulder?',
      'Same fare, sir. The lady powdered her face in the back and clouded half the cab. Some of it landed on me.', 'neutral',
      s(
        c('Who was she, this fare?', 'The guest I drove up from the station. The footman saw her get out; ask him where the powder came from.', 'thoughtful'),
        c('Isn’t that just dust off your cap?', 'Cap dust’s grey, sir. This is ivory — a lady’s powder, not a driver’s.', 'neutral'),
        c('That powder was pressed on. Explain.', 'It settled off her puff in my cab. Read it how you want; that’s the truth of it.', 'neutral'),
      ),
      s(
        c('Where did the powder land?', 'My right shoulder, where I turned to answer her. The footman watched the whole handover.', 'worried'),
        c('Couldn’t several women wear that shade?', 'Maybe, sir. Only one was powdering her face in my back seat tonight.', 'suspicious'),
        c('The powder means nothing.', 'Then we’re done, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the powdered fare against the footman who saw her.',
        bargain: c('Confirm the fare and I keep your name off it?', 'Fair, sir. The footman’ll place her in my cab; the powder’s off her puff, not my hand.', 'thoughtful'),
        challenge: c('That powder puts you near a lady—well?', 'Near a fare in my own cab, sir, with the footman watching. That’s a job, not a crime.', 'angry'),
      }),
    r('chauffeur-oil', 'timeline', 'blade-oil', 'Why are your hands slick with fine oil?',
      'The motor, sir. Oiled a sticky throttle linkage so she’d turn over if the road ever cleared. Light oil, precision stuff.', 'neutral',
      s(
        c('What exactly did you oil?', 'The linkage and a stiff door hinge while I had the can out. A drop does the throttle, a drop does the hinge.', 'thoughtful'),
        c('Why bother if nobody’s leaving?', 'A driver keeps his motor ready, sir. That’s the whole job, flood or no flood.', 'neutral'),
        c('That oil went where it shouldn’t. Explain.', 'It went where I put it, sir. I don’t answer for where you think it went.', 'neutral'),
      ),
      s(
        c('Where did the oil travel?', 'Can to my thumb to the rag in my back pocket. One trail, all garage, sir.', 'worried'),
        c('Couldn’t that oil come from a clock or blade?', 'Same light oil, different machine. Follow where it’s been, not what it looks like.', 'suspicious'),
        c('The oil’s meaningless.', 'Then drop it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the oil from the motor can through his thumb to the garage rag.',
        bargain: c('Show me the garage and I log your route straight?', 'This way, sir — can, thumb, rag, linkage. One trail, all mine, and none of it near the house.', 'thoughtful'),
        challenge: c('That oil ties you to something delicate—well?', 'To my own motor, sir. Follow the trail from the garage can; it don’t reach where you’re pointing.', 'angry'),
      }),
    r('chauffeur-wax', 'social', 'wax-resin', 'Why’s there an amber fleck of wax on your cuff?',
      'A parcel, sir. I was asked to run it out when the roads clear, sealed with wax so nobody opens it on the way. Stick cracked as I pressed it.', 'suspicious',
      s(
        c('What’s in the parcel?', 'Not my business, sir. A driver carries; he doesn’t unwrap. The seal’s the whole point.', 'thoughtful'),
        c('Who asked you to seal it?', 'A guest who paid in advance and asked no questions be asked back. Common enough in my line.', 'neutral'),
        c('That’s no delivery seal. Explain the wax.', 'It’s a parcel seal, sir. Believe it or don’t; the parcel stays shut and so do I.', 'neutral'),
      ),
      s(
        c('How’d the wax get on your cuff?', 'Snapped off the stick when I pressed the knot. Warm fleck, straight onto the cuff, sir.', 'worried'),
        c('Couldn’t that be an antiquarian’s resin?', 'Looks close. Mine’s off a sealing stick, not some relic. Test it.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then leave it be, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him seal the parcel again and show how the fleck flicks loose.',
        bargain: c('Show me how you sealed it and I keep the parcel out of it?', 'Right, sir. I press the knot here, the stick cracks there, the fleck hits my cuff. No mystery, just a job.', 'thoughtful'),
        challenge: c('That wax ties you to something sealed—well?', 'To a parcel I was paid to carry, sir. Watch me seal another; the wax breaks the same, proves nothing worse.', 'angry'),
      }),
    r('chauffeur-note', 'timeline', 'torn-note', 'What are those cramped little marks you keep folding away?',
      'Fares and addresses, sir. My own shorthand — pickup, drop, time. I tear off each run once it’s done.', 'suspicious',
      s(
        c('What was on tonight’s note?', 'A time and a spot to wait. Somebody wanted a car ready at an hour, sir. That’s all it says.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'Another driver, maybe. To the rest it’s scratches and mud.', 'neutral'),
        c('Those aren’t fares. Hand it over.', 'A driver’s notes stay with the driver, sir. Torn and done.', 'neutral'),
      ),
      s(
        c('What happened to the torn scrap?', 'Slipped out of my glove getting out of the cab. Hand to ground, I couldn’t tell you where, sir.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious man, sir, a pickup time looks like a plot.', 'thoughtful'),
        c('I’ll ask whoever booked the car.', 'Do, sir. They’ll say the same hour my note does.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read the pickup time back wrong, and let him correct the hour.',
        bargain: c('Read me the run plainly and I keep the fare private?', 'Fair, sir — but your hour’s wrong; it’s a quarter later. Fix it and you’ll see it’s just a pickup.', 'thoughtful'),
        challenge: c('This note reads like a getaway plan—well?', 'You’ve got the hour wrong, sir. Fix the time and your “plan” is a fare waiting for a car.', 'angry'),
      }),
    r('chauffeur-standing', 'connection', undefined, 'What’s it like, being the one man in the room nobody sees?',
      'Restful, mostly, sir. People say things in front of a driver they’d never say to a guest. I hear a lot by being furniture.', 'thoughtful',
      s(
        c('How’d you end up driving?', 'War took the job I trained for. A motor’s honest work, sir, and it don’t ask where a man went to school.', 'thoughtful'),
        c('Does it wear on you, the way they look through you?', 'Some. A man likes to be counted now and then. But the wage clears, and I keep my own counsel.', 'neutral'),
        c('Skip the life story. I’ve questions.', 'Course, sir. Nobody asks the driver twice.', 'neutral'),
      ),
      s(
        c('What do you want out of tonight?', 'To be heard as a witness, sir, not written off as the help. I saw things worth saying.', 'worried'),
        c('And what won’t you do?', 'Take the fall because it’s tidy for the gentry. Done that once. Not again.', 'suspicious'),
        c('We’re done here.', 'Right, sir. Engine off.', 'neutral'),
      ),
      {
        bargain: c('Off the record—what do you actually want from me?', 'Off the record, sir: to be believed. Give a working man that, and I’ll tell you every road I drove tonight.', 'thoughtful'),
        challenge: c('All that silence—what are you hiding, then?', 'A fare I was paid to keep quiet, sir, not a crime. Taking money to wait isn’t the same as guilt.', 'angry'),
      }),
    r('chauffeur-fares', 'intel', undefined, 'You’ve driven half these guests—what do you make of them?',
      'You learn a person quick from the back seat, sir. Where they’re soft, where they lie, what they tip when they’re scared.', 'suspicious',
      s(
        c('Who rode worst tonight?', 'One guest kept looking behind us the whole way up, sir. People do that when they’re running from something, not to it.', 'thoughtful'),
        c('You size everyone up by their fare?', 'It don’t lie, sir. A man’s manners in a cab are his manners with nobody watching.', 'neutral'),
        c('I want names, not driver’s wisdom.', 'Then I’m poor company, sir.', 'neutral'),
      ),
      s(
        c('What tell would you trust?', 'A tip too big, sir. Guilty hands pay heavy, like money buys off a bad feeling.', 'thoughtful'),
        c('Couldn’t nerves explain that?', 'Could, sir. I give you what I saw, not the verdict.', 'suspicious'),
        c('That’s enough.', 'Then we’re parked, sir.', 'neutral'),
      ),
      {
        bargain: c('Quietly—who should I keep an eye on?', 'Quietly, sir: the one who watched the road behind us and overpaid at the door. Fear and money together, that’s a story.', 'thoughtful'),
        challenge: c('You see everyone—so whose secret are you keeping?', 'A paid fare’s, sir, not a culprit’s. A man who buys my silence about a trip hasn’t bought me for worse.', 'angry'),
      }),
  ],

  debutante: [
    r('debutante-earth', 'room', 'fine-earth', 'Why take the conservatory shortcut?',
      'The corridor was crowded, and the jasmine is far nicer company.', 'neutral',
      s(
        c('What happened to your shoes in there?', 'A spilled pot poured pale, powdery grit straight into my slipper.', 'surprised'),
        c('Were you hiding from someone?', 'I prefer “avoiding a tedious conversation.” Much prettier.', 'suspicious'),
        c('You did not wander in there for flowers. Who were you trailing?', 'Oh good. My shoes have suffered quite enough.', 'neutral'),
      ),
      s(
        c('Whose footsteps were you following?', 'A repaired left heel, clicking oddly, all the way to that crooked panel.', 'thoughtful'),
        c('Couldn’t it be dust from an old vase?', 'Perhaps. This house sheds nearly as much as its guests.', 'neutral'),
        c('The dirt is unhelpful.', 'Then let’s not dig any deeper.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Retrace the repaired heel’s path from the spilled grit to the panel.',
        bargain: c('Walk me through exactly where you followed them.', 'Gladly. The grit fell here, the odd heel clicked there — and both end at that crooked panel.', 'thoughtful'),
        challenge: c('That conservatory grit puts you at the panel.', 'It puts me behind someone else’s repaired heel. I followed the mess; I didn’t make it.', 'angry'),
      }),
    r('debutante-perfume', 'social', 'floral-perfume', 'Whose atomizer were you borrowing?',
      'Mine, mostly. A friend’s gardenia refill made it far stronger than I meant.', 'neutral',
      s(
        c('Why did it smell so strong?', 'Someone had emptied half the bulb. It drenched my scarf on the vanity.', 'surprised'),
        c('Was it expensive?', 'Expensive enough to pretend the spill was intentional.', 'neutral'),
        c('Your scent walked a hall you claim you did not. Explain that.', 'Already hidden. This topic too.', 'neutral'),
      ),
      s(
        c('Where were you when the corridor filled with it?', 'At the card table, before witnesses — while my scent wandered a hall without me.', 'worried'),
        c('Couldn’t another guest wear gardenia?', 'Of course. Taste is not exclusive, sadly.', 'neutral'),
        c('The scent proves nothing.', 'Then we can stop discussing it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Set the scented corridor against the card table that keeps you seated.',
        bargain: c('Someone framed your scent — let me prove where you sat.', 'Please do. Three players will swear I never left the table while my perfume took its little stroll.', 'thoughtful'),
        challenge: c('Your perfume walked that corridor, and so did you.', 'My perfume did. I was losing at cards in plain view — the score sheet says so.', 'angry'),
      }),
    r('debutante-powder', 'timeline', 'face-powder', 'What happened to your compact?',
      'It slipped while I fixed my face. Ivory powder simply exploded.', 'surprised',
      s(
        c('Where did it spill?', 'Across my collar, my bag, and the little table by the mirror.', 'worried'),
        c('Why fix your face so often?', 'Because people ask questions like that.', 'angry'),
        c('Powder does not climb onto a latch by itself. What did you open?', 'Snapped shut. So is the subject.', 'neutral'),
      ),
      s(
        c('Did anything press through the powder?', 'A gloved hand swept it aside and left its seams printed on the brass latch.', 'thoughtful'),
        c('Couldn’t that be theatrical makeup?', 'It could. Mine has a nicer case.', 'neutral'),
        c('I’ve heard enough about cosmetics.', 'Thank heavens. Nothing more there.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the glove seam in the latch powder to your vanity lining.',
        bargain: c('Show me the latch and I’ll keep your papers safe.', 'Then look closely — the glove seams in that powder aren’t mine, but they pressed my vanity lining too.', 'thoughtful'),
        challenge: c('Your powder’s on the latch — you searched that panel.', 'A gloved hand searched it and wore my powder off. The seams in it are a stranger’s.', 'suspicious'),
      }),
    r('debutante-glance', 'intel', undefined, 'What have people assumed you failed to notice?',
      'That two guests swapped keys beneath the card table while explaining the rules to me.', 'suspicious',
      s(
        c('What did the keys look like?', 'One long and brass, one small and silver. Only the brass one changed hands.', 'thoughtful'),
        c('Were you cheating at cards?', 'Only at being underestimated.', 'neutral'),
        c('No more coy games. Which two, and which key?', 'If you insist. I fold.', 'neutral'),
      ),
      s(
        c('Where did the brass key go?', 'Into a left coat pocket, just before its new owner left the room alone.', 'thoughtful'),
        c('Couldn’t it have been a coin?', 'Coins don’t have teeth, detective. Even I know that.', 'angry'),
        c('That exchange is none of my concern.', 'Then we’ve nothing else to discuss.', 'neutral'),
      )),
    r('debutante-ink', 'timeline', 'ink-fiber', 'How did blue-black ink get on your fingers?',
      'I was writing in my little book by the clock. Everyone thinks I doodle hearts — I was noting the time, actually.', 'neutral',
      s(
        c('When exactly were you writing?', 'Right as the clock struck, silly — I remember because I dated the page. I do date my pages.', 'thoughtful'),
        c('What could you possibly be noting?', 'Oh, this and that. A figure, an hour. A girl’s allowed a diary, isn’t she?', 'neutral'),
        c('That is far more ink than a diary needs. Explain.', 'My pen simply burst. That’s all it is. Do let’s talk of something prettier.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'My fingers and the page corner, right at the hour I’d written down. It quite ruined my glove.', 'worried'),
        c('Couldn’t anyone else use that ink?', 'Heaps of people, I should think. Ink isn’t exactly a signature.', 'suspicious'),
        c('The ink leads nowhere.', 'Then let it dry, and me be.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the dated page against the exact stroke of the clock.',
        bargain: c('Show me the hour on the page and I’ll keep your diary safe?', 'How kind. The page is dated to the very chime — the ink and the hour agree, and neither of them accuses poor me.', 'thoughtful'),
        challenge: c('You dated that page to a telling minute—well?', 'So I keep careful time, detective. A girl who can read a clock isn’t a girl with a plot.', 'suspicious'),
      }),
    r('debutante-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply medicinal?',
      'Varnish remover, detective. I redid my nails before dinner. It reeks like a hospital, but it’s pure vanity, I promise.', 'neutral',
      s(
        c('What were you removing, exactly?', 'A chipped polish. One does not appear at dinner with a ruined manicure; there are standards, even in a storm.', 'thoughtful'),
        c('Why should I think it isn’t the real thing?', 'Because a surgeon’s carbolic and my remover only smell alike, silly. One mends nails; one mends people.', 'neutral'),
        c('That is a doctor’s antiseptic. Explain.', 'It’s acetone, from my vanity case. Believe your nose if you must; I’m quite finished.', 'neutral'),
      ),
      s(
        c('Where did the remover touch you?', 'My fingertips and a cotton pad — and my cuff, where I was careless. It clings like the surgeon’s, but it isn’t.', 'worried'),
        c('Couldn’t it be surgical antiseptic?', 'Only to a hurried nose. Sniff it properly and it’s pear-drops, not medicine.', 'suspicious'),
        c('The smell tells me nothing.', 'Then do stop sniffing my hands, detective.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid on her cuff is nail-varnish remover, not surgical carbolic.',
        bargain: c('Let me test it and I keep your vanity case private?', 'How gallant. Test it — acetone, not carbolic. They share a sting and absolutely nothing else.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve—well?', 'Smell again, detective. Mine takes off polish; his takes off infection. A shared reek isn’t a shared hand.', 'suspicious'),
      }),
    r('debutante-wool', 'social', 'black-wool', 'Whose black coat left threads all over you?',
      'A gentleman lent me his jacket when I got cold on the terrace. Terribly gallant, terribly scratchy — it shed everywhere.', 'neutral',
      s(
        c('Which gentleman lent it?', 'One who wanted to seem heroic, I expect. The wool snagged on my bracelet the moment he draped it.', 'thoughtful'),
        c('Do you often borrow men’s coats?', 'When they insist and the terrace is freezing, why not? It’s practically a public service.', 'neutral'),
        c('That thread is coarser than any dinner jacket. Explain.', 'Then it’s his outdoor coat, not his dinner one — do keep up. The coat went back; we’re finished.', 'neutral'),
      ),
      s(
        c('Where did the thread come loose?', 'At my bracelet clasp and my shoulder, where the collar sat. It followed me back inside, the beastly thing.', 'worried'),
        c('Couldn’t the thread be your own wrap?', 'My wrap is silk, detective. That coarse black strand is his gallantry, not mine.', 'suspicious'),
        c('The thread proves nothing.', 'Then do let go of it, please.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the coarse thread from the borrowed coat to her bracelet and shoulder.',
        bargain: c('Point me to the coat and I keep the gentleman out of it?', 'How considerate. Coat to bracelet to shoulder — the whole gallant little journey, and nothing wicked on it.', 'thoughtful'),
        challenge: c('That thread puts a man’s coat on you—well?', 'On me, detective, not the other way about. Borrowing a coat isn’t a crime, however scratchy.', 'suspicious'),
      }),
    r('debutante-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'My little silver hand-mirror had gone dreadfully dull, so I buffed it before dinner. Vanity is such hard work.', 'neutral',
      s(
        c('What exactly did you polish?', 'The mirror’s back and my compact’s clasp. Both had tarnished in this dreadful damp house.', 'thoughtful'),
        c('Do you polish your own silver?', 'When the staff are run off their feet, yes. I’m more capable than I look, detective — most people are.', 'neutral'),
        c('You buffed more than a hand-mirror. What else?', 'A lady never lists her fingerprints. Do let’s move on.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the mirror’s back — just where one holds it up to the light.', 'worried'),
        c('Couldn’t that smear be from the big silver?', 'It’s the same waxy stuff, I suppose. Only where it’s been could tell you which.', 'thoughtful'),
        c('The polish is meaningless.', 'Then do let it tarnish in peace.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the mirror’s handle too, and watch her correct you.',
        bargain: c('Help me quietly and I’ll keep your name spotless?', 'How sweet. I only did the back and the clasp, never the handle — whoever touched the big silver was far less tidy than me.', 'thoughtful'),
        challenge: c('That polish matches the dining-room silver—well?', 'I shined a hand-mirror, detective. Follow the smear to my vanity, not to a platter I never lifted.', 'suspicious'),
      }),
    r('debutante-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'My music box jammed mid-waltz — so vexing. A drop of oil on the little movement and it played again. I’m quite the mechanic, really.', 'surprised',
      s(
        c('What did you oil, exactly?', 'The comb and the cylinder, where it had seized. One drop, no more; the movement is dreadfully delicate.', 'thoughtful'),
        c('Where would a girl learn to oil a movement?', 'From taking things apart when the grown-ups thought I was napping. I was a frightful child, detective.', 'neutral'),
        c('That oil went somewhere it shouldn’t. Explain.', 'It went on my music box, silly. I shan’t apologise for mending my own things.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the cylinder sprang free. It marks whatever I touch afterward, annoyingly.', 'worried'),
        c('Couldn’t that oil be from a lock or a clock?', 'The very same little oil, I expect. All the delicate things drink it.', 'suspicious'),
        c('The oil means nothing.', 'Then let it dry, do.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her free the jammed music box again and show where the oil sprang.',
        bargain: c('Show me how the box freed and I’ll keep it between us?', 'Watch, then — I oil the comb here, the cylinder springs there, and the oil catches my thumb. No mystery, just a stubborn waltz.', 'thoughtful'),
        challenge: c('That oil ties you to a mechanism—well?', 'A music box, detective. Watch me mend it; the oil falls exactly where a clever girl would leave it.', 'suspicious'),
      }),
    r('debutante-wax', 'social', 'wax-resin', 'Why is there an amber fleck of wax on your glove?',
      'I sealed a letter with wax — a private one. Everyone reads a girl’s post if she lets them, so I don’t let them.', 'suspicious',
      s(
        c('Who was the letter for?', 'A friend who’ll tell you the very same, if you ask nicely. The seal keeps it mine until she opens it.', 'thoughtful'),
        c('Do girls still bother with sealing wax?', 'The careful ones do. A licked envelope can be steamed; hot wax leaves a scar if anyone tries.', 'neutral'),
        c('That’s no ordinary letter wax. Explain.', 'It’s perfectly ordinary, detective — I simply have secrets, like everyone. The letter stays sealed.', 'neutral'),
      ),
      s(
        c('How did the wax reach your glove?', 'It snapped off the stick as I pressed the seal; a warm fleck caught my glove. My friend has the matching half.', 'worried'),
        c('Couldn’t that fleck be an antiquarian’s resin?', 'To a careless eye, perhaps. Mine came off a sealing stick — ask the friend who holds the letter.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then do stop peering at my glove.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the seal against the friend who holds the matching letter.',
        bargain: c('Name who has the letter and I’ll keep it sealed?', 'How decent. My friend holds it; her seal is twin to the fleck on my glove. Ask her and it all agrees.', 'thoughtful'),
        challenge: c('That wax ties you to something sealed—well?', 'To a letter, detective. Ask my friend; her half matches mine. A sealed secret isn’t a sealed guilt.', 'suspicious'),
      }),
    r('debutante-note', 'timeline', 'torn-note', 'What are those cramped little marks you keep hiding?',
      'Card scores, detective. I keep a running tally — who owes what, who cheats. My hand’s dreadful, so it looks like scribbles.', 'suspicious',
      s(
        c('What was on tonight’s tally?', 'Names, hands, a running total. Everyone thinks I lose at cards; I keep better books than they know.', 'thoughtful'),
        c('Can anyone else read your marks?', 'Hardly. I made the shorthand up myself so nosy people can’t. Present company included.', 'neutral'),
        c('Those aren’t card scores. Hand them over.', 'A girl’s tally is a girl’s business. I tore that sheet ages ago.', 'neutral'),
      ),
      s(
        c('What happened to the torn sheet?', 'It slipped from my little bag between hands. From my lap to the floor, I couldn’t say where it went.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious mind, a card score looks like a conspiracy. Yours seems the suspicious sort.', 'thoughtful'),
        c('I’ll compare it to the card table myself.', 'Do. You’ll find it matches the score sheet exactly, detective.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match her cramped shorthand to the card table’s running score sheet.',
        bargain: c('Let me match it to the scores and I keep your winnings quiet?', 'How gallant. Lay my marks beside the table’s score sheet; they’re the same hand, the same night — nothing hidden.', 'thoughtful'),
        challenge: c('That note reads like a scheme—well?', 'Compare it to the card scores, detective. It matches them exactly. A tally isn’t a plot.', 'suspicious'),
      }),
    r('debutante-underestimated', 'connection', undefined, 'What is it like, being underestimated by everyone in the room?',
      'Marvellously useful, detective. People say anything in front of a girl they think can’t count. I can count beautifully.', 'thoughtful',
      s(
        c('When did you learn to use that?', 'The first time a grown man discussed money over my head as if I were a lamp. I’ve been listening ever since.', 'thoughtful'),
        c('Doesn’t it hurt, being dismissed?', 'It did once. Now it’s armour. Let them think me silly; silly girls hear the most.', 'neutral'),
        c('Drop the act. I have real questions.', 'Everyone wants the real me eventually. How refreshing that you asked.', 'neutral'),
      ),
      s(
        c('What are you actually fighting for?', 'My own money, detective, and the right to say what I saw without a guardian deciding it for me.', 'worried'),
        c('And what will you never allow?', 'To be handed off, hushed up, and filed away like a debut portrait. Not again.', 'suspicious'),
        c('We are finished here.', 'Are we? How you all love ending things for me.', 'neutral'),
      ),
      {
        bargain: c('Off the record—what do you truly want tonight?', 'Off the record: control. Of my accounts, my accusation, my future. Give me that and I’ll give you the truth I’ve been counting.', 'thoughtful'),
        challenge: c('All this performance—what are you hiding under it?', 'Papers, detective, not a crime. Protecting my own evidence isn’t the same as guilt.', 'suspicious'),
      }),
    r('debutante-watchers', 'intel', undefined, 'What have you noticed that the grown-ups think you missed?',
      'Almost everything, detective. When people believe you’re decorative, they stop performing. That’s when they get interesting.', 'suspicious',
      s(
        c('Who forgot you were watching?', 'One guest counted the exits every time the thunder hid it. People only map their escapes when they’re planning to use one.', 'thoughtful'),
        c('Do you spy on everyone?', 'I observe, detective. Spying sounds so grubby, and I have such lovely manners.', 'neutral'),
        c('I want names, not cleverness.', 'Then you’ll find me a most disappointing girl tonight.', 'neutral'),
      ),
      s(
        c('What would you actually swear to?', 'A whispered figure changing hands under the card table. I was dealt in; I saw the whole trade.', 'thoughtful'),
        c('Could you have misread it?', 'I might, detective. I give you what I saw, not what it means.', 'suspicious'),
        c('That’s enough observation.', 'Pity. I was rather enjoying being asked.', 'neutral'),
      ),
      {
        bargain: c('Quietly—who should I be watching?', 'Quietly: the one who counts the doors. Nervous people fidget; guilty ones plan. That one was planning.', 'thoughtful'),
        challenge: c('You see it all—so whom are you protecting?', 'Myself, detective, and my own papers. A girl guarding her evidence isn’t a girl to be arrested for it.', 'suspicious'),
      }),
  ],
}
