// Pack C — Jazz Vocalist, Antiquarian, Off-Duty Chauffeur, Debutante.
// Owned by the performance/false-presence & key/route writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_C: Record<Extract<ArchetypeId, 'vocalist' | 'antiquarian' | 'chauffeur' | 'debutante'>, AuthoredDialogueRoute[]> = {
  vocalist: [
    r('vocalist-perfume', 'room', 'floral-perfume', 'That floral scent follows you everywhere. Where does it come from?',
      'My atomizer leaked over my scarf before the first set. Gardenia got the encore instead of me.', 'neutral',
      s(
        c('How much of it spilled?', 'One little bulb, and the scarf drank the lot. I reeked of the flower shop all night.', 'thoughtful'),
        c('Is gardenia your signature?', 'A singer keeps some signatures off the program, sugar.', 'neutral'),
        c('That scent turned up somewhere you weren’t. How?', 'All right. That song is over.', 'neutral'),
      ),
      s(
        c('Where was that scarf while you sang?', 'That’s the thing — nowhere near the trouble. It sat folded in my case while the scent turned up in a hall I never walked.', 'worried'),
        c('Could the conservatory flowers smell the same?', 'Close enough to fool a hurried nose, not a patient one.', 'thoughtful'),
        c('That’s enough about the scent.', 'Then let it fade.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Set the scented hall against the scarf that stayed in her case.',
        bargain: c('Help me show someone used your perfume against you — quietly.', 'Gladly. That trail is gardenia I never spilled, on a route I never took.', 'thoughtful'),
        challenge: c('Your perfume turned up somewhere you claim you never walked.', 'It puts my scent there. Scent travels where my feet never did.', 'angry'),
      }),
    r('vocalist-powder', 'social', 'face-powder', 'There’s ivory powder dusted across your collar. Where’s that from?',
      'Just my compact. The ivory cracked and jumped clean across the dressing table before the first set.', 'neutral',
      s(
        c('What set the compact off?', 'It slipped when the lamps flickered and cracked wide open. Ivory everywhere.', 'surprised'),
        c('Who were you hoping to impress?', 'The whole room. Never one soul when an audience is going spare.', 'neutral'),
        c('That powder was pressed into a door. How?', 'Then the mirror goes quiet.', 'neutral'),
      ),
      s(
        c('Where did all that powder end up?', 'On my collar — and pressed into the dressing-room door, where somebody leaned in to listen.', 'worried'),
        c('Couldn’t anyone own stage powder?', 'Anybody can own it. Wearing it well is rarer.', 'neutral'),
        c('A cracked compact isn’t enough.', 'Then close it, and this too.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the print in the door powder to a card edge.',
        bargain: c('Help me show someone else pressed that powder — I keep your dressing room out of it.', 'Whoever leaned on my dressing-room door pressed a card carrier into it. The seams match, detective.', 'thoughtful'),
        challenge: c('That powder puts you where you shouldn’t be. Own it.', 'It puts my powder there, not me. The print pressed in it wears seams that aren’t mine.', 'suspicious'),
      }),
    r('vocalist-wax', 'timeline', 'wax-resin', 'There’s a smear of amber wax on your hands. What is that?',
      'Grip wax. A little amber cake I warm to keep a stubborn clasp moving and my hands from slipping.', 'thoughtful',
      s(
        c('Why warm the wax?', 'Cold wax skips. Warm it and it goes on smooth as a low note.', 'neutral'),
        c('Does wax improve the singing?', 'No, but this conversation may need several coats.', 'suspicious'),
        c('That wax has taken some odd shape. What pressed into it?', 'Fine by me. End of the number.', 'neutral'),
      ),
      s(
        c('What pressed into that soft wax?', 'Something with teeth. A brass key left its shape when it sat against the cake.', 'worried'),
        c('Couldn’t that be sealing wax?', 'Same family of shine, different rhythm. A test would tell.', 'thoughtful'),
        c('The wax is no concern of mine.', 'Then let that note resolve.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Press the key shape back into the wax.',
        bargain: c('Show me what leaned on that wax and I leave the key alone.', 'Watch — something sat on it while I wasn’t looking. Teeth-down, brass. The wax remembers what I didn’t see.', 'thoughtful'),
        challenge: c('Something left its shape in that wax. You’re hiding what used it.', 'A brass key, teeth-down — the wax took the impression, not me. A cake can’t choose what leans on it.', 'angry'),
      }),
    r('vocalist-ear', 'intel', undefined, 'What did you hear while everyone else was talking?',
      'A door at an odd moment, hurried shoes, then somebody humming to cover their nerves.', 'thoughtful',
      s(
        c('What were they humming?', 'One of my songs from earlier — but the last phrase came too fast.', 'suspicious'),
        c('Why hum at all?', 'Some people pray. Some lie. Some borrow a tune.', 'neutral'),
        c('Who was humming?', 'That’s where I stop.', 'neutral'),
      ),
      s(
        c('Where did they go?', 'From the side hall toward the stairs, and they stopped the moment another guest appeared.', 'thoughtful'),
        c('Could that have been you?', 'I know when I’m singing — even badly.', 'angry'),
        c('That’s not enough to follow.', 'Then we’re done.', 'neutral'),
      )),
    r('vocalist-ink', 'timeline', 'ink-fiber', 'Why are your fingers stained blue-black with ink?',
      'I mark my charts in ink before each set — a key change here, a rest there — and I date the margin by the chime. Tonight the pen bled worse than a torch song.', 'neutral',
      s(
        c('What were you marking tonight?', 'A late key change, right as the clock chimed. I keep time even off the stage.', 'thoughtful'),
        c('Why ink and not pencil?', 'Pencil fades under the lamps. Ink stays, same as a good lyric.', 'neutral'),
        c('That’s more ink than a chart needs.', 'The nib caught and wept. That’s the whole verse. We can let it end there.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'My fingers and the margin, right at the hour I’d just inked into the score.', 'worried'),
        c('Could another writer share that ink?', 'Half this house scribbles. Ink doesn’t sign a name.', 'suspicious'),
        c('That’s enough about the ink.', 'Then let that note fade.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the inked margin to the clock stroke she marked.',
        bargain: c('Give me the hour on the score — I leave the rest unread.', 'Sweet of you. The margin’s inked to the chime I marked it by; the hour and the stain sing the same note, nothing more.', 'thoughtful'),
        challenge: c('You inked that score at a minute you’re covering. Which?', 'So I keep good time. A singer on the beat isn’t a singer with a motive.', 'angry'),
      }),
    r('vocalist-antiseptic', 'room', 'antiseptic', 'Your hands and scarf reek of something medicinal. Why?',
      'Throat wash and a menthol chest rub before a set. It bites like a sickroom, but it’s all a singer’s vanity.', 'neutral',
      s(
        c('What exactly do you use it for?', 'To open the pipes. Damp weather closes a voice like a bad review; the rub keeps the low notes low.', 'thoughtful'),
        c('Why should I believe it isn’t the real thing?', 'Because a surgeon’s carbolic and my gargle just happen to share a sting. Different bottles entirely.', 'neutral'),
        c('That smell’s a doctor’s.', 'Trust your nose over my dressing table if you like. That song’s over.', 'neutral'),
      ),
      s(
        c('Where did the wash touch you?', 'My scarf and fingers, where I dabbed the rub. It clings all night, same as the surgeon’s — but it isn’t.', 'worried'),
        c('Could it be surgical antiseptic instead?', 'Only to a nose in a rush. Taste it and it’s menthol and honey, not medicine.', 'suspicious'),
        c('That’s enough about the smell.', 'Then quit breathing in my vanity.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the scarf smells of throat wash, not carbolic.',
        bargain: c('Let me test the bottle — I won’t call it a surgeon’s.', 'Sweet. Test it — throat wash, menthol, honey. It shares a sting with carbolic and nothing else.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your scarf. Explain it.', 'Sniff again, detective. Mine soothes a voice; his cleans a wound. A shared sting isn’t a shared crime.', 'angry'),
      }),
    r('vocalist-earth', 'social', 'fine-earth', 'What is that pale grit on your hands and hem?',
      'Grip chalk, near enough — I keep a tin of it and chalk my palms so the microphone stand doesn’t slide when the room gets warm.', 'neutral',
      s(
        c('What do you use the powder for?', 'A slick grip drops a mic mid-song. A little chalk and the stand stays put.', 'thoughtful'),
        c('Isn’t that just floor dust?', 'Finer than any floor. It comes from my own tin, not your garden.', 'neutral'),
        c('That grit looks like floor dust, not chalk.', 'You want to write me crawling in the dirt. That’s not my number.', 'neutral'),
      ),
      s(
        c('Where did the powder settle?', 'My palms, my hem, the stand I gripped. It’s paler and finer than soil, if you look close.', 'worried'),
        c('Could it match the conservatory grit?', 'At a glance, maybe. Side by side, my chalk’s milled even; garden grit never is.', 'suspicious'),
        c('The grit isn’t helping.', 'Then let the dust settle.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare her palm chalk to the grip tin and the garden grit.',
        bargain: c('Show me your tin and I won’t chase the conservatory.', 'Kindly. Set my palm by the tin; the grip chalk matches, the garden grit doesn’t.', 'thoughtful'),
        challenge: c('That grit came from the conservatory. Your chalk story won’t hold.', 'Compare them. My chalk’s even; soil isn’t. They won’t match.', 'angry'),
      }),
    r('vocalist-wool', 'timeline', 'black-wool', 'Where did that frayed black wool come from?',
      'My performance stole. Black, warm, a little worn — it caught on a splintered doorframe by the side hall and shed threads down my shoulder.', 'neutral',
      s(
        c('What made it fray like that?', 'The splinter took a thread the moment I brushed past. Old weave gives easily.', 'thoughtful'),
        c('Why wear a heavy stole indoors?', 'A cold room steals a voice. I keep my shoulders warm the way a horn player keeps his reed.', 'neutral'),
        c('That stole took you somewhere you deny.', 'You haven’t touched my stole, so you can’t say. I won’t sing to your guess.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after that?', 'Doorframe to shoulder to the chair I draped it on. Follow it and it plays straight through.', 'worried'),
        c('Could the thread be another dark coat?', 'Could be. Coarse black wool’s common enough to accuse half the room.', 'suspicious'),
        c('The thread isn’t enough.', 'Then let it hang loose.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the doorframe to her stole.',
        bargain: c('Show me where the stole snagged and I keep it quiet.', 'Sweet. Doorframe to shoulder to chair — the whole soft little journey, and nothing sharp on it.', 'thoughtful'),
        challenge: c('That thread puts you in the side hall for more than a song.', 'So my stole brushed a door, detective. Passing through a hall isn’t a plot.', 'angry'),
      }),
    r('vocalist-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'I keep my microphone stand and my locket bright. A dull stand under the lights looks like a dull act.', 'thoughtful',
      s(
        c('What exactly did you polish?', 'The stand’s neck and my little silver locket. Both had gone grey in the damp.', 'suspicious'),
        c('Do you shine everything you own?', 'Only the things the audience sees. The rest can tarnish in peace.', 'neutral'),
        c('What else did you polish?', 'A lady doesn’t catalogue her fingerprints. That number’s finished.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the stand’s neck — right where a hand grips to sing.', 'worried'),
        c('Could that smear be from the silver?', 'Same waxy stuff, near enough. Only where it’s been tells you which.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then let it go dull.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the locket’s back — see if she corrects you.',
        bargain: c('Help me quietly and I keep your name clean.', 'Obliging of you. I shined only the front and the neck; whoever handled the silver was messier than me.', 'thoughtful'),
        challenge: c('That polish matches the silver upstairs. You handled more than a mic stand.', 'I shine a mic stand, detective. Follow the smear to my locket, not to a plate I never lifted.', 'angry'),
      }),
    r('vocalist-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'My music case latch seized in the damp. One drop of light oil and it snapped open again, smooth as a slow number.', 'neutral',
      s(
        c('What exactly did you oil?', 'The latch and the little hinge on the lid. Both had rusted stiff in this weather.', 'thoughtful'),
        c('Why fuss with a case tonight?', 'Because my charts live in it, and a stuck latch means no set. Couldn’t wait.', 'neutral'),
        c('That oil went where it shouldn’t.', 'You suppose a lot from a slick thumb, detective. I won’t sing to it.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the latch sprang back. It marks whatever I touch after.', 'worried'),
        c('Could that oil be from a lock or a blade?', 'Same light oil, different job. A dozen little machines take it.', 'suspicious'),
        c('That’s enough about the oil.', 'Then let it dry.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her free the case latch again and show where the oil went.',
        bargain: c('Show me how the case opened and I leave the latch alone.', 'Watch — I oil the latch here, it springs there, the oil catches my thumb. No mystery, just a stuck lid.', 'thoughtful'),
        challenge: c('That oil touched more than a music case. What else did you free?', 'A music case, detective. Watch me free it; the oil lands right where an honest fix would put it.', 'angry'),
      }),
    r('vocalist-note', 'social', 'torn-note', 'What are those cramped little marks you keep tucking away?',
      'Song requests — a shorthand of my own for who wants what and when. I tear off each one as I sing it.', 'suspicious',
      s(
        c('What was on the marks tonight?', 'A title, a table, a time. Somebody wanted a particular tune at a particular hour.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'Another band singer, maybe. To the rest it’s just scratches and hope.', 'neutral'),
        c('Those aren’t song requests. Hand them over.', 'A singer’s notes stay in a singer’s glove. That verse is done.', 'neutral'),
      ),
      s(
        c('What became of the torn scrap?', 'It slipped from my glove between numbers. From my hand to the floor, I couldn’t swear where.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious eye, a shopping list looks like a scheme.', 'thoughtful'),
        c('I’ll ask whoever made the request.', 'Do. They’ll hum it back the same as my note.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the guest who requested the tune.',
        bargain: c('Name who asked for the song — I won’t put it in print.', 'Sweet. The guest who asked will confirm the tune and the hour; my note just sings back what they wanted.', 'thoughtful'),
        challenge: c('That scrap looks like more than a song request. What are you hiding?', 'To a song request, detective. Ask the guest; my marks and their wish are the same tune.', 'angry'),
      }),
    r('vocalist-road', 'connection', undefined, 'How did you end up singing in a house like this?',
      'You follow the work, and the work follows the money — into colder rooms than the clubs I came up in.', 'thoughtful',
      s(
        c('Where did you learn to sing?', 'Rooms full of smoke and second chances. I learned the blues before I learned my letters.', 'thoughtful'),
        c('Is it lonely?', 'A little. The room loves the song, never quite the girl singing it.', 'neutral'),
        c('I have other questions.', 'Course you do.', 'neutral'),
      ),
      s(
        c('Who are you looking out for?', 'A friend who kept me singing when a powerful man tried to take my voice for himself.', 'worried'),
        c('What won’t you do?', 'Sing someone else’s lie because the pay is good. I did it once. Never again.', 'suspicious'),
        c('We’re done here.', 'Pity.', 'neutral'),
      ),
      {
        bargain: c('Honestly — what are you carrying tonight?', 'A tune that isn’t mine to lose, and a friend I won’t let anyone silence.', 'thoughtful'),
        challenge: c('What are you hiding?', 'A friend’s name, not a crime. Keeping someone safe isn’t guilt.', 'angry'),
      }),
    r('vocalist-room', 'intel', undefined, 'Looking at this room — what do you notice?',
      'Everybody’s a little off tonight. Fear pulls a voice wrong, and I hear it all over this house.', 'suspicious',
      s(
        c('Who sounds off?', 'One guest laughs a half-beat late — like they’re listening for something under the music.', 'thoughtful'),
        c('You judge people by how they sound?', 'It’s truer than words sometimes. A voice can’t hide the way a face can.', 'neutral'),
        c('I need a name.', 'Then I’m poor company tonight.', 'neutral'),
      ),
      s(
        c('What would you trust as a real sign?', 'The breath before a lie. It catches every time.', 'thoughtful'),
        c('Could you be hearing it wrong?', 'Sure. I give you what I hear, not a verdict.', 'suspicious'),
        c('That’s enough.', 'Then we’re done.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who’s trying too hard to sound calm?', 'The one who’s too smooth. Real calm breathes. A fake one holds too long.', 'thoughtful'),
        challenge: c('Who are you covering for?', 'A friend’s name — not a culprit’s.', 'angry'),
      }),
  ],

  antiquarian: [
    r('antiquarian-earth', 'room', 'fine-earth', 'There’s pale dust on your fingertips and hem. Where did it come from?',
      'A reliquary I was studying — modern hinge, undocumented base. Pale packing dust sits beneath that false base, finer than any garden soil.', 'thoughtful',
      s(
        c('What was packed beneath the base?', 'Display packing — pumice-like and pale. Certainly not the flowerbeds.', 'thoughtful'),
        c('How old is the piece, truly?', 'Late medieval in aspiration. Rather more recent in execution.', 'angry'),
        c('What was under that false base?', 'Object returned; inquiry concluded.', 'neutral'),
      ),
      s(
        c('Where did that dust travel?', 'From the false base to my fingertips, then along the hem to the west panel.', 'worried'),
        c('Couldn’t it just be plaster?', 'To an untrained eye. The grain deserves magnification.', 'suspicious'),
        c('The dust is not important.', 'Philistinism noted. We are done.', 'angry'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the packing dust from the false base toward the panel.',
        bargain: c('Tell me what was under the false base — discreetly.', 'Hear it gently: the base opened to a compartment, and its dust marks the road I walked to the panel.', 'worried'),
        challenge: c('That dust marks a path you’re not owning. Where did it really lead?', 'I followed dust, not a plan. Where packing falls is not where guilt lies.', 'angry'),
      }),
    r('antiquarian-polish', 'timeline', 'metal-polish', 'Why is there waxy polish streaked on your glove and cuff?',
      'Authentication. I test old brass with a pinhead of waxy polish — it takes the wax differently from a modern plate.', 'neutral',
      s(
        c('What exactly did you treat?', 'A pinhead of polish to one inconspicuous corner of a fitting. No more.', 'thoughtful'),
        c('Did you have permission?', 'History outranks temporary ownership, within reason.', 'suspicious'),
        c('What else did you handle?', 'I have stopped discussing it, at least.', 'neutral'),
      ),
      s(
        c('How did the polish reach you?', 'My glove split at the thumb; the streak crossed skin, cuff, and a catalog card.', 'worried'),
        c('Couldn’t silver polish match it?', 'Close enough to fool a glance. The mix would tell them apart.', 'thoughtful'),
        c('No more conservation lessons.', 'A merciful end to your education.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the streak on his card to the polish tin.',
        bargain: c('Let me match your polish to its source — quietly.', 'By all means — the streak on my card and the tin by the passage share a formula. Nothing to hide there.', 'thoughtful'),
        challenge: c('That polish touched more than authentication. What did you wipe?', 'I noticed a new hinge on an old saint, detective. Noticing a forgery is not committing a crime.', 'angry'),
      }),
    r('antiquarian-resin', 'social', 'wax-resin', 'There’s fresh amber resin on your fingers. What’s it from?',
      'A lifted veneer on the reliquary. I bedded it with warm amber restoration resin — neglect is history’s dullest vandal.', 'angry',
      s(
        c('How did you set the veneer?', 'Warm amber resin, sparingly, beneath the lifted edge. It goes on tacky and holds.', 'thoughtful'),
        c('Was the reliquary valuable?', 'Culturally, immensely. Financially, ask the ledger worshipper.', 'neutral'),
        c('That resin is fresh — and not just on the relic. Where else?', 'The relic and this topic are now sealed.', 'neutral'),
      ),
      s(
        c('How fresh is that resin?', 'Mine went on tonight — still tacky. The flecks in the old passage are decades cured.', 'worried'),
        c('Couldn’t sealing wax look identical?', 'Superficially. Age would expose the impostor.', 'suspicious'),
        c('I need no provenance lecture.', 'Your loss. The lecture concludes.', 'angry'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Compare his fresh resin to the old flecks in the passage.',
        bargain: c('Help me date the resin — I leave the patron unnamed.', 'Then note the ages: my resin is hours old, the passage flecks are generations. Time itself parts them.', 'thoughtful'),
        challenge: c('That fresh resin isn’t only on the relic. You’re covering a second use.', 'My resin is on the relic, hours old. Any flecks in that old passage wear a far older hand than mine.', 'angry'),
      }),
    r('antiquarian-history', 'intel', undefined, 'Does this house have any hidden history I should know about?',
      'Its servants once used a narrow route between the public rooms, now hidden behind the paneling.', 'thoughtful',
      s(
        c('Is that route still usable?', 'One panel has fresh scratches around an otherwise old catch.', 'suspicious'),
        c('Why does that matter?', 'Fresh damage on old wood earns attention.', 'angry'),
        c('Which panel?', 'That’s as far as I go for now.', 'neutral'),
      ),
      s(
        c('Where is the scratched panel?', 'Beside the landscape whose frame hangs slightly crooked in the west passage.', 'thoughtful'),
        c('Couldn’t movers have marked it?', 'Possible, though nothing was moved recently that I know of.', 'suspicious'),
        c('I’ll ignore the passage.', 'As you like.', 'neutral'),
      )),
    r('antiquarian-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink staining your fingers?',
      'I catalogue in ink, as one should, and I date every entry to the hour I make it. Pencil is for schoolboys and forgers.', 'neutral',
      s(
        c('When were you cataloguing tonight?', 'On the hour precisely — the ink and the clock keep each other honest.', 'thoughtful'),
        c('Why catalogue during a party?', 'Because a piece unrecorded is a piece half-lost. History does not adjourn for canapés, detective.', 'neutral'),
        c('That’s far more ink than an entry needs.', 'The nib split across the card and flooded. That is the whole of it; I shall say no more.', 'neutral'),
      ),
      s(
        c('Where did the flooded ink settle?', 'My forefinger and the card’s edge, at the very hour I had inscribed upon it.', 'worried'),
        c('Could another writer share that ink?', 'Any scribbler could. Ink respects no discipline, sadly, not even mine.', 'suspicious'),
        c('That’s enough about the ink.', 'Then let it dry, unremarked.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the dated catalog card to the clock stroke.',
        bargain: c('Give me the hour on the card — I won’t ask for the rest.', 'Civilised of you. The card is dated to the chime I wrote it by; ink and hour concur, and neither indicts me.', 'thoughtful'),
        challenge: c('You dated that card to cover a minute you can’t account for.', 'So I record time meticulously, detective. Scholarship is a habit, not a crime.', 'angry'),
      }),
    r('antiquarian-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply medicinal?',
      'Conservation solvent — a spirit I use to lift old varnish. It reeks of the sickroom, but it has never touched a patient, detective.', 'neutral',
      s(
        c('What were you treating with it?', 'A clouded lacquer on a reliquary hinge. The spirit cuts the grime where water would ruin the piece.', 'thoughtful'),
        c('Why should I believe it isn’t surgical?', 'Because a surgeon’s carbolic and a restorer’s spirit merely share a bite. Their purposes could not differ more.', 'neutral'),
        c('That’s a doctor’s antiseptic.', 'It is a conservator’s spirit. Trust your nose if you must; the topic is closed.', 'neutral'),
      ),
      s(
        c('Where did the solvent touch you?', 'Fingertip and cuff, where the swab slipped. It lingers loud, the same as carbolic — yet it is not.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test the fluid. Mine dissolves varnish; his cleans wounds. Chemistry will part them at once.', 'suspicious'),
        c('That’s enough about the smell.', 'Then cease inhaling my materials.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the spirit lifts varnish, not infection.',
        bargain: c('Let me test the bottle — I won’t call it a surgeon’s.', 'Reasonable. Test it — a restorer’s spirit, not carbolic. Same smell, different job.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve. Explain it.', 'Analyse it. Mine strips lacquer; his strips infection. You have mis-attributed the fluid entirely.', 'angry'),
      }),
    r('antiquarian-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My scholar’s coat — dark, decades old. It caught on a display case in the west passage, where the glass meets a rough brass edge, and shed threads down my sleeve.', 'neutral',
      s(
        c('What exactly snagged it?', 'That rough brass corner where the glass meets the frame. Old weave surrenders a thread at once.', 'thoughtful'),
        c('Why wear such an old coat here?', 'Sentiment and warmth, detective. A garment, like an antique, improves with documented age.', 'neutral'),
        c('That thread is coarser than your coat.', 'You haven’t examined my coat, so you can’t say that. I won’t argue a guess.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after that?', 'From the case corner to my elbow to the ledge I steadied a piece upon. A traceable little chain.', 'worried'),
        c('Could the thread be another dark coat?', 'Entirely possible. Coarse black wool is a poor witness; it accuses everyone and no one.', 'suspicious'),
        c('The thread isn’t enough.', 'A conclusion of rare good sense.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the display case to his elbow.',
        bargain: c('Show me where the coat snagged and I keep it quiet.', 'Very well. Case to elbow to ledge — the whole short trip, and nothing wrong in it.', 'thoughtful'),
        challenge: c('That thread puts you at the west passage case for more than looking.', 'Admiring a case, detective. Leaning near glass is not a plot.', 'angry'),
      }),
    r('antiquarian-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your coat?',
      'A guest leaned over my shoulder to look at a piece and left her scent on my coat. Two other people saw her do it.', 'neutral',
      s(
        c('Who leaned over you?', 'A woman looking at the reliquary. She pressed close for a better look.', 'thoughtful'),
        c('Do people often crowd you like that?', 'When the piece is fine enough, yes. They forget themselves.', 'neutral'),
        c('That scent looks worn, not caught.', 'It came off her sleeve onto mine. I don’t wear gardenia. We’re done.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My shoulder and collar, where she bent to see. Ask the two who watched — they’ll say the same.', 'thoughtful'),
        c('Could you wear the scent yourself?', 'Gardenia? Ask anyone who’s sat through one of my lectures.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then stop following it.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the two people who watched her lean over.',
        bargain: c('Name who admired the piece — I keep it off the record.', 'Fair. The two who watched will place her at my shoulder — her scent, not mine.', 'thoughtful'),
        challenge: c('That perfume puts you alone with someone. Who?', 'Close to someone looking at a piece, with witnesses. Standing near a person isn’t proof of anything.', 'angry'),
      }),
    r('antiquarian-powder', 'room', 'face-powder', 'How did ivory powder come to be on your sleeve?',
      'A lady brushed past me at the display and left half her compact on my coat. The passage is narrow; collisions are inevitable.', 'neutral',
      s(
        c('Who brushed past you?', 'A woman hurrying from the gallery. I registered the brush of her more than the face, I confess.', 'thoughtful'),
        c('Is that not simply your own powder?', 'I use chalk-white whiting for restoration, not ivory on my face. It’s a lady’s powder.', 'neutral'),
        c('That powder looks applied, not brushed.', 'You reconstruct a fiction from a smudge. I shall not authenticate it.', 'neutral'),
      ),
      s(
        c('Where did the powder settle?', 'My upper sleeve and shoulder — precisely where a passing arm would meet me.', 'worried'),
        c('Could several women wear that shade?', 'Several might. Only one wears it heavily enough to bequeath it to strangers.', 'suspicious'),
        c('That’s enough about the powder.', 'Then let it settle out of the catalogue.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder on his sleeve to the compact.',
        bargain: c('Help me find whose compact it is — quietly.', 'Obliging. Match the shade to her compact, not my sleeve; my whiting is chalk-white, not ivory.', 'thoughtful'),
        challenge: c('That powder puts you near someone you won’t name. Who?', 'Near a careless shoulder, detective. Compare the shade; it is hers, and demonstrably not mine.', 'angry'),
      }),
    r('antiquarian-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'I eased a seized antique lock to examine its wards. One drop of light oil and a mechanism two centuries old turned sweetly again.', 'neutral',
      s(
        c('What lock were you examining?', 'A period escutcheon on a cabinet. The wards tell you the maker; a frozen lock tells you nothing.', 'thoughtful'),
        c('Why oil someone else’s cabinet?', 'To read it, detective. A conservator cannot resist a mechanism begging to be understood.', 'neutral'),
        c('That oil went where it shouldn’t.', 'You infer a great deal from a slick thumb. I decline to indulge it.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the bolt sprang. It marks whatever I handle thereafter.', 'worried'),
        c('Could that oil be from a blade or a clock?', 'The same light oil serves them all. Only its use distinguishes them.', 'suspicious'),
        c('That’s enough about the oil.', 'Then permit the matter to rust.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him free the lock again and show where the oil went.',
        bargain: c('Show me how the lock freed and I leave the ward alone.', 'Gladly. I oil the ward here, the bolt springs there, and the oil catches my thumb — a scholar’s fix, nothing worse.', 'thoughtful'),
        challenge: c('That oil touched more than an old lock. What else did you open?', 'An antique lock, detective. Watch me ease it; the oil falls exactly where honest curiosity would leave it.', 'angry'),
      }),
    r('antiquarian-note', 'social', 'torn-note', 'What are those cramped marks you keep noting down?',
      'Catalogue shorthand — accession codes, condition notes, a date of examination. I tear off each completed slip as I file it.', 'suspicious',
      s(
        c('What did the notes record?', 'The condition of a piece and the hour I examined it. Dull to you; indispensable to posterity.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'A fellow curator, perhaps. To the layman it is a thicket of abbreviations.', 'neutral'),
        c('Those are no catalogue notes. Hand them over.', 'A scholar’s notes remain a scholar’s. The slip is torn and the topic with it.', 'neutral'),
      ),
      s(
        c('What became of the torn slip?', 'It parted from my folio as I rose; from desk to floor, I did not follow it. Careless of me.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious reader, an accession code resembles a conspiracy.', 'thoughtful'),
        c('I will read it myself.', 'Then mind you do not mistake a condition note for a confession.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read one number wrong and let him correct it.',
        bargain: c('Read me the slip plainly — patron stays unnamed.', 'Very well — but your accession number is transposed. Correct it and you will see it is merely a condition report.', 'thoughtful'),
        challenge: c('This note reads like a plot. What are you coding?', 'You have misread the code, detective. Restore the digits and your “plot” becomes a catalogue entry.', 'angry'),
      }),
    r('antiquarian-vocation', 'connection', undefined, 'Why give your life to old objects?',
      'They keep their promises. A genuine piece is honest about its age. People and forgeries lie.', 'thoughtful',
      s(
        c('How did you get started?', 'A cracked Roman lamp my grandfather refused to throw away. I’ve been mending neglect ever since.', 'thoughtful'),
        c('Do you prefer objects to people?', 'Objects don’t disappoint you twice. That recommends them.', 'neutral'),
        c('I have other questions.', 'Very well. Ask.', 'neutral'),
      ),
      s(
        c('What would you fix if you could?', 'One authentication I signed that I now doubt. A false attribution weighs on me.', 'worried'),
        c('What would you never do?', 'Knowingly certify a forgery for money. Once would be a mistake. Twice would unmake me.', 'suspicious'),
        c('We’re finished here.', 'A pity.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what troubles you tonight?', 'A piece I called genuine that I now suspect is not. Correcting that may cost me a great deal.', 'worried'),
        challenge: c('What is all this learning hiding?', 'A mistaken attribution — not a motive.', 'angry'),
      }),
    r('antiquarian-guests', 'intel', undefined, 'What do you make of the other guests?',
      'A mixed lot. A few are exactly what they seem. Several are clever fakes in good frames.', 'suspicious',
      s(
        c('Who seems fake?', 'One guest handles everything — and everyone — a shade too casually.', 'thoughtful'),
        c('Do you judge people like objects?', 'Wear patterns don’t flatter, whether on silver or on a smile.', 'neutral'),
        c('I need a name.', 'Names I withhold. Impressions I have plenty of.', 'neutral'),
      ),
      s(
        c('Who do you like here?', 'The curator. She cares for living things the way I care for made ones.', 'thoughtful'),
        c('Who bothers you?', 'The one who asked the reliquary’s price before its history.', 'suspicious'),
        c('That’s enough.', 'Then we can stop.', 'neutral'),
      ),
      {
        bargain: c('Off the record — who worries you most?', 'The one who priced a sacred object like a paperweight. People who only see cost frighten me.', 'thoughtful'),
        challenge: c('Who are you protecting?', 'A pressured patron — not a culprit.', 'angry'),
      }),
  ],

  chauffeur: [
    r('chauffeur-solvent', 'room', 'antiseptic', 'What’s that sharp smell on your hands?',
      'Motor solvent, sir — from the tin in my kit. Battery terminal furred up before the rain came in.', 'neutral',
      s(
        c('What sort of solvent?', 'Clear stuff from the motor kit. Bites the nose. Not the doctor’s sort.', 'thoughtful'),
        c('Will the car start now?', 'Road’s flooded. Starting isn’t leaving.', 'neutral'),
        c('That smell is not just the garage. What did it touch?', 'Fine. Garage is closed.', 'neutral'),
      ),
      s(
        c('How did it reach your cuff?', 'Bottle kicked when I set it down. Splashed me before I capped it.', 'worried'),
        c('Couldn’t that be medical antiseptic?', 'Smells close. I’m no chemist, but mine came from a motor tin.', 'suspicious'),
        c('That’s enough about the solvent.', 'Then we’re done with it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match his cuff to the motor tin, not the doctor’s shelf.',
        bargain: c('Point me to the tin and I won’t call it a doctor’s.', 'Right there on the bench, sir. Same label as my cuff. Nothing off the doctor’s shelf about it.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve. Explain it.', 'It’s battery solvent, sir. You smell a workingman and write “guilt”. Match the tin first.', 'angry'),
      }),
    r('chauffeur-wool', 'timeline', 'black-wool', 'Where did that black wool thread come from?',
      'My coat, most likely, sir. Black wool, warm and tough — but the sleeve caught a seat spring and the seam’s been shedding at the wrist ever since.', 'neutral',
      s(
        c('How bad is that wrist seam?', 'Frays a little more every time I reach across the seat. Been trailing threads all evening.', 'worried'),
        c('Why dress for work off duty?', 'Car trouble doesn’t check the invitation.', 'neutral'),
        c('A wrist tear won’t account for all of it.', 'Done.', 'neutral'),
      ),
      s(
        c('Where exactly does your coat shed?', 'At the wrist, sir, only the wrist — where the seat spring caught it. Nowhere near the elbow.', 'thoughtful'),
        c('Couldn’t it be another black coat?', 'That’s my point. Two coats, two weaves.', 'suspicious'),
        c('The thread’s useless.', 'Then stop pulling it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Compare his wrist tear to the coarser elbow thread.',
        bargain: c('Help me clear your coat — quietly.', 'Appreciated, sir. Mine frayed at the wrist on a seat spring; if your thread’s elbow-high and coarser, it can’t be the same coat.', 'thoughtful'),
        challenge: c('Your coat left that thread where it shouldn’t be. Own the path.', 'Can’t have, sir. Mine sheds at the wrist; if that one’s at the elbow and coarser, look again before you decide.', 'angry'),
      }),
    r('chauffeur-polish', 'social', 'metal-polish', 'Why is there waxy metal polish on your cuff and glove?',
      'The Bentley’s radiator badge, sir. Butler wanted it bright before the weather turned, so I saw to it out in the garage.', 'neutral',
      s(
        c('What polish did you use?', 'Tin by the garage door. Waxy stuff, smells of pennies and paraffin.', 'thoughtful'),
        c('Why polish a car in this storm?', 'Job came before the rain. Weather doesn’t cancel chores.', 'neutral'),
        c('What else did that polish touch?', 'Ask the glasses. I’m done with the motor.', 'neutral'),
      ),
      s(
        c('How did that polish get onto you?', 'No rag, sir. I wiped two fingers in my glove; the split smeared the garage latch and my cuff.', 'worried'),
        c('Couldn’t that smear come from silver?', 'Could. Same sort of compound. I didn’t touch silver.', 'suspicious'),
        c('That’s enough about the badge.', 'Then nothing more to say on it.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the polish from the garage tin to the latch.',
        bargain: c('Show me the garage trail and I leave the silver alone.', 'This way, sir — tin, glove, latch, cuff. One trail, all garage. Nothing near the silver.', 'thoughtful'),
        challenge: c('That polish matches the silver upstairs. You handled more than a latch.', 'Same compound, different job, sir. Follow it from my tin, not from the dining room.', 'angry'),
      }),
    r('chauffeur-traffic', 'intel', undefined, 'Who’s been moving through the halls?',
      'Plenty of trips. One guest used the service door twice and pretended not to know it existed.', 'suspicious',
      s(
        c('How do you know it was the same person?', 'Same step. Heel drags on the left when they hurry.', 'thoughtful'),
        c('You can tell people by their footsteps?', 'Drive long enough, you hear bad bearings.', 'neutral'),
        c('Did you see their face?', 'I’m not saying. Road closed.', 'neutral'),
      ),
      s(
        c('When was the second trip?', 'After the hall clock chimed, before the next thunderclap.', 'thoughtful'),
        c('Couldn’t a servant walk that way?', 'Could. Didn’t look like staff shoes.', 'suspicious'),
        c('That timing’s too vague.', 'Then we’re done.', 'neutral'),
      )),
    r('chauffeur-ink', 'timeline', 'ink-fiber', 'Why’s there blue-black ink on your fingers?',
      'Route log, sir. I write down every run — where, when, who — and mark the hour to the minute. Pen leaked when I logged the last one.', 'neutral',
      s(
        c('When did you make the last entry?', 'On the hour, sir. Clock chimed while I was writing. I log the time to the minute; always have.', 'thoughtful'),
        c('Why keep a log off duty?', 'Habit. A driver with no record is a driver who takes the blame for other men’s trips.', 'neutral'),
        c('That’s more ink than a log needs.', 'Nib split. That’s the whole of it. Leave it there.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'Fingers and the page edge, right at the hour I’d just logged. Still wet, sir.', 'worried'),
        c('Couldn’t another writer use that ink?', 'Plenty could. Ink don’t care whose hand holds the pen.', 'suspicious'),
        c('That’s enough about the ink.', 'Then we’re done with it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the log entry to the clock stroke.',
        bargain: c('Give me the hour in the log — I leave the rest unread.', 'Fair, sir. The entry’s dated to the chime I wrote by; ink and hour say the same thing, nothing more.', 'thoughtful'),
        challenge: c('You logged that at a minute you’re covering. Which?', 'So I keep good time, sir. A careful log’s not a guilty one.', 'angry'),
      }),
    r('chauffeur-earth', 'room', 'fine-earth', 'Where’d that pale grit on your knees come from?',
      'Under the motor, sir. Something rattled on the axle before the rain, so I went down on the drive to look.', 'neutral',
      s(
        c('What were you checking under there?', 'A loose plate throwing grit. Fine pale stuff off the gravel, drier than garden dirt.', 'thoughtful'),
        c('Why crawl under a car in a storm?', 'A rattle at speed’s a broken axle waiting to happen, sir. Rain or not, you check it.', 'neutral'),
        c('That grit looks indoors, not from a drive.', 'Think what you like. I went under the car, I came out gritty. That’s the run.', 'neutral'),
      ),
      s(
        c('Where did the grit end up?', 'Knees, cuffs, the tin I set down. Paler and finer than soil, if you look close, sir.', 'worried'),
        c('Couldn’t it match the conservatory dust?', 'Close, not the same. Drive grit’s got sand in it; that garden stuff don’t.', 'suspicious'),
        c('The grit isn’t helping.', 'Then leave it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare his knee grit to the drive gravel and the garden dust.',
        bargain: c('Show me where you went under the motor — I won’t chase the garden.', 'This way, sir. Set my knee-grit by the drive gravel — matches. The garden stuff’s a different grain.', 'thoughtful'),
        challenge: c('That grit came from the conservatory. Your motor story won’t hold.', 'Compare it proper, sir. Drive grit’s coarse and sandy; garden dust ain’t. They won’t match.', 'angry'),
      }),
    r('chauffeur-perfume', 'social', 'floral-perfume', 'Why’s a woman’s perfume on your uniform?',
      'Off the last fare, sir. A lady rode in the back this evening; her scent soaked the seat and my collar with it.', 'neutral',
      s(
        c('Who was the passenger?', 'A guest I ran up from the station before the roads flooded. Perfume like a greenhouse, sir. It lingers.', 'thoughtful'),
        c('Do you always smell of your fares?', 'When they wear half a bottle, aye. A back seat holds a scent longer than a memory.', 'neutral'),
        c('That scent looks worn, not caught.', 'A driver in gardenia? No, sir. It came off the seat, off her, not off me.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My collar and shoulder, where I leaned back over the seat to shut her door.', 'worried'),
        c('Couldn’t you wear the scent yourself?', 'Look at me, sir. A man in oil and wool don’t buy French perfume. It isn’t mine.', 'suspicious'),
        c('That’s enough about the perfume.', 'Then let it air out, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Smell the back seat against his collar.',
        bargain: c('Name the fare and I keep it quiet.', 'Right, sir. Smell the back seat — same gardenia. It came off my passenger, never out of my pocket.', 'thoughtful'),
        challenge: c('That perfume puts you alone with a lady. Who?', 'Close enough to shut her door, sir. The scent’s on the seat and my collar, not a thing I’d ever wear.', 'angry'),
      }),
    r('chauffeur-powder', 'room', 'face-powder', 'How’d ivory face powder get on your shoulder?',
      'Same fare, sir. The lady powdered her face in the back and clouded half the cab — the footman watched her step out. Some of it landed on me.', 'neutral',
      s(
        c('Who was she, this fare?', 'The guest I drove up from the station. Ask the footman where the powder came from.', 'thoughtful'),
        c('Isn’t that just dust off your cap?', 'Cap dust’s grey, sir. This is ivory — a lady’s powder, not a driver’s.', 'neutral'),
        c('That powder looks pressed on.', 'It settled off her puff in my cab. Read it how you want; that’s the truth of it.', 'neutral'),
      ),
      s(
        c('Where did the powder land?', 'My right shoulder, where I turned to answer her. The footman watched the whole handover.', 'worried'),
        c('Couldn’t several women wear that shade?', 'Maybe, sir. Only one was powdering her face in my back seat tonight.', 'suspicious'),
        c('That’s enough about the powder.', 'Then we’re done, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the footman who saw the fare.',
        bargain: c('Confirm the fare and I leave her name out of it.', 'Fair, sir. The footman’ll place her in my cab; the powder’s off her puff, not my hand.', 'thoughtful'),
        challenge: c('That powder puts you near a lady you won’t name. Who?', 'Near a fare in my own cab, sir, with the footman watching. That’s a job, not a crime.', 'angry'),
      }),
    r('chauffeur-oil', 'timeline', 'blade-oil', 'Why are your hands slick with fine oil?',
      'The motor, sir. Out in the garage I oiled a sticky throttle linkage so she’d turn over if the road ever cleared. Light oil, precision stuff.', 'neutral',
      s(
        c('What exactly did you oil?', 'The linkage and a stiff door hinge while I had the can out. A drop does the throttle, a drop does the hinge.', 'thoughtful'),
        c('Why bother if nobody’s leaving?', 'A driver keeps his motor ready, sir. That’s the whole job, flood or no flood.', 'neutral'),
        c('That oil went where it shouldn’t.', 'It went where I put it, sir. I don’t answer for where you think it went.', 'neutral'),
      ),
      s(
        c('Where did the oil travel?', 'Can to my thumb to the rag in my back pocket. One trail, all garage, sir.', 'worried'),
        c('Couldn’t that oil come from a clock or blade?', 'Same light oil, different machine. Follow where it’s been, not what it looks like.', 'suspicious'),
        c('The oil’s meaningless.', 'Then drop it, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the oil from the motor can to his rag.',
        bargain: c('Show me the garage trail and I leave the house oil alone.', 'This way, sir — can, thumb, rag, linkage. One trail, all mine, and none of it near the house.', 'thoughtful'),
        challenge: c('That oil touched something delicate upstairs. What did you free?', 'To my own motor, sir. Follow the trail from the garage can; it don’t reach where you’re pointing.', 'angry'),
      }),
    r('chauffeur-wax', 'social', 'wax-resin', 'Why’s there an amber fleck of wax on your cuff?',
      'A parcel, sir. I was asked to run it out when the roads clear, sealed with wax so nobody opens it on the way. Stick cracked as I pressed it.', 'suspicious',
      s(
        c('What’s in the parcel?', 'Not my business, sir. A driver carries; he doesn’t unwrap. The seal’s the whole point.', 'thoughtful'),
        c('Who asked you to seal it?', 'A guest who paid in advance and asked no questions be asked back. Common enough in my line.', 'neutral'),
        c('That’s no ordinary delivery seal.', 'It’s a parcel seal, sir. Believe it or don’t; the parcel stays shut and so do I.', 'neutral'),
      ),
      s(
        c('How’d the wax get on your cuff?', 'Snapped off the stick when I pressed the knot. Warm fleck, straight onto the cuff, sir.', 'worried'),
        c('Couldn’t that be an antiquarian’s resin?', 'Looks close. Mine’s off a sealing stick, not some relic. Test it.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then leave it be, sir.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him seal the parcel again and show how the fleck lands.',
        bargain: c('Show me how you sealed it and I leave the parcel unread.', 'Right, sir. I press the knot here, the stick cracks there, the fleck hits my cuff. No mystery, just a job.', 'thoughtful'),
        challenge: c('That wax sealed something you won’t show me. What was in the parcel?', 'To a parcel I was paid to carry, sir. Watch me seal another; the wax breaks the same, proves nothing worse.', 'angry'),
      }),
    r('chauffeur-note', 'timeline', 'torn-note', 'What are those cramped little marks you keep folding away?',
      'Fares and addresses, sir. My own shorthand — pickup, drop, time. I tear off each run once it’s done.', 'suspicious',
      s(
        c('What was on tonight’s note?', 'A time and a spot to wait. Somebody wanted a car ready at an hour, sir. That’s all it says.', 'thoughtful'),
        c('Can anyone else read your shorthand?', 'Another driver, maybe. To the rest it’s scratches and mud.', 'neutral'),
        c('Those aren’t fares. Hand it over.', 'A driver’s notes stay with the driver, sir. Torn and done.', 'neutral'),
      ),
      s(
        c('What happened to the torn scrap?', 'Slipped out of my glove getting out of the cab. Hand to ground, I couldn’t tell you where, sir.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious man, sir, a pickup time looks like a plot.', 'thoughtful'),
        c('I’ll ask whoever booked the car.', 'Do, sir. They’ll say the same hour my note does.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read the pickup time wrong and let him correct it.',
        bargain: c('Read me the run plainly — I leave the fare unnamed.', 'Fair, sir — but your hour’s wrong; it’s a quarter later. Fix it and you’ll see it’s just a pickup.', 'thoughtful'),
        challenge: c('This note reads like a getaway plan. What are you covering?', 'You’ve got the hour wrong, sir. Fix the time and your “plan” is a fare waiting for a car.', 'angry'),
      }),
    r('chauffeur-standing', 'connection', undefined, 'What’s it like, being ignored in a room like this?',
      'Restful, mostly, sir. People say things in front of a driver they’d never say to a guest. I hear a lot by being furniture.', 'thoughtful',
      s(
        c('How did you end up driving?', 'War took the job I trained for. A motor’s honest work, and it don’t ask where a man went to school.', 'thoughtful'),
        c('Does it bother you, being looked through?', 'Some. A man likes to be counted now and then. But the wage clears.', 'neutral'),
        c('I have other questions.', 'Course, sir.', 'neutral'),
      ),
      s(
        c('What do you want tonight?', 'To be heard as a witness, sir — not written off as the help. I saw things worth saying.', 'worried'),
        c('What won’t you do?', 'Take the fall because it’s tidy for the gentry. Done that once. Not again.', 'suspicious'),
        c('We’re done here.', 'Right, sir.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what do you want from me?', 'To be believed. Give a working man that, and I’ll tell you every road I drove tonight.', 'thoughtful'),
        challenge: c('What are you hiding?', 'A fare I was paid to keep quiet — not a crime.', 'angry'),
      }),
    r('chauffeur-fares', 'intel', undefined, 'You’ve driven half these guests — what do you make of them?',
      'You learn a person quick from the back seat, sir. Where they’re soft, where they lie, what they tip when they’re scared.', 'suspicious',
      s(
        c('Who rode strangely tonight?', 'One guest kept looking behind us the whole way up. People do that when they’re running from something.', 'thoughtful'),
        c('You judge people by how they tip?', 'It don’t lie, sir. Manners in a cab are manners with nobody watching.', 'neutral'),
        c('I need a name.', 'Then I’m poor company, sir.', 'neutral'),
      ),
      s(
        c('What would you trust as a real sign?', 'A tip too big, sir. Guilty hands pay heavy.', 'thoughtful'),
        c('Couldn’t that just be nerves?', 'Could, sir. I give you what I saw, not the verdict.', 'suspicious'),
        c('That’s enough.', 'Then we’re parked, sir.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who should I watch?', 'The one who watched the road behind us and overpaid at the door. Fear and money together.', 'thoughtful'),
        challenge: c('Whose secret are you keeping?', 'A paid fare’s — not a culprit’s.', 'angry'),
      }),
  ],

  debutante: [
    r('debutante-earth', 'room', 'fine-earth', 'There’s pale grit caught in your slipper. Where did that come from?',
      'The conservatory, I’m afraid. A spilled pot poured powdery grit straight into my slipper as I passed through.', 'neutral',
      s(
        c('What did it do to your shoes?', 'Ruined them. A whole slipper of pale, powdery grit from that toppled pot.', 'surprised'),
        c('Were you hiding from someone?', 'I prefer “avoiding a tedious conversation.” Much prettier.', 'suspicious'),
        c('You didn’t go in there just for the flowers. What were you doing?', 'Oh good. My shoes have suffered quite enough.', 'neutral'),
      ),
      s(
        c('What did you notice while you were in there?', 'A repaired left heel, clicking oddly, all the way to that crooked panel. I followed the sound.', 'thoughtful'),
        c('Couldn’t it be dust from an old vase?', 'Perhaps. This house sheds nearly as much as its guests.', 'neutral'),
        c('The dirt is unhelpful.', 'Then let’s not dig any deeper.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Retrace the odd heel from the grit to the panel.',
        bargain: c('Tell me what you saw in there — off the record.', 'Gladly. The grit fell here, an odd repaired heel clicked there — and both end at that crooked panel.', 'thoughtful'),
        challenge: c('That grit puts you at more than flowers. What were you following?', 'It ties me behind someone else’s repaired heel. I followed the mess; I didn’t make it.', 'angry'),
      }),
    r('debutante-perfume', 'social', 'floral-perfume', 'That gardenia scent is awfully strong on you. Where’s it from?',
      'My own atomizer, mostly — but a friend’s gardenia refill made it far stronger than I meant, and it drenched my scarf.', 'neutral',
      s(
        c('Why so overpowering?', 'Someone had emptied half the bulb. It soaked my scarf on the vanity.', 'surprised'),
        c('Was it expensive?', 'Expensive enough to pretend the spill was intentional.', 'neutral'),
        c('Your scent walked a hall without you. How?', 'Already hidden. This topic too.', 'neutral'),
      ),
      s(
        c('Where were you while your scent was on the move?', 'At the card table, before witnesses — while my perfume wandered a hall without me.', 'worried'),
        c('Couldn’t another guest wear gardenia?', 'Of course. Taste is not exclusive, sadly.', 'neutral'),
        c('That’s enough about the scent.', 'Then we can stop discussing it.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Set the scented hall against the card table that kept her seated.',
        bargain: c('Help me prove where you sat — I won’t spoil the card table.', 'Please do. Three players will swear I never left the table while my perfume took its little stroll.', 'thoughtful'),
        challenge: c('Your perfume walked that corridor — and so did you. Own it.', 'My perfume did. I was losing at cards in plain view — the score sheet says so.', 'angry'),
      }),
    r('debutante-powder', 'timeline', 'face-powder', 'There’s ivory powder spilled across your collar and bag. What’s that from?',
      'My compact slipped while I fixed my face and simply exploded. Ivory across my collar, my bag, the little table by the mirror.', 'surprised',
      s(
        c('Where did the worst of it go?', 'Across my collar, my bag, and the table by the mirror. It went everywhere.', 'worried'),
        c('Why fix your face so often?', 'Because people ask questions like that.', 'angry'),
        c('Powder doesn’t climb onto brass by itself. What happened next?', 'Snapped shut. So is the subject.', 'neutral'),
      ),
      s(
        c('Did anything press through that spilled powder?', 'A gloved hand swept it aside and left its seams printed on the brass latch.', 'thoughtful'),
        c('Couldn’t that be theatrical makeup?', 'It could. Mine has a nicer case.', 'neutral'),
        c('I’ve heard enough about cosmetics.', 'Thank heavens. Nothing more there.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the glove seams in the latch powder to her vanity lining.',
        bargain: c('Show me where that powder was pressed — quietly.', 'Then look closely — the glove seams in that powder aren’t mine, but they pressed my vanity lining too.', 'thoughtful'),
        challenge: c('That powder ended up where a hand went searching. Yours?', 'A gloved hand searched, and wore my powder off. The seams in it are a stranger’s.', 'suspicious'),
      }),
    r('debutante-glance', 'intel', undefined, 'What have you noticed that other people missed?',
      'That two guests swapped keys under the card table while explaining the rules to me.', 'suspicious',
      s(
        c('What did the keys look like?', 'One long and brass, one small and silver. Only the brass one changed hands.', 'thoughtful'),
        c('Were you paying attention to the cards?', 'I was paying attention to everything. That’s the point.', 'neutral'),
        c('Which two, and which key?', 'If you insist. I fold.', 'neutral'),
      ),
      s(
        c('Where did the brass key go?', 'Into a left coat pocket, just before its new owner left the room alone.', 'thoughtful'),
        c('Couldn’t it have been a coin?', 'Coins don’t have teeth. Even I know that.', 'angry'),
        c('That exchange is none of my concern.', 'Then we’ve nothing else to discuss.', 'neutral'),
      )),
    r('debutante-ink', 'timeline', 'ink-fiber', 'How did blue-black ink get on your fingers?',
      'I was writing in my little book by the clock. Everyone thinks I doodle hearts — I was noting the time, actually.', 'neutral',
      s(
        c('When exactly were you writing?', 'Right as the clock struck, silly — I remember because I dated the page. I do date my pages.', 'thoughtful'),
        c('What could you possibly be noting?', 'Oh, this and that. A figure, an hour. A girl’s allowed a diary, isn’t she?', 'neutral'),
        c('That’s far more ink than a diary needs.', 'My pen simply burst. That’s all it is. Do let’s talk of something prettier.', 'neutral'),
      ),
      s(
        c('Where did the ink end up?', 'My fingers and the page corner, right at the hour I’d written down. It quite ruined my glove.', 'worried'),
        c('Couldn’t anyone else use that ink?', 'Heaps of people, I should think. Ink isn’t exactly a signature.', 'suspicious'),
        c('That’s enough about the ink.', 'Then let it dry, and me be.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Pin the dated page to the clock stroke.',
        bargain: c('Show me the hour on the page — I leave the rest unread.', 'How kind. The page is dated to the very chime — the ink and the hour agree, and neither of them accuses poor me.', 'thoughtful'),
        challenge: c('You dated that page to cover a minute you can’t account for.', 'So I keep careful time, detective. A girl who can read a clock isn’t a girl with a plot.', 'suspicious'),
      }),
    r('debutante-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply medicinal?',
      'Varnish remover, detective. I redid my nails before dinner. It reeks like a hospital, but it’s pure vanity, I promise.', 'neutral',
      s(
        c('What were you removing, exactly?', 'A chipped polish. One does not appear at dinner with a ruined manicure; there are standards, even in a storm.', 'thoughtful'),
        c('Why should I think it isn’t the real thing?', 'Because a surgeon’s carbolic and my remover only smell alike, silly. One mends nails; one mends people.', 'neutral'),
        c('That’s a doctor’s antiseptic.', 'It’s acetone, from my vanity case. Believe your nose if you must; I’m quite finished.', 'neutral'),
      ),
      s(
        c('Where did the remover touch you?', 'My fingertips and a cotton pad — and my cuff, where I was careless. It clings like the surgeon’s, but it isn’t.', 'worried'),
        c('Couldn’t it be surgical antiseptic?', 'Only to a hurried nose. Sniff it properly and it’s pear-drops, not medicine.', 'suspicious'),
        c('That’s enough about the smell.', 'Then do stop sniffing my hands, detective.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid is nail remover, not carbolic.',
        bargain: c('Let me test it — I won’t call it a surgeon’s.', 'How gallant. Test it — acetone, not carbolic. They share a sting and absolutely nothing else.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve. Explain it.', 'Smell again, detective. Mine takes off polish; his takes off infection. A shared reek isn’t a shared hand.', 'suspicious'),
      }),
    r('debutante-wool', 'social', 'black-wool', 'Where did those black threads on your shoulders come from?',
      'A gentleman lent me his coat when I got cold on the terrace. Terribly gallant, terribly scratchy — it shed everywhere.', 'neutral',
      s(
        c('Which gentleman lent it?', 'One who wanted to seem heroic, I expect. The wool snagged on my bracelet the moment he draped it.', 'thoughtful'),
        c('Do you often borrow men’s coats?', 'When they insist and the terrace is freezing, why not? It’s practically a public service.', 'neutral'),
        c('That thread is coarser than any dinner jacket.', 'Then it’s his outdoor coat, not his dinner one — do keep up. The coat went back; we’re finished.', 'neutral'),
      ),
      s(
        c('Where did the thread come loose?', 'At my bracelet clasp and my shoulder, where the collar sat. It followed me back inside, the beastly thing.', 'worried'),
        c('Couldn’t the thread be your own wrap?', 'My wrap is silk, detective. That coarse black strand is his gallantry, not mine.', 'suspicious'),
        c('The thread isn’t enough.', 'Then do let go of it, please.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Follow the thread from the borrowed coat to her bracelet.',
        bargain: c('Point me to the coat and I keep the man’s name out of it.', 'How considerate. Coat to bracelet to shoulder — the whole gallant little journey, and nothing wicked on it.', 'thoughtful'),
        challenge: c('That thread puts a man’s coat on you for more than warmth. Whose?', 'On me, detective, not the other way about. Borrowing a coat isn’t a crime, however scratchy.', 'suspicious'),
      }),
    r('debutante-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'My little silver hand-mirror had gone dreadfully dull, so I buffed it before dinner. Vanity is such hard work.', 'neutral',
      s(
        c('What exactly did you polish?', 'The mirror’s back and my compact’s clasp. Both had tarnished in this dreadful damp house.', 'thoughtful'),
        c('Do you polish your own silver?', 'When the staff are run off their feet, yes. I’m more capable than I look, detective — most people are.', 'neutral'),
        c('What else did you buff?', 'A lady never lists her fingerprints. Do let’s move on.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the mirror’s back — just where one holds it up to the light.', 'worried'),
        c('Couldn’t that smear be from the big silver?', 'It’s the same waxy stuff, I suppose. Only where it’s been could tell you which.', 'thoughtful'),
        c('That’s enough about the polish.', 'Then do let it tarnish in peace.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell her she polished the mirror’s handle — see if she corrects you.',
        bargain: c('Help me quietly and I keep your name out of it.', 'How sweet. I only did the back and the clasp, never the handle — whoever touched the big silver was far less tidy than me.', 'thoughtful'),
        challenge: c('That polish matches the dining-room silver. You handled more than a mirror.', 'I shined a hand-mirror, detective. Follow the smear to my vanity, not to a platter I never lifted.', 'suspicious'),
      }),
    r('debutante-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine oil?',
      'My music box jammed mid-waltz — so vexing. A drop of oil on the little movement and it played again. I’m quite the mechanic, really.', 'surprised',
      s(
        c('What did you oil, exactly?', 'The comb and the cylinder, where it had seized. One drop, no more; the movement is dreadfully delicate.', 'thoughtful'),
        c('Where would a girl learn to oil a movement?', 'From taking things apart when the grown-ups thought I was napping. I was a frightful child, detective.', 'neutral'),
        c('That oil went somewhere it shouldn’t.', 'It went on my music box, silly. I shan’t apologise for mending my own things.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'My thumb and cuff when the cylinder sprang free. It marks whatever I touch afterward, annoyingly.', 'worried'),
        c('Couldn’t that oil be from a lock or a clock?', 'The very same little oil, I expect. All the delicate things drink it.', 'suspicious'),
        c('That’s enough about the oil.', 'Then let it dry, do.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have her free the music box again and show where the oil went.',
        bargain: c('Show me how the box freed and I leave the comb alone.', 'Watch, then — I oil the comb here, the cylinder springs there, and the oil catches my thumb. No mystery, just a stubborn waltz.', 'thoughtful'),
        challenge: c('That oil touched more than a music box. What else did you free?', 'A music box, detective. Watch me mend it; the oil falls exactly where a clever girl would leave it.', 'suspicious'),
      }),
    r('debutante-wax', 'social', 'wax-resin', 'Why is there an amber fleck of wax on your glove?',
      'I sealed a letter with wax — a private one. Everyone reads a girl’s post if she lets them, so I don’t let them.', 'suspicious',
      s(
        c('Who was the letter for?', 'A friend who’ll tell you the very same, if you ask nicely. The seal keeps it mine until she opens it.', 'thoughtful'),
        c('Do girls still bother with sealing wax?', 'The careful ones do. A licked envelope can be steamed; hot wax leaves a scar if anyone tries.', 'neutral'),
        c('That’s no ordinary letter wax.', 'It’s perfectly ordinary, detective — I simply have secrets, like everyone. The letter stays sealed.', 'neutral'),
      ),
      s(
        c('How did the wax reach your glove?', 'It snapped off the stick as I pressed the seal; a warm fleck caught my glove. My friend has the matching half.', 'worried'),
        c('Couldn’t that fleck be an antiquarian’s resin?', 'To a careless eye, perhaps. Mine came off a sealing stick — ask the friend who holds the letter.', 'thoughtful'),
        c('That’s enough about the wax.', 'Then do stop peering at my glove.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Ask the friend who holds the matching letter.',
        bargain: c('Name who has the letter — I keep it quiet.', 'How decent. My friend holds it; her seal is twin to the fleck on my glove. Ask her and it all agrees.', 'thoughtful'),
        challenge: c('That wax sealed something you won’t show me. What was in the letter?', 'To a letter, detective. Ask my friend; her half matches mine. A sealed secret isn’t a sealed guilt.', 'suspicious'),
      }),
    r('debutante-note', 'timeline', 'torn-note', 'What are those cramped little marks you keep hiding?',
      'Card scores, detective. I keep a running tally — who owes what, who cheats — and tear off each sheet once it’s done. My hand’s dreadful, so it looks like scribbles.', 'suspicious',
      s(
        c('What was on tonight’s tally?', 'Names, hands, a running total. Everyone thinks I lose at cards; I keep better books than they know.', 'thoughtful'),
        c('Can anyone else read your marks?', 'Hardly. I made the shorthand up myself so nosy people can’t. Present company included.', 'neutral'),
        c('Those aren’t card scores. Hand them over.', 'A girl’s tally is a girl’s business. I tore that sheet ages ago.', 'neutral'),
      ),
      s(
        c('What happened to the torn sheet?', 'It slipped from my little bag between hands. From my lap to the floor, I couldn’t say where it went.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious mind, a card score looks like a conspiracy. Yours seems the suspicious sort.', 'thoughtful'),
        c('I’ll compare it to the card table myself.', 'Do. You’ll find it matches the score sheet exactly, detective.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match her shorthand to the card table’s score sheet.',
        bargain: c('Let me match it to the scores — I leave the table alone.', 'How gallant. Lay my marks beside the table’s score sheet; they’re the same hand, the same night — nothing hidden.', 'thoughtful'),
        challenge: c('That note reads like a scheme. What are you really tallying?', 'Compare it to the card scores, detective. It matches them exactly. A tally isn’t a plot.', 'suspicious'),
      }),
    r('debutante-underestimated', 'connection', undefined, 'People underestimate you, don’t they?',
      'Marvellously useful. People say anything in front of a girl they think can’t count. I can count beautifully.', 'thoughtful',
      s(
        c('When did you learn to use that?', 'The first time a grown man discussed money over my head as if I were a lamp. I’ve been listening ever since.', 'thoughtful'),
        c('Doesn’t it hurt, being dismissed?', 'It did once. Now it’s useful. Let them think me silly — silly girls hear the most.', 'neutral'),
        c('I have real questions.', 'Everyone wants the real me eventually.', 'neutral'),
      ),
      s(
        c('What are you fighting for?', 'My own money, and the right to say what I saw without a guardian deciding it for me.', 'worried'),
        c('What will you never allow?', 'To be handed off, hushed up, and filed away. Not again.', 'suspicious'),
        c('We are finished here.', 'Are we? How you all love ending things for me.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what do you want tonight?', 'Control. Of my accounts, my accusation, my future. Give me that and I’ll give you the truth I’ve been counting.', 'thoughtful'),
        challenge: c('What are you hiding under all this?', 'Papers — not a crime. Protecting my own evidence isn’t guilt.', 'suspicious'),
      }),
    r('debutante-watchers', 'intel', undefined, 'What have you seen tonight?',
      'Almost everything. When people believe you’re decorative, they stop performing. That’s when they get interesting.', 'suspicious',
      s(
        c('Who forgot you were watching?', 'One guest counted the exits every time the thunder hid it. People only map escapes when they mean to use one.', 'thoughtful'),
        c('Do you watch everyone?', 'I notice things. Spying sounds so grubby.', 'neutral'),
        c('I need a name.', 'Then you’ll find me disappointing tonight.', 'neutral'),
      ),
      s(
        c('What would you swear to?', 'A whispered figure changing hands under the card table. I was dealt in; I saw the whole trade.', 'thoughtful'),
        c('Could you have misread it?', 'I might. I give you what I saw, not what it means.', 'suspicious'),
        c('That’s enough.', 'Pity. I was rather enjoying being asked.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who should I watch?', 'The one who counts the doors. Nervous people fidget; that one was planning.', 'thoughtful'),
        challenge: c('Who are you protecting?', 'Myself, and my own papers.', 'suspicious'),
      }),
  ],
}
