// Pack B — Stage Magician, War Correspondent, Estate Accountant.
// Owned by the key/route & paper/payments writers' room.
import type { ArchetypeId } from '../types'
import { c, r, s, type AuthoredDialogueRoute } from './types'

export const PACK_B: Record<Extract<ArchetypeId, 'magician' | 'correspondent' | 'accountant'>, AuthoredDialogueRoute[]> = {
  magician: [
    r('magician-wool', 'room', 'black-wool', 'Is that your performance coat?',
      'The very one. It’s survived trapdoors, doves, and one nasty cabinet latch tonight.', 'neutral',
      s(
        c('Which latch did it catch on?', 'A brass tooth in the west passage. The hidden pocket snagged and the weave started to give.', 'worried'),
        c('What do you keep in that hidden pocket?', 'A magician’s pocket holds disappointment and a contract or two.', 'suspicious'),
        c('No more patter. What did that cabinet cost your coat?', 'A thread and a good exit. We’ll leave the coat closed.', 'neutral'),
      ),
      s(
        c('Where exactly did the thread pull free?', 'As I stepped clear, a short dark strand stayed hooked on the tooth behind me.', 'thoughtful'),
        c('Could another black coat leave that thread?', 'Certainly. Black wool is far less exclusive than my billing.', 'neutral'),
        c('The coat proves nothing on its own.', 'No — and that’s where we’ll stop.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the snagged strand from the cabinet latch to his tailor’s repair ticket.',
        bargain: c('Off the record — what were you fetching from that cabinet?', 'Between us: a paper that ought to bear another man’s name. The coat caught as I reached for it.', 'worried'),
        challenge: c('The west cabinet was sealed. You were inside it.', 'You have me at the door, not at any crime. I went for a contract, not for a soul.', 'angry'),
      }),
    r('magician-powder', 'social', 'face-powder', 'Why were you at the mirror before dinner?',
      'Rehearsing an illusion. A pale face floats beautifully once the room goes dark.', 'surprised',
      s(
        c('How did you prepare the effect?', 'Ivory stage powder, a puff, and a compact that chose tonight to crack.', 'thoughtful'),
        c('Did the rehearsal have an audience?', 'Rehearsals are private. Nobody watches the seams being sewn.', 'angry'),
        c('The trick’s over. Why is your powder where you weren’t?', 'Now that’s the real question. And that’s where I stop.', 'neutral'),
      ),
      s(
        c('Where did the spilled powder settle?', 'My lapel, a lamp I’d hidden, and the little case I palm cards from.', 'worried'),
        c('Couldn’t that be ordinary face powder?', 'The powder could pass. The skill behind it couldn’t.', 'neutral'),
        c('A cracked compact is hardly proof.', 'Then the mirror goes dark, and so does this.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the powder print on the ballroom switch to his cracked compact.',
        bargain: c('Show me the effect and I won’t make sport of it.', 'Watch the lamp, not my hands — that’s exactly where the powder gives the method away.', 'thoughtful'),
        challenge: c('That powder’s on a switch you claim you never touched.', 'A switch, a lamp — props, not proof. Ivory dust signs no confession.', 'suspicious'),
      }),
    r('magician-oil', 'timeline', 'blade-oil', 'What mechanism were you repairing tonight?',
      'A prop with a sulky spring — the Mercy Box, if you want its stage name.', 'suspicious',
      s(
        c('How did you free the spring?', 'A pin, some patience, and one drop of precision oil along the false back.', 'thoughtful'),
        c('What does the Mercy Box actually do?', 'It performs mercy. The workings are older than my name on the poster.', 'neutral'),
        c('Open the box. I want to see what you oiled.', 'Not tonight. That subject closes with the lid.', 'neutral'),
      ),
      s(
        c('Where did the extra oil end up?', 'On my thumb, then my cuff, when I reset the mechanism behind my back.', 'worried'),
        c('Wouldn’t a sewing machine use that oil?', 'And clocks, and adding machines. A crowded little alibi, detective.', 'suspicious'),
        c('The oil’s too common to matter.', 'A poor audience indeed. We’re finished.', 'angry'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Open the false back again, exactly the way he did.',
        bargain: c('Rebuild it for me and I’ll credit whoever really built it.', 'Then watch: oil here, the back lifts here. The hands are mine; the invention wasn’t.', 'thoughtful'),
        challenge: c('You oiled that false back to reach what’s hidden inside.', 'I oiled a spring. What it hides is a matter of contracts, not of guilt.', 'angry'),
      }),
    r('magician-sightline', 'intel', undefined, 'What did everyone else miss tonight?',
      'They watched the loud hand. The quiet one opened a side door while every head turned.', 'suspicious',
      s(
        c('What caused the distraction?', 'A dropped tray and three glances thrown at the noise. Textbook misdirection.', 'thoughtful'),
        c('Is every accident misdirection to you?', 'Only the useful ones.', 'neutral'),
        c('Enough misdirection. Whose quiet hand was it?', 'That’s where the trick ends.', 'neutral'),
      ),
      s(
        c('What could place that quiet hand?', 'A polished ring caught the lamp for a second beside the doorframe.', 'surprised'),
        c('Couldn’t that flash be glass?', 'Glass doesn’t curl its fingers around a handle.', 'suspicious'),
        c('A glimpse like that is too thin.', 'Then let the curtain fall.', 'neutral'),
      )),
    r('magician-ink', 'timeline', 'ink-fiber', 'Why is there blue-black ink on your fingers?',
      'A prediction trick. The volunteer names a word, I write it, and the ink’s meant to vanish. Tonight it sulked.', 'surprised',
      s(
        c('When did you perform the effect?', 'Just as the clock struck. I like to time a reveal to a chime; it steals the applause.', 'thoughtful'),
        c('What’s the trick, exactly?', 'A magician who explains it is just a man with a wet pen. Watch, don’t audit.', 'neutral'),
        c('That’s far too much ink for a card. Explain.', 'The vanishing part failed and the pen wept. That’s the whole of it.', 'neutral'),
      ),
      s(
        c('Where did the stubborn ink settle?', 'My fingers and the card’s edge, at the exact stroke I performed against.', 'worried'),
        c('Could another writer own that ink?', 'Half the house scribbles. The ink’s a common prop, not a signed confession.', 'suspicious'),
        c('The ink leads nowhere.', 'Then the curtain falls on it.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the inked card to the exact stroke of the clock he performed against.',
        bargain: c('Give me the hour of the trick and I’ll spare the method?', 'Generous. The card’s inked to the chime I played to; the hour and the stain agree, nothing more.', 'thoughtful'),
        challenge: c('You inked that card at a very telling minute. Well?', 'So my timing’s theatrical. A punctual flourish isn’t a plot.', 'angry'),
      }),
    r('magician-antiseptic', 'room', 'antiseptic', 'Why do your hands smell so sharply of medicine?',
      'Spirit-gum solvent. It lifts a false moustache and reeks like a sickroom, but it’s pure stagecraft.', 'neutral',
      s(
        c('What were you gumming and un-gumming?', 'A quick-change disguise for the second act. The solvent bites worse than the glue.', 'thoughtful'),
        c('Why should I believe it isn’t the real thing?', 'Because a surgeon’s carbolic and my solvent only share a smell, not a purpose.', 'neutral'),
        c('That smell’s a doctor’s, not a conjuror’s. Explain.', 'You trust your nose over my craft. The trick, and this, are closed.', 'neutral'),
      ),
      s(
        c('Where did the solvent touch you?', 'My fingertips and cuff, where I peeled the disguise. It dries fast and smells loud.', 'worried'),
        c('Could it be surgical antiseptic instead?', 'Only to a nose in a hurry. Test the fluid and it’ll admit it’s theatre, not medicine.', 'suspicious'),
        c('The smell tells me nothing.', 'Then stop breathing in my props.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the solvent on his cuff is stage gum-remover, not surgical carbolic.',
        bargain: c('Let me test the fluid and I keep the disguise a secret?', 'Fair trade. Test it — spirit gum, not carbolic. The smell’s the only thing they share.', 'thoughtful'),
        challenge: c('That’s a surgeon’s antiseptic on your sleeve. Well?', 'Analyse it. My solvent lifts glue; it never touched a wound. A shared reek isn’t a shared crime.', 'angry'),
      }),
    r('magician-earth', 'social', 'fine-earth', 'What’s that pale grit ground into your palms?',
      'Grip chalk, near enough — a fine powder I dust on for a clean palm and a cleaner vanish.', 'neutral',
      s(
        c('What do you use the powder for?', 'To keep a coin from betraying me with sweat. A slick palm ruins the best sleight.', 'thoughtful'),
        c('Isn’t that just garden dust?', 'It’s far finer than any flowerbed, and it’s from my own tin, not your conservatory.', 'neutral'),
        c('That grit came off a floor, not a tin. Explain.', 'You’d rewrite my act into a crawl through the dirt. I decline.', 'neutral'),
      ),
      s(
        c('Where did the powder end up?', 'My palms, my cuffs, and the little case I load coins from. It clings to everything.', 'worried'),
        c('Could it match the conservatory grit?', 'At a glance, maybe. Side by side, my chalk’s finer and paler than any soil.', 'suspicious'),
        c('The grit means nothing.', 'Then let the dust settle where it likes.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the powder in his palm to his grip tin against the conservatory dust.',
        bargain: c('Show me your tin and I’ll leave the method alone?', 'Kindly done. Set my palm beside the tin; the grip chalk matches, the garden grit doesn’t.', 'thoughtful'),
        challenge: c('That grit could put you in the conservatory. Well?', 'Compare it properly. My chalk’s even; soil isn’t. The samples will part ways.', 'angry'),
      }),
    r('magician-polish', 'room', 'metal-polish', 'Why are your hands filmed with metal polish?',
      'The linking rings have to catch the light or the illusion dies. I buff them till they almost wink at the crowd.', 'thoughtful',
      s(
        c('Which props did you polish?', 'The rings and a steel cup or two. A dull prop shows its seams; a bright one keeps my secrets.', 'suspicious'),
        c('Do you polish everything you touch?', 'Only the things that have to lie convincingly under a lamp.', 'neutral'),
        c('You buffed more than props tonight. What else?', 'A magician doesn’t catalogue his own hands. Let it go.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'To my fingers and the ring’s inner curve — right where a grip would sit.', 'worried'),
        c('Could that film be from the silver?', 'It’s a cousin to it. Only its history tells you which object it left.', 'thoughtful'),
        c('The polish is meaningless.', 'Then let it lose its shine.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he polished the ring’s outer face too, and watch him correct you.',
        bargain: c('Help me quietly and I’ll leave your method in the dark?', 'Obliging. I brighten only the inner curve I grip; whoever handled the silver was less tidy than I.', 'thoughtful'),
        challenge: c('That polish matches the silver. Well?', 'I shine props. Follow the film to my rings, not to a plate I never lifted.', 'angry'),
      }),
    r('magician-perfume', 'social', 'floral-perfume', 'Why does a lady’s perfume cling to your sleeve?',
      'The vanishing bouquet. I produce flowers, a lady takes them, and her scent stays on me after the blooms are gone.', 'neutral',
      s(
        c('Who took the bouquet from you?', 'A guest near the ballroom who played my volunteer. The whole room watched.', 'thoughtful'),
        c('Are the flowers real or an illusion?', 'Real enough to smell, false enough to vanish. The perfume, sadly, won’t obey me.', 'neutral'),
        c('That scent is worn, not brushed on. Explain.', 'You mistake stagecraft for vanity. The act’s over and so is this.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'My cuff and lapel, where she pressed the bouquet back into my hands. Witnesses aplenty.', 'thoughtful'),
        c('Couldn’t you just be wearing the scent?', 'A conjuror in gardenia? Ask the room; they saw the lady, not a bottle in my pocket.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then let it fade with the applause.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the bouquet exchange against the guests who watched it.',
        bargain: c('Name the volunteer and I keep the method quiet?', 'Fair. The volunteer and the room will confirm it — her scent came to my sleeve in full view.', 'thoughtful'),
        challenge: c('That perfume ties you to someone. Well?', 'To a volunteer, in front of an audience. Ask them. A witnessed trick isn’t a secret meeting.', 'angry'),
      }),
    r('magician-wax', 'timeline', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'A sealed prediction. I write the outcome, seal it in wax before witnesses, and open it at the finish. The stick snapped as I pressed it.', 'thoughtful',
      s(
        c('What did the prediction say?', 'That would spoil the ending. The seal matters more than the words — a broken one ruins the wonder.', 'suspicious'),
        c('Do conjurors still use sealing wax?', 'The honest ones do. A licked flap can be steamed; hot wax can’t be faked mid-trick.', 'neutral'),
        c('That’s no stage prop. Explain the wax.', 'A sealed prediction stays sealed until the reveal. The subject seals with it.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'It snapped off the warming stick as I pressed the envelope; a warm fleck flicked to my cuff.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'To a hasty eye. Mine came off a sealing stick, not a relic.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then let the envelope keep its secret.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him seal a fresh envelope and show how the fleck flies loose.',
        bargain: c('Show me how it seals and the prediction stays secret?', 'Watch: I press here, the stick cracks there, the fleck lands on my cuff. No mystery, only method.', 'thoughtful'),
        challenge: c('That wax ties you to something sealed. Well?', 'To a prediction envelope. Have me seal another; the wax breaks the same, and proves nothing worse.', 'angry'),
      }),
    r('magician-note', 'social', 'torn-note', 'What’s that torn scrap of shorthand you keep palming?',
      'A cue card. My own cramped marks — running order, a gag, the beat to drop a coin. I tore the used corner off between effects.', 'suspicious',
      s(
        c('What was written on the card?', 'The order of the act and a private note or two. Meaningless to anyone who can’t read a conjuror’s hand.', 'thoughtful'),
        c('Can anyone else read your marks?', 'A fellow performer, perhaps. To the rest it’s a hedge of scribbles.', 'neutral'),
        c('That’s no cue card. Hand it over.', 'A magician’s notes stay in a magician’s palm.', 'neutral'),
      ),
      s(
        c('What happened to the torn corner?', 'It slipped from my palm mid-flourish. From my hand to my pocket to the floor — I couldn’t swear which.', 'worried'),
        c('Could the marks pass for something sinister?', 'To a suspicious reader, anything can. That’s the trouble with reading over a shoulder.', 'thoughtful'),
        c('I’ll read it myself.', 'Then mind you don’t mistake the running order for a plot.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the torn cue card from his palm through his pocket to where it fell.',
        bargain: c('Walk me through where the card went and I keep the act secret?', 'Fair. Palm to pocket to floor — the whole clumsy trip, and nothing but a running order on it.', 'thoughtful'),
        challenge: c('That scrap ties you to a place you deny. Well?', 'A dropped cue card. Follow it from my palm; it leads to a stage, not a scheme.', 'angry'),
      }),
    r('magician-craft', 'connection', undefined, 'How does a person come to make a life out of fooling people?',
      'By learning young that the truth disappoints and a good illusion never does. I chose the kinder one.', 'thoughtful',
      s(
        c('Who taught you the trade?', 'A woman with faster hands than mine, whom the posters never bothered to name. I owe her more than a flourish.', 'worried'),
        c('Is it lonely, living behind misdirection?', 'A little. The audience loves the trick, never the man working it. You get used to the dark of the wings.', 'neutral'),
        c('Save the patter. I have questions.', 'Of course. The finale’s always the part people skip to.', 'neutral'),
      ),
      s(
        c('What would you set right if you could?', 'A name. Someone’s invention wears my billing, and that’s weighed on me longer than any secret.', 'worried'),
        c('And what will you never reveal?', 'How the trick’s done, and how much it cost the person who first dreamed it.', 'suspicious'),
        c('We’re finished here.', 'Then the house lights come up. Pity.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what do you actually want tonight?', 'Off the record: to hand back a credit I borrowed too long. A confession’s just another kind of reveal.', 'thoughtful'),
        challenge: c('All this misdirection — what are you steering me from?', 'From the method, not from any crime. Guarding a secret is my whole profession, not my guilt.', 'angry'),
      }),
    r('magician-audience', 'intel', undefined, 'You read audiences for a living — what does this one tell you?',
      'That everyone here is running an act, and most of them are under-rehearsed. I can see the wires.', 'suspicious',
      s(
        c('Whose act is slipping?', 'One guest keeps checking a pocket the way an amateur checks a hidden card. Guilt has terrible technique.', 'thoughtful'),
        c('Is everyone a performer to you?', 'Everyone in evening dress. The question is only who rehearsed their alibi and who improvised.', 'neutral'),
        c('I want names, not stage notes.', 'Then you’ll be a hard house to play tonight.', 'neutral'),
      ),
      s(
        c('What tell would you actually trust?', 'The pause before an answer. A prepared lie comes too smoothly; the truth stumbles first.', 'thoughtful'),
        c('Could you be misreading nerves?', 'Every showman can. I’m offering you the reading, not the verdict.', 'suspicious'),
        c('That’s enough theatre.', 'Then the curtain drops on it.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who’s working hardest to seem calm?', 'Quietly: the one whose hands are too still. Stillness that deliberate is a performance, and a poor one up close.', 'thoughtful'),
        challenge: c('You see everything — so whose act are you covering for?', 'I cover for no one. I guard methods, not culprits. Don’t confuse the two.', 'angry'),
      }),
  ],

  correspondent: [
    r('correspondent-ink', 'timeline', 'ink-fiber', 'Were you filing a story tonight?',
      'Drafting one. Storm, stranded guests, short tempers. Blue-black ink, worse ending pending.', 'neutral',
      s(
        c('What interrupted the draft?', 'The gallery door slammed and my pen went straight through the page.', 'suspicious'),
        c('Who’s the story about?', 'Everyone. Names wait until the facts show up.', 'neutral'),
        c('Show me that draft. What time did you write down?', 'Copy’s spiked. Topic’s closed.', 'neutral'),
      ),
      s(
        c('When exactly did the pen tear it?', 'On the slam. I’d just written the hour, and the nib buried in the crease.', 'thoughtful'),
        c('Couldn’t another writer use that ink?', 'Columnists. Accountants. Anyone with old habits.', 'neutral'),
        c('The draft leads nowhere.', 'Agreed. No more copy.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the torn crease to the moment the gallery door slammed.',
        bargain: c('Keep your source out of it and give me the hour.', 'Fair trade. The hour on that page is the one thing I’ll stand behind — the name stays mine.', 'thoughtful'),
        challenge: c('You wrote a time you shouldn’t have known yet.', 'I wrote what I heard through a door. Hearing a thing isn’t doing it.', 'angry'),
      }),
    r('correspondent-wool', 'room', 'black-wool', 'Why wear that heavy coat indoors?',
      'Field habit. Pockets where I expect them, wool built for worse weather than this.', 'neutral',
      s(
        c('Has it been damaged tonight?', 'Left sleeve caught a brass latch. An old seam opened another inch.', 'worried'),
        c('Expecting a battlefield in here?', 'I expect exits. Battlefields are optional.', 'suspicious'),
        c('You didn’t tear that coat sitting still. Where were you?', 'No. But I’ll forget you asked.', 'neutral'),
      ),
      s(
        c('Which latch caught the seam?', 'The third in the west passage — while I followed a figure whose limp quit the moment it felt unwatched.', 'thoughtful'),
        c('Couldn’t a driver’s uniform shed the same wool?', 'Same colour, similar weave. Test it.', 'neutral'),
        c('The coat leads nowhere useful.', 'Then stop pulling the thread.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Lay his coat seam against the fibre on the third latch.',
        bargain: c('Walk me through what you saw and I’ll keep it off the record.', 'Off the record: someone crossed that passage faking a limp. My coat paid the toll following them.', 'worried'),
        challenge: c('You were in the west passage. Prove you were only watching.', 'The latch marked my sleeve, not my hands. Watching a man isn’t the same as touching him.', 'angry'),
      }),
    r('correspondent-note', 'social', 'torn-note', 'Who were you interviewing in the corridor?',
      'A source. Nervous. Gave me a time, a room, and an envelope in tight shorthand.', 'suspicious',
      s(
        c('What made the source so nervous?', 'They heard the exchange and feared their initials would put them in it.', 'thoughtful'),
        c('Will you give me the source’s name?', 'No. Source protection outlives a dinner invitation.', 'angry'),
        c('Protecting a source won’t cover you. Read me the page.', 'It stays buried. We’re done.', 'neutral'),
      ),
      s(
        c('What survives on the shorthand page?', 'A time, “gallery,” an envelope — and a false limp. The initials I tore away.', 'worried'),
        c('Could your marks pass for gossip notes?', 'Easily. Meaning depends on who taught the hand.', 'neutral'),
        c('I’ll find another witness.', 'Do. This source is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Match his shorthand to the singer’s coded reply.',
        bargain: c('Protect the initials — just confirm the time and room.', 'That I can do. The hour and the gallery are solid; the name stays out of your notebook.', 'thoughtful'),
        challenge: c('You’re hiding those initials to protect yourself.', 'Believe that if you like. I burned a source once. Never again.', 'angry'),
      }),
    r('correspondent-exits', 'intel', undefined, 'You count exits. Who used them?',
      'Most drifted. One waited, checked both corridors, then moved with purpose.', 'suspicious',
      s(
        c('When did that happen?', 'Just after the clock struck. The rain covered the first few steps.', 'thoughtful'),
        c('Couldn’t they just want privacy?', 'Could. Privacy usually walks slower.', 'neutral'),
        c('You count everything. Give me the one who moved.', 'Filed and closed.', 'neutral'),
      ),
      s(
        c('What detail marks the person?', 'A limp for three steps, then none once they judged the corridor empty.', 'surprised'),
        c('Couldn’t bad shoes explain the limp?', 'Could. So could an act. Verify it yourself.', 'suspicious'),
        c('That’s too little to chase.', 'Then this dispatch ends.', 'neutral'),
      )),
    r('correspondent-antiseptic', 'room', 'antiseptic', 'Why do your hands reek of something medicinal?',
      'Field kit. Cleaned a cut the way I learned in worse places than this. Sharp stuff. Not the surgeon’s shelf.', 'neutral',
      s(
        c('What did you cut yourself on?', 'A splintered window frame while I watched the drive. Old habit — check the exits, bleed a little.', 'thoughtful'),
        c('Why carry field antiseptic to a dinner?', 'Because I’ve needed it at dinners before. Bad weekends leave marks.', 'neutral'),
        c('That’s a doctor’s antiseptic. Explain.', 'It isn’t. Same smell, different bottle. Believe your nose if you like; I’m done.', 'neutral'),
      ),
      s(
        c('Where did the antiseptic touch your clothes?', 'Cuff and knuckle. It dries loud and lingers, same as the surgeon’s — but it isn’t his.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test it. Mine’s a soldier’s bottle. The two only share a reek.', 'suspicious'),
        c('The smell leads nowhere.', 'Agreed. Spike the thread.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid on his cuff is field antiseptic, not the surgeon’s carbolic.',
        bargain: c('Let me test the bottle and I keep it out of the story?', 'Fine. Test it — field kit, not carbolic. Two things can stink alike and share nothing else.', 'thoughtful'),
        challenge: c('That’s the surgeon’s antiseptic on your sleeve. Well?', 'Analyse it. Mine came from a kit, not an operating tray. A shared smell isn’t a shared hand.', 'angry'),
      }),
    r('correspondent-earth', 'timeline', 'fine-earth', 'How did pale grit get onto your knees and cuffs?',
      'Went low by the conservatory glass to watch the drive without being seen. Old reflex. The floor was gritty.', 'neutral',
      s(
        c('What were you watching for?', 'Whoever came and went in the storm. You learn to read a doorway from the floor up.', 'thoughtful'),
        c('Do you always crawl around a party?', 'When the story’s outside and the crowd’s inside, yes. Beats asking politely.', 'neutral'),
        c('That grit’s from digging, not watching. Explain.', 'Think what you like. I knelt, I watched, I left. That’s the whole dispatch.', 'neutral'),
      ),
      s(
        c('Where did the grit end up?', 'Knees, cuffs, the sill I braced on. Pale stuff, finer than dirt. It travelled with me.', 'worried'),
        c('Could it match the conservatory soil?', 'Close, not the same. Someone tracked this in before I ever knelt in it.', 'suspicious'),
        c('The grit means nothing.', 'Then strike it.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him take the same low watch-post and show how the grit transferred.',
        bargain: c('Show me exactly where you knelt and I keep the source out?', 'Fair. I go low here, brace on the sill there — the grit lands on my knees. A watcher’s mess, nothing worse.', 'thoughtful'),
        challenge: c('That grit ties you to the conservatory. Well?', 'To a watch-post. Have me show you the crouch; it explains every grain.', 'angry'),
      }),
    r('correspondent-polish', 'room', 'metal-polish', 'Why is there metal polish on your fingers?',
      'Cleaned my lighter and flask. Bad habit in a storm — a man tends his small machines when the big story stalls.', 'neutral',
      s(
        c('What exactly did you polish?', 'The lighter’s case and the flask’s cap. Both had gone dull in my pocket. Idle hands.', 'thoughtful'),
        c('Why bother with that tonight?', 'Nerves. I clean brass when I can’t file copy. Everyone waits differently.', 'neutral'),
        c('You polished more than your own kit. What else?', 'I don’t itemise my hands for anyone. Leave it.', 'neutral'),
      ),
      s(
        c('Where did the polish transfer?', 'From the flask cap to my thumb to the rag in my pocket. One clean little chain.', 'worried'),
        c('Could that smear be from the silver?', 'Same compound, near enough. Only where it’s been tells you which.', 'thoughtful'),
        c('The polish is meaningless.', 'Then drop it.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the polish from his flask and lighter to his thumb and rag.',
        bargain: c('Walk me through your kit and I keep it out of print?', 'Fine. Cap to thumb to rag — my flask, my lighter, my chain. It doesn’t reach the plate.', 'thoughtful'),
        challenge: c('That polish matches the silver. Well?', 'Follow it from my flask, not the dining room. The chain starts in my pocket.', 'angry'),
      }),
    r('correspondent-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your coat?',
      'A source got frightened and held on a second too long before she talked. Her scent stayed. Her name won’t.', 'neutral',
      s(
        c('Who was the source?', 'Not a chance. But others saw us in the corridor. Ask them where I stood, not who I stood with.', 'thoughtful'),
        c('Do sources usually embrace you?', 'When they’re scared enough, yes. Fear makes people grab the nearest steady thing.', 'neutral'),
        c('That scent is worn, not caught. Explain.', 'It’s hers, transferred. I don’t bottle gardenia. That part of the record stays shut.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'Lapel and collar, where she leaned in. Two guests passed and saw the whole thing.', 'thoughtful'),
        c('Couldn’t you just wear it yourself?', 'A war correspondent in gardenia. Ask anyone who’s shared a foxhole with me.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then let it evaporate.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the corridor embrace against the guests who passed.',
        bargain: c('Confirm the spot and I keep your source unnamed?', 'Deal. The passers-by will place me in that corridor; the scent came off her, and her name stays mine.', 'thoughtful'),
        challenge: c('That perfume puts you close to someone. Well?', 'Close to a frightened source, in front of witnesses. Proximity isn’t a confession.', 'angry'),
      }),
    r('correspondent-powder', 'room', 'face-powder', 'How did ivory powder get onto your shoulder?',
      'Someone brushed past me in a doorway, hurrying. Left half her compact on my coat. Doorways are where people collide.', 'neutral',
      s(
        c('Who brushed past you?', 'A woman moving fast toward the hall. I felt the shove more than I saw the face.', 'thoughtful'),
        c('Isn’t that your own powder?', 'A field man in ivory powder? No. It came off someone in a hurry.', 'neutral'),
        c('That powder was pressed on. Explain.', 'It was a collision, not a cosmetic. Read it how you want; I’m finished.', 'neutral'),
      ),
      s(
        c('Where did the powder land?', 'Shoulder and upper sleeve — right where a passing arm clips you.', 'worried'),
        c('Could several women wear that shade?', 'Sure. Only one wore enough to leave it on a stranger.', 'suspicious'),
        c('The powder means nothing.', 'Then cut it.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Match the shade on his shoulder to the compact that shed it.',
        bargain: c('Point me to whose compact it is and I keep you clear?', 'Fair. Match the shade to her compact, not my face. I’ve never owned the stuff.', 'thoughtful'),
        challenge: c('That powder puts you near someone. Well?', 'Near a shoulder in a doorway. Compare the shade; it’s hers, not mine.', 'angry'),
      }),
    r('correspondent-oil', 'timeline', 'blade-oil', 'Why are your fingers slick with fine machine oil?',
      'Typewriter jammed mid-sentence. One drop on the carriage rail and it ran again. Can’t file with a stuck key.', 'neutral',
      s(
        c('When did the machine jam?', 'On the hour — I heard the clock while I was cursing the carriage. Easy time to remember.', 'thoughtful'),
        c('Why type during a storm like this?', 'Copy waits for no weather. The story was half-written and going cold.', 'neutral'),
        c('That’s more oil than a typewriter needs. Explain.', 'The bottle slipped. That’s the whole item. Move on.', 'neutral'),
      ),
      s(
        c('Where did the oil end up?', 'Fingers and cuff, right as the clock finished striking. The rail’s still slick.', 'worried'),
        c('Could that oil be from a lock or a blade?', 'Same light oil, different job. A dozen machines take it.', 'suspicious'),
        c('The oil leads nowhere.', 'Then spike it.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the oiled typewriter to the exact stroke of the clock.',
        bargain: c('Give me the hour you fixed it and I keep the draft private?', 'Fair trade. The rail was oiled on the clock’s stroke; oil and hour agree, and neither writes me guilty.', 'thoughtful'),
        challenge: c('You oiled something at a very telling minute. Well?', 'So I mend machines on the hour. Punctual maintenance isn’t a motive.', 'angry'),
      }),
    r('correspondent-wax', 'social', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'Sealed a dispatch the old way — hot wax over the flap so I’d know if anyone steamed it open. Habit from censored posts.', 'suspicious',
      s(
        c('What was in the dispatch?', 'Notes I don’t want read before I file them. The seal’s the point; the words are mine.', 'thoughtful'),
        c('Do reporters still seal with wax?', 'The ones who’ve been read over do. A wax seal can’t be faked without leaving a scar.', 'neutral'),
        c('That’s no press habit. Explain the wax.', 'Believe it or don’t. The dispatch stays sealed and so does this.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'Snapped off the stick as I pressed it. Warm fleck, straight to the cuff. Careless.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'Looks close. Mine’s off a sealing stick, not a relic. Test it.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then leave it.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he used the black wax, and watch him correct the colour.',
        bargain: c('Show me the seal and I keep the dispatch out of print?', 'Fair — and it’s amber, not black. The colour’s wrong in your note; the seal itself is plain enough.', 'thoughtful'),
        challenge: c('You sealed something with that black wax. Well?', 'Amber, not black. If you’ve got the colour wrong, mind what else you’ve assumed.', 'angry'),
      }),
    r('correspondent-beat', 'connection', undefined, 'What keeps a man on the worst assignments year after year?',
      'The idea that if someone writes it down straight, the lie can’t stand. Naive, maybe. It’s kept me moving.', 'thoughtful',
      s(
        c('What was the story that changed you?', 'One where I named a source to make the copy sing. They paid for my byline. I don’t do that anymore.', 'worried'),
        c('Do you ever want to stop?', 'Every filing day. Then something needs saying and my feet start walking. Habit outranks sense.', 'neutral'),
        c('Skip the war stories. I have questions.', 'Course you do. Everyone skips to the last line.', 'neutral'),
      ),
      s(
        c('What line won’t you cross now?', 'Burning a source. Once was enough to teach me the weight of a name.', 'worried'),
        c('And what do you still chase?', 'The version of events nobody wants filed. Usually the true one.', 'suspicious'),
        c('We’re done here.', 'Fine. Story’s spiked.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what are you protecting tonight?', 'Off the record: someone who trusted me after the last time I failed one. I don’t get to fail twice.', 'worried'),
        challenge: c('All this principle — what are you hiding behind it?', 'A source, not a crime. Guarding a name is my whole trade, not my guilt.', 'angry'),
      }),
    r('correspondent-map', 'intel', undefined, 'You map every room you enter — what does this house tell you?',
      'Too many exits, too few honest ones. And a guest list where half the alibis are load-bearing lies.', 'suspicious',
      s(
        c('Which alibi looks weakest?', 'One that’s too rehearsed. Honest people fumble the order; liars have it memorised.', 'thoughtful'),
        c('Do you distrust everyone by default?', 'I verify everyone by default. Trust’s a luxury for people with fewer datelines.', 'neutral'),
        c('I want names, not fieldcraft.', 'Names come after facts. That’s the whole job.', 'neutral'),
      ),
      s(
        c('What did the exits tell you?', 'That someone used a door twice they claim not to know. Movement leaves a trail; I count the trail.', 'thoughtful'),
        c('Could you be over-reading it?', 'Always possible. I flag it verified or not. This one’s not — yet.', 'suspicious'),
        c('That’s enough fieldwork.', 'Then the map’s filed.', 'neutral'),
      ),
      {
        bargain: c('Quietly — who moved when they shouldn’t have?', 'Quietly: one guest crossed after the clock struck, checked both corridors first. That’s not a stroll; that’s a plan.', 'thoughtful'),
        challenge: c('You track everyone — so whose trail are you hiding?', 'None. I hide a source’s name, never a movement. Learn the difference before you print it.', 'angry'),
      }),
  ],

  accountant: [
    r('accountant-ink', 'timeline', 'ink-fiber', 'What were you correcting in the estate ledger?',
      'An entry that wouldn’t balance. Posting ink makes an error look permanent.', 'angry',
      s(
        c('Why did the correction turn messy?', 'Someone startled me; the nib split and flooded the margin with blue-black.', 'suspicious'),
        c('How much money was missing?', 'A figure that’s immaterial to you and very material to the estate.', 'neutral'),
        c('That was no slip of the pen. What figure did you change?', 'Gladly. Account settled.', 'neutral'),
      ),
      s(
        c('What happened to the flooded margin?', 'I tore the soaked strip away. The altered zero underneath is still legible.', 'worried'),
        c('Couldn’t a reporter use the same ink?', 'Yes. Ink keeps no loyalty to a profession.', 'neutral'),
        c('The books can wait for morning.', 'Then this entry is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Set the altered zero against the carbon copy that can’t match it.',
        bargain: c('Initial the correction with me and I’ll note you were coerced.', 'That I can do. If the record shows the pressure I was under, I’ll sign the true figure.', 'worried'),
        challenge: c('You didn’t spill that ink. You altered that zero.', 'I posted a figure I was ordered to post. A forced hand isn’t a free one.', 'angry'),
      }),
    r('accountant-polish', 'room', 'metal-polish', 'Why were you handling the silver?',
      'Inventory. One candlestick had been moved and left badly tarnished.', 'suspicious',
      s(
        c('How did you test the tarnish?', 'A dab of waxy polish on the base — it lifted the oxide at once.', 'thoughtful'),
        c('Was the candlestick valuable?', 'Everything carries a value. That answer carries none.', 'angry'),
        c('You didn’t polish silver for inventory. What were you wiping?', 'With pleasure. Item struck from discussion.', 'neutral'),
      ),
      s(
        c('Where did you polish it, exactly?', 'Only where a hand would grip — the very places prints would sit.', 'worried'),
        c('Couldn’t that be motor-badge polish?', 'Substantially similar. The brand records might part them.', 'thoughtful'),
        c('The inventory is irrelevant.', 'Then strike it from your inquiry.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Tell him he polished the base too, and watch him correct you.',
        bargain: c('Help me quietly and your name stays off the inventory.', 'Then note this: I polished only the grip. Whoever moved it left the base untouched.', 'thoughtful'),
        challenge: c('You cleaned that candlestick to wipe a grip, not tarnish.', 'I cleaned where hands go. If that troubles you, it troubles whoever’s hands were there.', 'angry'),
      }),
    r('accountant-oil', 'social', 'blade-oil', 'Why were you repairing the adding machine?',
      'The carriage stuck mid-column. I dislike an interrupted total.', 'angry',
      s(
        c('What freed the carriage?', 'A tiny drop of machine oil along the precision rail.', 'thoughtful'),
        c('Couldn’t you add by hand?', 'I could also walk home through the flood. Neither’s sensible.', 'neutral'),
        c('Forget the machine. That oil went where it shouldn’t. Where?', 'Transaction cancelled.', 'neutral'),
      ),
      s(
        c('Where did the oil travel after?', 'The key snapped back and flicked a clear drop onto my hand and the ledger clasp.', 'worried'),
        c('Wouldn’t instrument oil look the same?', 'Likely. Composition, not appearance, answers that.', 'thoughtful'),
        c('Your total tells me nothing.', 'Then the account is closed.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the single oil drop from the machine rail to the ledger clasp.',
        bargain: c('Show me the machine and I’ll log it as routine upkeep.', 'Gladly — rail, key, clasp. The same drop touched all three, and nothing else of mine.', 'thoughtful'),
        challenge: c('That oil’s on the clasp of a ledger you say you never opened.', 'The clasp, not the crime. A careless drop isn’t a damning one.', 'angry'),
      }),
    r('accountant-ledger', 'intel', undefined, 'What in the household accounts looks unusual?',
      'A late charge posted twice, then one copy removed without proper initials.', 'suspicious',
      s(
        c('Who could alter that entry?', 'Anyone with study access, but only a few knew which book to open.', 'thoughtful'),
        c('Couldn’t it be a clerical slip?', 'Slips add ink. They don’t remove pages.', 'angry'),
        c('Stop hiding behind the books. Who pulled that page?', 'Very well. This account closes tonight.', 'neutral'),
      ),
      s(
        c('What narrows who had access?', 'The cabinet was locked before dinner and open after one guest left the study.', 'suspicious'),
        c('Are you accusing that guest?', 'I report access. Accusation is your unbalanced column.', 'neutral'),
        c('That’s enough bookkeeping.', 'Finally, a reconciled decision.', 'neutral'),
      )),
    r('accountant-antiseptic', 'room', 'antiseptic', 'Why do your hands smell sharply of chemicals?',
      'Ink eradicator. When a figure’s posted wrong, you bleach it out. It reeks like a sickroom and costs a fortune.', 'neutral',
      s(
        c('What figure were you correcting?', 'A transposed sum. The fluid lifts the error so a clean one can replace it. Tedious, necessary.', 'thoughtful'),
        c('Why keep such a chemical on you?', 'An accountant without eradicator lives with his mistakes. I prefer to erase mine.', 'neutral'),
        c('That’s a surgeon’s antiseptic. Explain.', 'It’s a clerk’s bleach. The smell’s shared; the purpose isn’t. We’re finished.', 'neutral'),
      ),
      s(
        c('Where did the eradicator touch you?', 'Fingertip and cuff, where the dropper slipped over the ledger. It dries loud, like carbolic — but it isn’t.', 'worried'),
        c('Could it be surgical carbolic instead?', 'Test the bottle. Mine dissolves ink, not infection. The two only agree on their stink.', 'suspicious'),
        c('The smell tells me nothing.', 'Then strike it from the account.', 'neutral'),
      ),
      {
        revealMechanism: 'contradiction',
        revealLabel: 'Show the fluid on his cuff dissolves ink, not the surgeon’s carbolic.',
        bargain: c('Let me test the bottle and I keep the correction quiet?', 'Reasonable. Test it — eradicator, not carbolic. A shared reek is a poor ledger entry.', 'thoughtful'),
        challenge: c('That’s the surgeon’s antiseptic on your sleeve. Well?', 'Analyse it. Mine erases figures; his cleans wounds. You’ve posted the wrong column.', 'angry'),
      }),
    r('accountant-earth', 'timeline', 'fine-earth', 'What is that pale grit dusted over your ledger and cuffs?',
      'Pounce — fine sand a clerk shakes over wet ink so a figure dries without smearing. Older than blotting paper, and cleaner.', 'neutral',
      s(
        c('When did you pounce the page?', 'After each correction tonight. The grit tells you a fresh entry was just made and dried in a hurry.', 'thoughtful'),
        c('Why use sand instead of a blotter?', 'A blotter lifts ink and can be read in a mirror. Pounce leaves no ghost of the figure. Discretion.', 'neutral'),
        c('That grit’s from a floor, not a pot. Explain.', 'It’s from a pounce-pot on my desk. Your theory needs auditing.', 'neutral'),
      ),
      s(
        c('Where did the pounce end up?', 'My cuff, the page, the desk edge. Far finer than garden grit — a lens shows even grains.', 'thoughtful'),
        c('Could it match the conservatory soil?', 'Only to a careless eye. Side by side, pounce is uniform; soil isn’t.', 'suspicious'),
        c('The grit is irrelevant.', 'Then let it settle.', 'neutral'),
      ),
      {
        revealMechanism: 'comparison',
        revealLabel: 'Compare the pounce on his cuff to the desk pot against the garden grit.',
        bargain: c('Show me the pounce-pot and I trouble you no further?', 'Efficient. Set my cuff beside the pot; the grain matches the pounce, not the flowerbeds.', 'thoughtful'),
        challenge: c('That grit could put you in the conservatory. Well?', 'Compare the grains properly. Pounce is milled; soil is chance. They won’t reconcile.', 'angry'),
      }),
    r('accountant-wool', 'social', 'black-wool', 'Where did that frayed black wool come from?',
      'My suit. Dark, serviceable, worn at the elbow from leaning over ledgers. It catches on rough cabinetry.', 'neutral',
      s(
        c('What did the suit catch on?', 'The cellar cabinet where the estate books are kept. A splintered edge took a thread as I reached in.', 'thoughtful'),
        c('Why were you at the cellar cabinet?', 'That’s where the accounts live. A man doesn’t audit from an armchair.', 'neutral'),
        c('That thread’s coarser than a suit. Explain.', 'You haven’t examined my suit, so you can’t say. I decline the assumption.', 'neutral'),
      ),
      s(
        c('Where did the thread travel after?', 'Cabinet edge to elbow to the ledger I carried out. A plain, itemised trail.', 'worried'),
        c('Could the thread be another dark coat?', 'It could. Coarse black wool is common enough to implicate half the staff.', 'suspicious'),
        c('The thread proves nothing.', 'A rare balanced conclusion.', 'neutral'),
      ),
      {
        revealMechanism: 'custody',
        revealLabel: 'Trace the thread from the cellar cabinet to his elbow and the ledger.',
        bargain: c('Walk me through the trail and I keep the books out of it?', 'Fair. Cabinet to elbow to ledger — the whole chain, and nothing on it but bookkeeping.', 'thoughtful'),
        challenge: c('That thread puts you at the cellar cabinet. Well?', 'Where the accounts are kept. Reaching for a ledger isn’t a plot.', 'angry'),
      }),
    r('accountant-perfume', 'social', 'floral-perfume', 'Why does a woman’s perfume cling to your sleeve?',
      'A guest leaned over my shoulder to argue about a figure and left her scent on my coat. Interruptions have a smell now, apparently.', 'suspicious',
      s(
        c('Who leaned over you?', 'A woman disputing an entry in the study. Two others were there; ask them where I sat.', 'thoughtful'),
        c('Do people often read over your shoulder?', 'When money’s involved, constantly. Everyone’s an auditor of their own account.', 'neutral'),
        c('That scent is worn, not caught. Explain.', 'It transferred from her sleeve to mine. I don’t wear gardenia. The matter closes.', 'neutral'),
      ),
      s(
        c('Where did the perfume settle?', 'Shoulder and collar, where she bent over the page. The others saw the whole quarrel.', 'thoughtful'),
        c('Could you wear the scent yourself?', 'An estate accountant in perfume. Ask anyone who’s shared an office with me.', 'suspicious'),
        c('The perfume tells me nothing.', 'Then write it off.', 'neutral'),
      ),
      {
        revealMechanism: 'corroboration',
        revealLabel: 'Confirm the study quarrel against the guests who witnessed it.',
        bargain: c('Confirm where you sat and I keep her name off the page?', 'Acceptable. The witnesses place me at the desk; her scent came over my shoulder, not from any bottle of mine.', 'thoughtful'),
        challenge: c('That perfume puts you close to someone. Well?', 'Close enough to be scolded over a figure, in front of witnesses. Proximity balances no ledger of guilt.', 'angry'),
      }),
    r('accountant-powder', 'timeline', 'face-powder', 'How did ivory face powder get onto your ledger and cuff?',
      'The same woman who quarrelled over the figure set her compact on my desk. When she snatched it back, it burst.', 'surprised',
      s(
        c('What happened to the compact?', 'She slapped it down to make a point, then grabbed it too fast. The lid sprang and dusted the page and my cuff.', 'thoughtful'),
        c('Why should I believe it was hers?', 'Because I keep pounce and ink on that desk, not cosmetics. The powder’s plainly a lady’s.', 'neutral'),
        c('That powder was applied, not spilled. Explain.', 'You’re building a fiction from a smear. I won’t endorse it.', 'neutral'),
      ),
      s(
        c('Show me how the compact burst?', 'She sets it here, snatches there, the lid snaps back, and the puff scatters across the ledger. Simple mechanics.', 'worried'),
        c('Could the powder be your own?', 'I balance books, not my complexion. It isn’t mine.', 'suspicious'),
        c('The powder means nothing.', 'Then keep it out of your figures.', 'neutral'),
      ),
      {
        revealMechanism: 'reconstruction',
        revealLabel: 'Have him reconstruct the snatched compact that dusted the ledger.',
        bargain: c('Show me exactly how it spilled and I keep her name out?', 'Gladly. Set here, snatched there, the lid bursts — the powder writes the whole quarrel across my page.', 'thoughtful'),
        challenge: c('That powder ties you to something. Well?', 'Then have me show you the spill. The sequence posts the blame to her clasp, not my hand.', 'angry'),
      }),
    r('accountant-wax', 'room', 'wax-resin', 'Why is there an amber fleck of wax on your cuff?',
      'I sealed an envelope of accounts. Wax over the flap, dated and pressed, so any tampering shows. The stick cracked as I stamped it.', 'thoughtful',
      s(
        c('When did you seal the envelope?', 'On the hour — I stamp the seal and note the time together, so the record and the wax agree.', 'thoughtful'),
        c('Why seal accounts at a party?', 'Because figures don’t keep office hours, and neither, apparently, do the people they implicate.', 'suspicious'),
        c('That’s no office seal. Explain the wax.', 'A sealed account stays sealed until it’s called for. So does this subject.', 'neutral'),
      ),
      s(
        c('How did the wax reach your cuff?', 'It snapped off the stick as I pressed the stamp, right as the clock struck. A fleck caught my cuff.', 'worried'),
        c('Could that fleck be an antique dealer’s resin?', 'To an untrained eye. Mine came off a sealing stick and carries the hour I used it.', 'thoughtful'),
        c('The wax is irrelevant.', 'Then let the seal keep its date.', 'neutral'),
      ),
      {
        revealMechanism: 'chronology',
        revealLabel: 'Fix the dated seal against the exact stroke of the clock.',
        bargain: c('Give me the hour on the seal and the accounts stay sealed?', 'Fair. The seal carries the time I stamped it; wax and clock agree, and neither posts me guilty.', 'thoughtful'),
        challenge: c('You sealed that envelope at a telling minute. Well?', 'So I date my seals precisely. A punctual stamp isn’t a confession.', 'angry'),
      }),
    r('accountant-note', 'suspicion', 'torn-note', 'What were you jotting in that cramped shorthand?',
      'Running figures. A private tally in my own marks — sums, initials, a running balance. I tore the finished strip off out of habit.', 'thoughtful',
      s(
        c('What did the tally record?', 'A discrepancy I was chasing across two books. Numbers, not names — though the numbers point somewhere.', 'suspicious'),
        c('Can anyone else read your marks?', 'A trained bookkeeper, perhaps. To most it reads as a fence of scratches.', 'neutral'),
        c('That’s no ledger note. Hand it over.', 'A private tally stays private. The strip’s torn and the topic with it.', 'neutral'),
      ),
      s(
        c('What happened to the torn strip?', 'It left my folio when I stood; desk to floor, I didn’t track it. Careless of me.', 'worried'),
        c('Could the marks pass for something else?', 'To a suspicious reader, any figure looks like a motive.', 'thoughtful'),
        c('I’ll read it myself.', 'Then mind you don’t misread a subtotal for a threat.', 'neutral'),
      ),
      {
        revealMechanism: 'bait',
        revealLabel: 'Read the total back wrong, and let him correct the figure.',
        bargain: c('Read me the tally plainly and the names stay out?', 'Very well — but your total’s off by a decimal. Correct it and you’ll see it’s only a balance.', 'thoughtful'),
        challenge: c('This note reads like a threat. Well?', 'You’ve misread the figure. Move the decimal and your “threat” becomes a subtotal.', 'angry'),
      }),
    r('accountant-ledgerlife', 'connection', undefined, 'How does a man come to trust numbers more than people?',
      'People revise their stories. A column of figures doesn’t. I learned young which one to rely on.', 'thoughtful',
      s(
        c('What taught you that lesson?', 'A family that promised much and posted nothing. Numbers never promised; they just added up.', 'worried'),
        c('Do you really feel nothing for the people behind the sums?', 'I feel plenty. I just decline to let it corrupt the arithmetic.', 'neutral'),
        c('Spare me the ledger philosophy.', 'As you like. Sentiment was never a line item anyway.', 'neutral'),
      ),
      s(
        c('What would you set right if you could?', 'One account I signed that balanced only on paper. It’s cost me sleep, not money.', 'worried'),
        c('And what will you never do again?', 'Sign my name to a figure I know is false. Once was a lesson; twice would be a character.', 'suspicious'),
        c('We’re finished here.', 'Then the meeting adjourns.', 'neutral'),
      ),
      {
        bargain: c('Off the record — what weighs on you tonight?', 'Off the record: a set of books I can no longer pretend I didn’t read correctly. Some totals demand to be paid.', 'worried'),
        challenge: c('All this precision — what does it conceal?', 'A false entry, not a false alibi. Complicity in a fraud isn’t the same as this.', 'angry'),
      }),
    r('accountant-audit', 'intel', undefined, 'If you audited this room, who would fail the review?',
      'Several. Money leaves a trail even when a person doesn’t, and three of these guests are running a deficit they won’t admit.', 'suspicious',
      s(
        c('Whose books wouldn’t balance?', 'One who spends like a man expecting a windfall he hasn’t earned. Anticipated income is a dangerous thing.', 'thoughtful'),
        c('Do you reduce everyone to their finances?', 'Not everyone. Only the ones whose finances explain their manners.', 'neutral'),
        c('I want names, not balance sheets.', 'Names follow figures. That’s the correct order of operations.', 'neutral'),
      ),
      s(
        c('What discrepancy have you actually seen?', 'A household charge posted, then quietly reversed. Someone tidied a record that didn’t need tidying.', 'suspicious'),
        c('Could that be a clerical error?', 'Errors add entries. They don’t remove them. This was deliberate.', 'angry'),
        c('That’s enough bookkeeping.', 'Then the audit is suspended.', 'neutral'),
      ),
      {
        bargain: c('Quietly — whose finances should I follow?', 'Quietly: follow the one who reversed the charge. People only erase what they can’t afford to have read.', 'thoughtful'),
        challenge: c('You see every figure — so whose ledger are you shielding?', 'No one’s. I withhold conclusions, not entries. Draw your own from the numbers.', 'angry'),
      }),
  ],
}
